Owner and nominate fixes for OVM support
Synthetixio/synthetix pull request #1060
Opened 2021-01-17 00:48 UTC by justinjmoses

2021-03-19 15:31 UTC, ajsantander requested changes

2021-03-19 15:31 UTC, ajsantander commented on publish/src/commands/owner.js
> +	const isContract = !useOvm && code !== '0x';
So, if it has code, it's not considered a contract if its on Optimism?
Why?

2021-03-19 15:38 UTC, justinjmoses commented on publish/src/commands/owner.js
> +	const isContract = !useOvm && code !== '0x';
It basically a hacky way of saying don't use contract owners on L2 - which honestly won't stick around anyhow. I can't recall why this was necessary at the time though frankly - why was `getCode` not return `0x` when this was run?

2021-03-19 16:43 UTC, ajsantander commented on publish/src/commands/owner.js
> +	const isContract = !useOvm && code !== '0x';
Sorry, totally confused with what you're saying here 😅 

What you're doing is basically saying that "contract accounts in Optimism are considered EOAs" which I think is wrong.

2021-03-24 02:26 UTC, ajsantander approved these changes

2021-04-08 17:36 UTC, i-stam commented on publish/src/commands/owner.js
> +	const isContract = !useOvm && code !== '0x';
I talked to Kevin about this. All accounts are initially EOAs (i.e. no code), but they are turned into a contract (proxy to the smart wallet) after they send the first tx. I 'm working to address this on the new owner-multisig script.

2022-01-28 22:15 UTC, closed without merging