Add OVM exchanging functionality
Synthetixio/synthetix pull request #1086
Opened 2021-02-12 15:30 UTC by i-stam

2021-02-26 14:44 UTC, ajsantander commented on contracts/BaseSynthetix.sol
> +    function _systemActive() private view {
Why are you adding this visibility identifier?

SystemStatus.requireSystemActive() can revert, thus its not just a view.

2021-02-26 14:45 UTC, ajsantander commented on contracts/BaseSynthetix.sol
> +    function _issuanceActive() private view {
Same here.

2021-02-26 14:59 UTC, ajsantander commented on contracts/BaseSynthetix.sol
> +    function _exchangeActive(bytes32 src, bytes32 dest) private view {
The original `Synthetix._exchangeActive(...)` required these conditions:
* requireExchangeBetweenSynthsAllowed(src, dest)

And you are suggesting to change the conditions to:
* requireExchangeActive()
* requireSynthsActive(src, dest)

Which I think is a regression because the number of calls increases to two, and the actual internal checks become redundant and poorer:

Original (6 checks):
* requireExchangeBetweenSynthsAllowed(src, dest)
  * _internalRequireSystemActive();
  * _internalRequireExchangeActive();
  * _internalRequireSynthExchangeActive(sourceCurrencyKey);
  * _internalRequireSynthExchangeActive(destinationCurrencyKey);
  * _internalRequireSynthActive(sourceCurrencyKey);
  * _internalRequireSynthActive(destinationCurrencyKey);

New (4 checks, 1 redundant):
* requireExchangeActive()
  * _internalRequireSystemActive();
  * _internalRequireExchangeActive();
* requireSynthsActive(src, dest)
  * _internalRequireSystemActive(); <------- AGAIN
  * _internalRequireSynthActive(sourceCurrencyKey);
  * _internalRequireSynthActive(destinationCurrencyKey);
  
  In fact, the new suggestion would allow an exchange for two synths whose exchanging is disabled, which is a critical bug.

2021-02-26 15:19 UTC, ajsantander commented on contracts/Collateral.sol
> +    function _requireRateIsValid() private view {
As commented above, I think this is semantically incorrect.

2021-02-26 15:23 UTC, ajsantander commented on contracts/Exchanger.sol
> +        // _processTradingRewards(fee, destinationAddress);
We should definitely not do this.

If we were to just comment out calls to this internal function, we should consistently comment out all calls. I.e. `exchangeOnBehalf` also calls it, as do others.

The proper way to do this would be to simply set `tradingRewardsEnabled` to false in all deployed instances.
2.

2021-02-26 15:26 UTC, ajsantander commented on contracts/RealtimeDebtCache.sol
> -    function updateCachedSynthDebts(bytes32[] calldata currencyKeys) external {}
We should probably get @zyzek to validate this too.

2021-02-26 15:45 UTC, ajsantander commented on test/optimism/index.js
> +	// after('exit', async () => {
Please try to avoid commenting out code. If its not needed, remove it.

2021-02-26 15:46 UTC, ajsantander commented on test/optimism/synthExchange.test.js
> +	describe.only('[SYNTEXCHANGE] when exchanging synths on L2', () => {
Remove the only

2021-02-26 15:49 UTC, ajsantander commented on test/optimism/synthExchange.test.js
> +									// before('settle', async () => {
As before. Commented out code suggests that this is incomplete? If it is complete, it should be removed in a PR that is ready for review.

2021-02-26 15:50 UTC, ajsantander commented on test/optimism/synthExchange.test.js
> +									// before('settle', async () => {
Btw, it might actually be a good idea to test settlement in prod right?

2021-02-26 15:51 UTC, ajsantander requested changes
Great job @i-stam 

Reported a couple of medium things on the contracts, and general aesthetic things elsewhere.

2021-02-26 16:36 UTC, i-stam commented on contracts/BaseSynthetix.sol
> +    function _systemActive() private view {
The compiler gives warnings, reverting does not technically invalidate it as a view. Can remove if it is confusing.

2021-02-26 17:00 UTC, i-stam commented on contracts/BaseSynthetix.sol
> +    function _exchangeActive(bytes32 src, bytes32 dest) private view {
This change wasn't made by me, it was introduced by another PR, I just updated the branch because it was lost during a merge.

2021-03-02 10:25 UTC, jacko125 approved these changes

2021-03-03 17:55 UTC, i-stam commented on contracts/Exchanger.sol
> +        // _processTradingRewards(fee, destinationAddress);
It has been added back.

2021-03-03 17:55 UTC, i-stam commented on contracts/RealtimeDebtCache.sol
> -    function updateCachedSynthDebts(bytes32[] calldata currencyKeys) external {}
It has been added back, no change has been made.

2021-03-03 17:56 UTC, i-stam commented on test/optimism/synthExchange.test.js
> +									// before('settle', async () => {
Settle revert is tested, I couldn't  fast forward in ovm.

2021-03-03 18:01 UTC, justinjmoses approved these changes
Nice work

2021-03-03 18:10 UTC, merged