Configurable waiting period
Synthetixio/synthetix pull request #1093
Opened 2021-02-19 15:43 UTC by i-stam

2021-02-22 17:31 UTC, justinjmoses commented on publish/src/commands/deploy.js
> +			writeArg: useOvm ? '0' : await getDeployParameter('WAITING_PERIOD_SECS'),
this can be overridden in the params per environment instead of coding this here, no?

2021-02-22 20:58 UTC, justinjmoses commented on contracts/BaseSynthetix.sol
> +    function exchangeOnBehalf(
any reason to move this?

2021-02-22 21:00 UTC, i-stam commented on publish/src/commands/deploy.js
> +			writeArg: useOvm ? '0' : await getDeployParameter('WAITING_PERIOD_SECS'),
Done! I modified only the `params.json` file in local-ovm deployment folder because it is used by the `deploy-ovm-pair` script.

2021-02-22 21:01 UTC, justinjmoses commented on contracts/Exchanger.sol
> +            _updateSNXIssuedDebtOnExchange([sourceCurrencyKey, destinationCurrencyKey], [sourceRate, destinationRate]);
⚠️ This should still exist above - we shouldn't mix no waiting period with an assumption that the real time debt caching is being used.

2021-02-22 21:04 UTC, justinjmoses commented on publish/deployed/local-ovm/params.json
> +	{
🙏🏼 we should probably add these for kovan-ovm and mainnet-ovm as well in this PR

2021-02-22 21:05 UTC, justinjmoses requested changes
a few small comments

2021-02-23 14:25 UTC, i-stam commented
Opened a new one that triggers CI unit testing

2021-02-23 14:25 UTC, closed without merging