ci: add L2 ovm tests
Synthetixio/synthetix pull request #1119
Opened 2021-03-02 12:49 UTC by drptbl

2021-03-03 20:43 UTC, justinjmoses requested changes
One change with a parameter for a ci command

2021-03-03 20:43 UTC, justinjmoses commented on .circleci/config.yml
> +      - cmd-wait-for-hardhat
can we change the port to a parameter and pass it in and then we don't have two separate commands?

2021-03-04 16:47 UTC, drptbl commented on .circleci/config.yml
> +      - cmd-wait-for-hardhat
@justinjmoses done!

2021-03-04 19:15 UTC, justinjmoses approved these changes
🙏🏼

2021-03-04 19:16 UTC, merged