update the exchange with tracking event
Synthetixio/synthetix pull request #1139
Opened 2021-03-11 20:27 UTC by dvd-schwrtz

2021-03-11 22:42 UTC, jacko125 approved these changes

2021-03-12 07:38 UTC, jacko125 commented on contracts/Exchanger.sol
> +        _emitTrackingEvent(trackingCode, destinationCurrencyKey, amountReceived, fee);
@dvd-schwrtz Just note that this fee is the nominal sUSD fee amount of the trade, not the fee % rate.

2021-03-12 07:58 UTC, jacko125 approved these changes
lgtm

2021-03-12 15:29 UTC, i-stam approved these changes

2021-03-12 16:12 UTC, ajsantander requested changes

2021-03-12 16:14 UTC, ajsantander commented on contracts/Exchanger.sol
> +        uint fee
Same for BaseSynthetix

2021-03-12 16:18 UTC, ajsantander commented on test/contracts/BaseSynthetix.js
> +						fee: amount2,
We should probably add tests for this event in Exchanger.spec.js and make sure that it emits with the expected values during an exchange.

2021-03-12 16:19 UTC, ajsantander commented on contracts/BaseSynthetix.sol
> +        uint fee
The EXCHANGE_TRACKING_SIG declaration underneath the event declaration also needs to be updated to:
`ExchangeTracking(bytes32,bytes32,uint256,uint256)`

2021-03-12 16:20 UTC, ajsantander commented on contracts/Exchanger.sol
> +        uint fee
uint256

2021-03-15 18:38 UTC, dvd-schwrtz commented on contracts/Exchanger.sol
> +        _emitTrackingEvent(trackingCode, destinationCurrencyKey, amountReceived, fee);
@jacko125 The notes in the _exchange method say that it is based in the destination currency key amount

        // Note: `fee` is denominated in the destinationCurrencyKey.
        (amountReceived, fee, exchangeFeeRate, sourceRate, destinationRate) = _getAmountsForExchangeMinusFees(
            sourceAmountAfterSettlement,
            sourceCurrencyKey,
            destinationCurrencyKey
        );

2021-03-16 20:38 UTC, justinjmoses commented on contracts/Exchanger.sol
> +        _emitTrackingEvent(trackingCode, destinationCurrencyKey, amountReceived, fee);
wrong section - see `function _exchange`

2021-03-19 15:06 UTC, ajsantander approved these changes
Looks good!

2021-03-26 13:55 UTC, i-stam approved these changes

2021-05-17 19:20 UTC, justinjmoses commented on test/contracts/Exchanger.spec.js
> -						});
be careful here - you broke the parsing logic by removing this.

2021-05-17 19:20 UTC, justinjmoses commented on test/contracts/Exchanger.spec.js
> -								});
and here as well.

2021-05-17 19:20 UTC, justinjmoses commented on test/contracts/Exchanger.spec.js
> -						});
you can tell because the formatter on L1816 didn't fix the indents for you on save.

2021-05-20 17:49 UTC, merged