[WIP] ETHWrapper
Synthetixio/synthetix pull request #1178
Opened 2021-03-26 06:48 UTC by liamzebedee

Implements the ETHWrapper as described in [SIP-112](https://sips.synthetix.io/sips/sip-112).

To do:

- [ ] replace ETH with WETH, fix tests relating to ETH
- [ ] remove `approve` requirement for burn`
- [ ] clean, document code
- [ ] move SCCP parameters into SystemSettings

2021-04-13 04:35 UTC, liamzebedee commented
Hey @jacko125 could I get your guidance on this?

**Summary:** There's another test failing in CI - this is a smoke test for an older version of CollateralEth, when we merged a fix which solved a bug in the MultiCollateral loans logic (SIP-105). The test was left to check the old contract still worked. This test is now failing in a call to TokenStatesUSD, which seems related to the fact this PR upgrades the sUSD synth contract. 

The test -

```
      1) Contract: MultiCollateral (prod tests)
       old contracts still work
         interacting with a loan on the old ETH contract works:
     Error: Returned error: Transaction reverted without a reason
```

The Hardhat stack trace, annotated with the contract names I've grepped from the source code:

```
eth_call
  Contract call:       <UnrecognizedContract>
  From:                0x62f7a1f94aba23ed2dd108f8d23aa3e7d452565b
  To:                  0x3ff5c0a14121ca39211c95f6ceb221b86a90729e

  Error: Transaction reverted without a reason
      at <UnrecognizedContract>.<unknown> (0x05a9cbe762b36632b3594da4f082340e0e5343e8) - TokenStatesUSD
      at <UnrecognizedContract>.<unknown> (0x6c85c5198c3cc4db1b87cb43b2674241a30f4845) - SynthsUSD
      at <UnrecognizedContract>.<unknown> (0x3ff5c0a14121ca39211c95f6ceb221b86a90729e) - CollateralEth
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at HardhatNode.runCall (/Users/liamz/Documents/Work/2021_Synthetix/code/synthetix/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:366:20)
      at EthModule._callAction (/Users/liamz/Documents/Work/2021_Synthetix/code/synthetix/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:321:9)
      at HardhatNetworkProvider._sendWithLogging (/Users/liamz/Documents/Work/2021_Synthetix/code/synthetix/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:22)
      at HardhatNetworkProvider.request (/Users/liamz/Documents/Work/2021_Synthetix/code/synthetix/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:98:18)
      at JsonRpcHandler._handleRequest (/Users/liamz/Documents/Work/2021_Synthetix/code/synthetix/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:187:20)
      at JsonRpcHandler._handleSingleRequest (/Users/liamz/Documents/Work/2021_Synthetix/code/synthetix/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:166:17)
```

```
0x05a9cbe762b36632b3594da4f082340e0e5343e8 - TokenState

	"v2.35.2": {
        0x6c85c5198c3cc4db1b87cb43b2674241a30f4845 - SynthsUSD

"CollateralEth": {
        "address": "0x3FF5c0A14121Ca39211C95f6cEB221b86A90729E",
        "status": "replaced",
        "keccak256": "0x1c9a753645e530b04a7d8ac4d394154efe5b4d0c097cd3dcb410ad03d477918d",
        "replaced_in": "v2.36.0"
    },
```

This test was introduced in this PR - https://github.com/Synthetixio/synthetix/commit/86a97e1da1a6b60b7f141b26d97025218d5e6a50. We merged in a fix in v2.35.2 and this was released as part of Shaula (v2.3.5) (or 2.3.6?).

2021-04-13 10:47 UTC, jacko125 commented on contracts/BaseDebtCache.sol
> +            if (key == sETH) {
@liamzebedee  Ensure that the debtCache snapshot uses this logic to exclude the `etherWrapperSupply` from the `debtCache.takeDebtSnapshot()` function

2021-04-13 10:49 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +import "hardhat/console.sol";
remember to remove this

2021-04-13 11:02 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +        // TODO: the capacity of the contract is exclusive of the mint fees?
I think we can keep it simple to include the `total amount of synths including mint fees` that is the capacity cap

2021-04-13 12:29 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +        uint feeAmountEth = calculateBurnFee(amount);
@liamzebedee  

We should discuss how the `redemption / burn` fee is captured here.  Burning the wETH portion of the `feeAmountEth` doesn't feel right here. While we issue sUSD to the fee pool (which increases the sUSD token supply), the wETH isn't being converted before being sent to the 0x address. 

One solution is to have the wETH fee amount collected inside a fee basket that can be sold to buy sUSD that gets sent to the fee pool.

2021-04-13 12:32 UTC, jacko125 commented on contracts/SystemSettings.sol
> +    uint public constant MAX_ETHER_WRAPPER_MINT_FEE_RATE = 1e18;
These max mint and burn fee's can be discussed in the SIP and on discord with community. max 100% feels too high as a max.

2021-04-13 12:34 UTC, jacko125 commented on contracts/WETH.sol
> +contract WETH is IWETH {
@liamzebedee 

Do we need the WETH implementation contract inside Synthetix for the ETH wrapper to function on L1?

2021-04-13 12:35 UTC, jacko125 requested changes
Want to discuss how the burn / redemption fee is being clipped and sent back to feepool for stakers

2021-04-14 01:17 UTC, liamzebedee commented on contracts/WETH.sol
> +contract WETH is IWETH {
Somewhat. The WETH contract is necessary to deploy for the local network, where there is no canonical WETH contract. 

We could remove this contract dependency and instead allow the user to pass in their own address for the WETH token, similar to how WETH is defined for other networks (mainnet, kovan, etc.).

This would be a bit more overhead for someone to get started. If someone is developing a bot locally to mint/burn to the EtherWrapper, I would prefer they don't have to mess around with deploying/configuring their own WETH instance. 

Perhaps it should be moved into `test-helpers/`, away from the core contracts. What do you think?

2021-04-20 05:19 UTC, liamzebedee commented
@justinjmoses can you lend a quick look at https://github.com/Synthetixio/synthetix/pull/1178#issuecomment-818429769. Jacko is off packing. Cheers

2021-04-20 05:43 UTC, liamzebedee commented
This test is timing out. Ran on my local and passes fine. https://app.circleci.com/pipelines/github/Synthetixio/synthetix/6649/workflows/8cd82186-ff64-4aee-8864-e9923b4d196a/jobs/58288

2021-04-26 23:12 UTC, justinjmoses commented on publish/releases.json
> +		"sources": [
This should be a new release, you'll need to create a new one.

2021-04-27 23:23 UTC, jacko125 commented on contracts/SystemSettings.sol
> +    uint public constant MAX_ETHER_WRAPPER_MINT_FEE_RATE = 1e18;
@liamzebedee  We leaving these max at 100%?

2021-04-27 23:26 UTC, jacko125 commented on contracts/WETH.sol
> +contract WETH is IWETH {
putting wETH into `test-helpers` make sense for local deployment & running tests in the local deployment.

2021-05-03 01:19 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +        // the sETH issued by the contract? I'm unsure.
@liamzebedee  

When we discussed this, on `clamFees()` it should:

- `sETHIssuedByWrapper -= sETH fee burnt`
- `sUSDIssuedByWrapper += sUSD issued as fees`

2021-05-03 08:16 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +    function totalIssuedSynths(bytes32 currencyKey) public view returns (uint) {
@liamzebedee  `totalIssuedSynths()` is used in the debt pool & cache contract, it would be easier to report both the `sETHIssued` and `sUSDIssued` with one request  for the view function.

2021-05-03 08:21 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +        require(amount <= feesEscrowed, "amount to distribute too large");
Instead of having an `amount` inputted for claimFees and checking that `amount <= feesEscrowed`, would be easier to claim all the `fees Escrowed / fees pending` here.

2021-05-03 08:22 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +        uint amount_sUSD = exchangeRates().effectiveValue(ETH, amount, sUSD);
Camel case instead of `_` here ?

2021-05-03 08:41 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +        sETHBurnt = sETHBurnt.add(amount);
`sETHBurnt` should be fine to track the `amount` of sETH "clipped" fees + redemption amount of sETH being claimed here. 

Could there be an edge case / issue with `sETHIssued > sETHBurnt ? sETHIssued.sub(sETHBurnt) : 0` the clamping of the totalIssuedSynth value for sETHIssued. This should be fine as the `sETH.totalSupply()` would be less for stakers.

2021-05-03 08:48 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +        synthsETH().burn(msg.sender, principal);
As discussed, it would be easier to calculate the amount of sETH to burn from `msg.sender` by inputting the total amount of sETH being burned instead of `principal amount` that they want to redeem. 

So the amount of wETH they would recieve is `amountToBurn - feeAmountEth`. 

- The `feeAmountEth` can be then issued to the EthWrapper as fees to be collected.

2021-05-04 17:10 UTC, justinjmoses commented on publish/releases.json
> +		"name": "Alioth",
this shoudl be changed to Alnair and we should put 116 after it. cc @ajsantander @i-stam

2021-05-06 04:48 UTC, liamzebedee commented on contracts/EtherWrapper.sol
> +    function totalIssuedSynths(bytes32 currencyKey) public view returns (uint) {
Yeah good point. We have different standards for what `totalIssuedSynths` returns (in some places, it's just the aggregate USD). I like your suggestion.

2021-05-10 09:01 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +    function totalIssuedSynths(bytes32 currencyKey) public view returns (uint) {
@liamzebedee  

Any update on this? Something to change and integrate with the new debtCache changes?

2021-05-10 23:58 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +        emit Minted(msg.sender, principal, feeAmountEth, amountIn);
@liamzebedee  This would emit the event for Minted as the NativeEthWrapper on L1 if someone chooses to go through ETH -> sETH directly.

2021-05-12 02:18 UTC, jacko125 commented on contracts/EtherWrapper.sol
> +        emit Minted(msg.sender, principal, feeAmountEth, amountIn);
Not issue - NativeETHWrapper also emits another event

2021-05-12 14:33 UTC, ajsantander commented on publish/src/commands/deploy.js
> +			legacyContracts.map(async ([name, contract]) => {
Wont this call rebuild cache on the legacy contracts always? I.e. regardless of their actual need to rebuild the cache? IMO this should only be done if needed.

2021-05-12 14:43 UTC, liamzebedee commented on publish/src/commands/deploy.js
> +			legacyContracts.map(async ([name, contract]) => {
Ah dude, nice catch 🙏 haha.

2021-05-12 16:02 UTC, liamzebedee commented
**NOTE:** DO NOT MERGE BEFORE #1243 is in, as this is dependent on its changes.

2021-05-12 16:21 UTC, justinjmoses commented on publish/src/commands/deploy.js
> +		const CollateralEth = '0x3FF5c0A14121Ca39211C95f6cEB221b86A90729E';
You could use `getVersions` from `index.js` to get these rather than hardcoding them. See how we use it to get existing versions of contracts here: https://github.com/Synthetixio/synthetix/blob/master/publish/src/Deployer.js#L413-L417

2021-05-12 22:14 UTC, justinjmoses commented on contracts/BaseDebtCache.sol
> +        if (resolver.getAddress(CONTRACT_ETHER_WRAPPER) != address(0)) {
same point in #1243 - no need to actually check this, BUT we do need to make sure we now deploy `EmptyEtherCollateral` in deploy.js for `EtherWrapper` so the line below won't reject on L2. Can you please add that?

2021-05-12 22:22 UTC, justinjmoses commented on contracts/EtherWrapper.sol
> +    bytes32 private constant CONTRACT_SYNTHETIX = "Synthetix";
do you still need this and system status? you don't seem to be using either

2021-05-12 22:40 UTC, justinjmoses requested changes

2021-05-12 22:40 UTC, justinjmoses commented on contracts/Issuer.sol
> +        bytes32[] memory newAddresses = new bytes32[](14);
Qu: is this change needed anymore? If not, we can remove `Issuer` from the contracts to deploy

2021-05-12 22:40 UTC, justinjmoses commented on contracts/MockWETH.sol
> +pragma solidity ^0.5.16;
If this is for testing, can you please move it to `test-helpers`? This will also prevent it from getting coverage reports

2021-05-12 22:40 UTC, justinjmoses commented on contracts/WETH.sol
> +// @unsupported: ovm
Again, this should be `test-helpers` - it's not for the unit tests but it's still the `local` test environment.

2021-05-12 22:40 UTC, justinjmoses commented on contracts/interfaces/IWETH.sol
> +}
[np] new line at end of file

2021-05-12 22:40 UTC, justinjmoses commented on publish/deployed/kovan/config.json
> -		"deploy": false
Please remove. `prepare-deploy` will do this for you using `releases.json`

2021-05-12 22:40 UTC, justinjmoses commented on publish/deployed/kovan/config.json
> +	"EtherWrapper": {
and these

2021-05-12 22:40 UTC, justinjmoses commented on publish/deployed/local/config.json
> +	"EtherWrapper": {
you can keep these

2021-05-12 22:40 UTC, justinjmoses commented on publish/src/commands/deploy.js
> +	await deployer.deployContract({
So we're deploying this on L2? I think you want the `EmptyEtherCollateral` here instead.

2021-05-13 03:18 UTC, justinjmoses approved these changes

2021-05-13 03:59 UTC, jacko125 approved these changes

2021-05-13 04:02 UTC, merged