fix: toggle off "all" approval if set, when withdrawing other approvals
Synthetixio/synthetix pull request #1181
Opened 2021-03-26 18:19 UTC by vbstreetz

The issue at the moment is one has to perform 2 transactions in order to downgrade the powers of a delegated account from all to a single one.

Part of: https://github.com/Synthetixio/staking/issues/267

<img width="488" alt="Screenshot 2021-03-26 at 21 17 28" src="https://user-images.githubusercontent.com/60554509/112675815-acb9a780-8e78-11eb-865f-991f3c543500.png">

2021-03-29 19:18 UTC, vbstreetz commented on package.json
> +		"web3-core-helpers": "^1.3.4",
Had to install these for some reason 🤔

2021-03-29 19:19 UTC, vbstreetz commented on test/contracts/DelegateApprovals.js
> +	describe('revoking non-ALL power', () => {
@i-stam, I've added the test case for the change...

2021-03-30 11:05 UTC, vbstreetz commented
- [ ] `approveAllDelegatePowers` probably also needs to be updated in this PR i.e., should explicitly turn on all the powers.

2021-04-09 19:14 UTC, i-stam approved these changes

2021-04-13 08:32 UTC, drptbl requested changes

2021-04-13 08:32 UTC, drptbl commented on package.json
> +		"web3-core-helpers": "^1.3.4",
@vbstreetz please lock versions 🙏

2021-08-29 21:22 UTC, KillerByte requested changes
talked privately with Mitch, and we agreed this PR does not quite meet the specification of the SIP. The "Approve All" flag uses a separate flag, and so if it is set, the other flags remain unset. Therefore, if a user approves all, and then tries to disable a specific permission, they would just be removing all permissions and would have to re-approve all the remaining ones.

2022-01-28 22:17 UTC, closed without merging