add accrued interest utility contract and add a test for it
Synthetixio/synthetix pull request #1200
Opened 2021-04-09 20:45 UTC by dvd-schwrtz

2021-04-16 16:21 UTC, i-stam requested changes

2021-04-16 16:21 UTC, i-stam commented on contracts/AccruedInterestUtil.sol
> +        require(!invalid, "Rates are invalid");
This is controversial, usually, in the Synthetix codebase reverting inside view functions is avoided. Better to return instead, even if this is a standalone function.

2021-04-20 18:49 UTC, dvd-schwrtz commented on contracts/AccruedInterestUtil.sol
> +        require(!invalid, "Rates are invalid");
done! @i-stam

2021-06-10 15:26 UTC, i-stam approved these changes

2021-06-15 19:13 UTC, justinjmoses commented on contracts/AccruedInterestUtil.sol
> +        // 5. If the loan was just opened, don't record any interest. Otherwise multiple by the amount outstanding.
this comment isn't strictly correct - there's no recording happening here.

2021-06-15 19:13 UTC, justinjmoses commented on contracts/AccruedInterestUtil.sol
> +    // define and emit events
there is no event emission here

2022-12-22 00:27 UTC, closed without merging