Sip-116 Update Implementation
Synthetixio/synthetix pull request #1212
Opened 2021-04-21 18:48 UTC by i-stam

2021-04-22 20:34 UTC, ajsantander commented on contracts/BaseSynthetixBridge.sol
> +    bytes32 private constant INITIATIONSUSPENDED_SIG = keccak256("FeePeriodClosed()");
Bad hash

2021-04-22 20:37 UTC, ajsantander commented on contracts/BaseSynthetixBridge.sol
> +        proxy._emit("", 1, INITIATIONSUSPENDED_SIG, 0, 0, 0);
Shouldnt that `1` be a `0` (that's the number of topics of the event)
Same below.

2021-04-22 20:43 UTC, ajsantander commented
@i-stam I think you should update the base branch to develop, and then this to the base branch.

2021-04-22 20:52 UTC, ajsantander commented on contracts/SynthetixBridgeToOptimism.sol
> +        synthetixERC20().transferFrom(messageSender, synthetixBridgeEscrow(), amount);
Might be a good idea to require that the escrow address is not zero here, and whenever tokens are sent there, to reduce the risk of burning tokens whenever that is not set correctly for some reason

2021-04-22 20:55 UTC, ajsantander commented on contracts/SynthetixBridgeToOptimism.sol
> +    function finalizeWithdrawal(address to, uint256 amount) external optionalProxy {
What's the optionalProxy modifier for here?

2021-04-22 20:55 UTC, ajsantander commented on contracts/SynthetixBridgeToOptimism.sol
> +        synthetixERC20().transferFrom(synthetixBridgeEscrow(), to, amount);
Here too, I think we need protection when the escrow is not set

2021-04-22 20:58 UTC, ajsantander commented on contracts/SynthetixBridgeToOptimism.sol
> +                synthetixERC20().transfer(synthetixBridgeEscrow(), escrowedAccountBalance);
Protection for escrow not set?

2021-04-22 20:59 UTC, ajsantander commented on contracts/SynthetixBridgeToOptimism.sol
> +        proxy._emit(abi.encode(to, amount), 2, DEPOSITINITIATED_SIG, bytes32(uint256(uint160(from))), 0, 0);
Shouldnt that `2` be a `1`?

2021-04-22 21:00 UTC, ajsantander commented on contracts/SynthetixBridgeToOptimism.sol
> +            2,
Same here, only 1 indexed param, so 1 topic right?

2021-04-22 21:00 UTC, ajsantander commented on contracts/SynthetixBridgeToOptimism.sol
> +        proxy._emit(abi.encode(amount), 2, REWARDDEPOSIT_SIG, bytes32(uint256(uint160(account))), 0, 0);
only 1 topic

2021-04-22 21:01 UTC, ajsantander commented on contracts/SynthetixBridgeToOptimism.sol
> +        proxy._emit(abi.encode(amount), 2, WITHDRAWALFINALIZED_SIG, bytes32(uint256(uint160(to))), 0, 0);
only 1 topic

2021-04-22 21:03 UTC, ajsantander commented on contracts/SynthetixBridgeToOptimism.sol
> +    function notifyRewardAmount(uint256 amount) external requireInitiationActive optionalProxy {
This is probably not related to this diff, but why aren't we transferring any tokens in this case? I.e. taking possession of a deposit.

2021-04-22 21:11 UTC, ajsantander commented on contracts/SynthetixBridgeToBase.sol
> +            2,
Review num topics

2021-04-22 21:12 UTC, ajsantander commented on contracts/SynthetixBridgeToBase.sol
> +        proxy._emit(abi.encode(amount), 2, DEPOSITFINALIZED_SIG, bytes32(uint256(uint160(to))), 0, 0);
Review num topics

2021-04-22 21:12 UTC, ajsantander commented on contracts/SynthetixBridgeToBase.sol
> +        proxy._emit(abi.encode(amount), 1, DEPOSITFINALIZED_SIG, 0, 0, 0);
Review num topics

2021-04-22 21:12 UTC, ajsantander commented on contracts/SynthetixBridgeToBase.sol
> +        proxy._emit(abi.encode(to, amount), 2, WITHDRAWALINITIATED_SIG, bytes32(uint256(uint160(from))), 0, 0);
Review num topics

2021-04-22 21:14 UTC, ajsantander requested changes
Looking good @i-stam !!
Do you want to also include the escrow contract in this PR?

2021-04-23 15:28 UTC, i-stam commented on contracts/SynthetixBridgeToOptimism.sol
> +    function finalizeWithdrawal(address to, uint256 amount) external optionalProxy {
This is because in theory we want to also allow people to interact directly with the contract, bypassing the bridge e..g the messenger calling directly the bridge instead of the proxy

2021-04-23 15:28 UTC, i-stam commented on contracts/BaseSynthetixBridge.sol
> +    bytes32 private constant INITIATIONSUSPENDED_SIG = keccak256("FeePeriodClosed()");
Fixed

2021-04-23 15:37 UTC, i-stam commented on contracts/SynthetixBridgeToOptimism.sol
> +        proxy._emit(abi.encode(to, amount), 2, DEPOSITINITIATED_SIG, bytes32(uint256(uint160(from))), 0, 0);
the sig is part of the topics

2021-04-23 15:37 UTC, i-stam commented on contracts/SynthetixBridgeToOptimism.sol
> +            2,
same as above

2021-04-23 15:38 UTC, i-stam commented on contracts/SynthetixBridgeToOptimism.sol
> +                synthetixERC20().transfer(synthetixBridgeEscrow(), escrowedAccountBalance);
what kind of protection (not 0x0)?

2021-04-23 15:41 UTC, i-stam commented on contracts/SynthetixBridgeToOptimism.sol
> +        synthetixERC20().transferFrom(messageSender, synthetixBridgeEscrow(), amount);
It should be taken care by `requireAndGetAddress(CONTRACT_SYNTHETIXBRIDGEESCROW);`

2021-04-26 17:25 UTC, elenadimitrova reviewed
Reviewed integration with optimism contracts only. @ajsantander can you remind me of which legacy functions you suspected might be obsolete?

2021-04-27 19:10 UTC, justinjmoses commented on contracts/BaseSynthetixBridge.sol
> +    ) public Owned(_owner) Proxyable(_proxy) MixinSystemSettings(_resolver) {
[np] I suggest putting `Proxyable` first as it uses the first arg (I accept that `ExternStateToken.sol` also has this issue but I think it's cleaner this way)

2021-04-27 19:10 UTC, justinjmoses commented on contracts/BaseSynthetixBridge.sol
> +        proxy._emit("", 1, INITIATIONSUSPENDED_SIG, 0, 0, 0);
Why emit an empty string?

2021-04-27 19:12 UTC, justinjmoses commented on contracts/SynthetixBridgeEscrow.sol
> +        emit Approval(msg.sender, _bridge, _amount);
I think a secondary Approval is probably excessive, no? This transaction will emit an Approval from SNX already....

2021-04-27 23:13 UTC, i-stam commented on contracts/SynthetixBridgeToOptimism.sol
> +        proxy._emit(abi.encode(amount), 2, REWARDDEPOSIT_SIG, bytes32(uint256(uint160(account))), 0, 0);
same as above

2021-04-27 23:13 UTC, i-stam commented on contracts/SynthetixBridgeToOptimism.sol
> +        proxy._emit(abi.encode(amount), 2, WITHDRAWALFINALIZED_SIG, bytes32(uint256(uint160(to))), 0, 0);
same as above

2021-04-27 23:16 UTC, i-stam commented on contracts/SynthetixBridgeEscrow.sol
> +        emit Approval(msg.sender, _bridge, _amount);
this is true, just wanted to enable this contract to emit events, it would be easier to track how mane times an approval was enabled or revoked.

2021-04-27 23:33 UTC, i-stam commented on contracts/BaseSynthetixBridge.sol
> +    ) public Owned(_owner) Proxyable(_proxy) MixinSystemSettings(_resolver) {
I noticed this too, FeePool suffers from the same issue. it was indeed confusing but I wanted to make sure that nothing was impacted before changing it. I 'll fix it.

2021-04-27 23:35 UTC, i-stam commented on contracts/SynthetixBridgeToOptimism.sol
>      event DepositInitiated(address indexed from, address to, uint256 amount);
No real reason, they were there before `iOVM_L1TokenGateway` was implemented and we just updated them, it is easy to remove them, even though I think that some of tests might fail and will need updating. Thanks for pointing this out.

2021-04-27 23:36 UTC, i-stam commented on package.json
> +		"@eth-optimism/contracts": "0.2.4",
updated!

2021-04-27 23:39 UTC, i-stam commented
> Reviewed integration with optimism contracts only. @ajsantander can you remind me of which legacy functions you suspected might be obsolete?

@elenadimitrova I think that Ale was referring to `getFinalizeDepositL2Gas()` and `getFinalizeWithdrawalL1Gas()`

2021-04-28 12:01 UTC, i-stam commented on contracts/BaseSynthetixBridge.sol
> +        proxy._emit("", 1, INITIATIONSUSPENDED_SIG, 0, 0, 0);
just the equivalent of empty bytes array.

2021-04-28 12:14 UTC, i-stam commented on contracts/SynthetixBridgeToOptimism.sol
> +    function notifyRewardAmount(uint256 amount) external requireInitiationActive optionalProxy {
This is a good point, I think there is a problem here.

2021-04-28 12:14 UTC, i-stam commented on contracts/SynthetixBridgeToBase.sol
> +            2,
done

2021-04-28 12:14 UTC, i-stam commented on contracts/SynthetixBridgeToBase.sol
> +        proxy._emit(abi.encode(amount), 2, DEPOSITFINALIZED_SIG, bytes32(uint256(uint160(to))), 0, 0);
done

2021-04-28 12:14 UTC, i-stam commented on contracts/SynthetixBridgeToBase.sol
> +        proxy._emit(abi.encode(amount), 1, DEPOSITFINALIZED_SIG, 0, 0, 0);
done

2021-04-28 12:14 UTC, i-stam commented on contracts/SynthetixBridgeToBase.sol
> +        proxy._emit(abi.encode(to, amount), 2, WITHDRAWALINITIATED_SIG, bytes32(uint256(uint160(from))), 0, 0);
done

2021-04-28 16:18 UTC, i-stam commented on contracts/BaseSynthetixBridge.sol
> +        proxy._emit("", 1, INITIATIONSUSPENDED_SIG, 0, 0, 0);
uses bytes("") or bytes(0) casting

2021-04-28 17:38 UTC, justinjmoses commented on contracts/SynthetixBridgeEscrow.sol
> +        emit Approval(msg.sender, _bridge, _amount);
Ok. Maybe call it `ApproveBridge` then?

2021-04-28 17:40 UTC, justinjmoses commented on contracts/SynthetixBridgeToBase.sol
> +    ) external optionalProxy onlyOptimismBridge {
no optional proxy required here - it's only called via the bridge

2021-04-28 17:41 UTC, justinjmoses commented on contracts/SynthetixBridgeToBase.sol
> +    function finalizeDeposit(address to, uint256 amount) external optionalProxy onlyOptimismBridge {
same again - no optional proxy needed here

2021-04-28 17:43 UTC, justinjmoses commented on contracts/SynthetixBridgeToBase.sol
> +    function finalizeRewardDeposit(uint256 amount) external optionalProxy onlyOptimismBridge {
same as above

2021-04-29 07:43 UTC, elenadimitrova commented
@i-stam @ajsantander just confirming that if you were using the Abstract base classes you would have had to override `getFinalizeWithdrawalL1Gas` and `getFinalizeDepositL2Gas`, however in your case here these are not required as you pass in the gasLimit directly in `sendMessage` calls. Basically you can remove them.

2021-04-29 07:57 UTC, i-stam commented
> @i-stam @ajsantander just confirming that if you were using the Abstract base classes you would have had to override `getFinalizeWithdrawalL1Gas` and `getFinalizeDepositL2Gas`, however in your case here these are not required as you pass in the gasLimit directly in `sendMessage` calls so you can safely remove them.

thanks for the feedback @elenadimitrova

2021-04-29 19:31 UTC, merged