Minimal Proxy pattern for Binary Options
Synthetixio/synthetix pull request #1216
Opened 2021-04-21 22:11 UTC by dgornjakovic

Minimal Proxy pattern applied to Binary Options:

- BinaryOptionMarketMastercopy added as in VirtualSynths
- BinaryOptionMarket now uses IAddressResolver as implemented in VirtualSynths
- Adapted tests accordingly
- Owned interface extended with an internal method which is called from BOM initialize logic

2021-04-27 08:24 UTC, zyzek requested changes

2021-04-27 08:24 UTC, zyzek commented on contracts/OwnedWithInit.sol
> +        initOwner(_owner);
Could this constructor not be empty?

2021-04-27 08:24 UTC, zyzek commented on contracts/BinaryOptionMarket.sol
>          options.long = new BinaryOption(_creator, longBid);
Should the Binary Option instances themselves not use minimal proxies?

2021-04-27 08:24 UTC, zyzek commented on contracts/BinaryOptionMarketMastercopy.sol
> +contract BinaryOptionMarketMastercopy is BinaryOptionMarket {
Not sure why we need this master copy; can't we just stub out the constructor of the BOM contract itself?

2021-04-27 08:46 UTC, dgornjakovic commented on contracts/OwnedWithInit.sol
> +        initOwner(_owner);
Goog point, it could now that a separate owned contract is used. Will adapt.

2021-04-27 08:47 UTC, dgornjakovic commented on contracts/BinaryOptionMarket.sol
>          options.long = new BinaryOption(_creator, longBid);
Good hint, will investigate.

2021-04-27 08:48 UTC, dgornjakovic commented on contracts/BinaryOptionMarketMastercopy.sol
> +contract BinaryOptionMarketMastercopy is BinaryOptionMarket {
That I wouldnt know, I followed Brett's approach from the VirtualSynths MinimalProxy impl.

2021-04-27 20:07 UTC, dgornjakovic commented on contracts/OwnedWithInit.sol
> +        initOwner(_owner);
Constructors is now empty

2021-04-27 20:07 UTC, dgornjakovic commented on contracts/BinaryOptionMarket.sol
>          options.long = new BinaryOption(_creator, longBid);
Implemented

2021-04-27 20:08 UTC, dgornjakovic commented on contracts/BinaryOptionMarket.sol
>          options.long = new BinaryOption(_creator, longBid);
Gas costs to create a new market dropped 5.5x with this change!

2021-04-30 06:14 UTC, zyzek commented on contracts/BinaryOptionMarketMastercopy.sol
> +contract BinaryOptionMarketMastercopy is BinaryOptionMarket {
Doesn't this need to set `initialized = true`?

2021-05-05 20:30 UTC, justinjmoses commented on contracts/OwnedWithInit.sol
> +contract OwnedWithInit {
Let's try to de-dupe code here. I think a `BaseOwned.sol` with the shared code including `initOwner` but no constructor and `Owned.sol` which extends from the base and adds a constructor that simply calls `initOwner`

2021-05-05 20:34 UTC, justinjmoses commented on publish/src/commands/deploy.js
> +					gray('is newer and cache status'),
technically it's newer but not as new as the latest that doesn't even need cache rebuilding.

2021-05-05 20:35 UTC, justinjmoses commented on publish/src/commands/deploy.js
> +					console.error(red(err));
Won't all of your new markets appear in here? Because they don't have a `isResolverCached()` function anymore and thus they don't need cache rebuilding. You can safely skip them for this part.

2021-05-18 15:45 UTC, justinjmoses commented
After some discussion, it's been agreed that Thales will clone these contracts and redeploy them going forward, rather than modifying these directly.

2021-05-18 15:45 UTC, closed without merging