Add Alnair entry to releases.json
Synthetixio/synthetix pull request #1222
Opened 2021-04-23 13:56 UTC by ajsantander

Also makes a slight modification to the prepare-deploy script, allowing it to pick a version depending on the evm/ovm nature of the release.

2021-04-23 21:31 UTC, justinjmoses commented on publish/src/commands/prepare-deploy.js
> +	const release = releases.reverse().find(release => (useOvm ? release.ovm : !release.ovm));
Yeah slick. I like it.

2021-04-23 21:32 UTC, justinjmoses commented on publish/releases.json
> +		"sources": ["SynthetixBridgeToBase", "Synthetix", "DebtCache"],
Hmmm - what about `SystemStatus`? I think we should deploy the latest version from Bellatrix to L2 which was https://sips.synthetix.io/sips/sip-109

2021-04-23 21:32 UTC, justinjmoses requested changes
Just an additional contract to L2.

2021-04-26 18:05 UTC, ajsantander commented on publish/releases.json
> +		"sources": ["SynthetixBridgeToBase", "Synthetix", "DebtCache"],
Ah yeah, good call.

2021-04-26 19:29 UTC, justinjmoses approved these changes

2021-04-26 19:53 UTC, i-stam approved these changes
lgtm, just a reminder, we should add the SynthexBridgeEscrow contract when sip-116 is merged.

2021-04-26 23:26 UTC, justinjmoses commented
Damn - gonna have to go back to *Alnair*. *Regora* is going to be used for the sCOIN and sMSFT releases.

2021-04-26 23:26 UTC, justinjmoses requested changes
Gonna have to use *Alnair* now

2021-04-26 23:29 UTC, justinjmoses commented on publish/releases.json
> +			"DebtCache",
You need to also add `Exchanger` - it's for SIP-118 - and add that below as well

2021-04-27 16:21 UTC, ajsantander commented on publish/releases.json
> +			"DebtCache",
Oh wait, now we see what you mean. Yeah, adding it.

2021-04-27 22:44 UTC, justinjmoses commented on publish/releases.json
> +		"name": "Alnair",
Please make sure #1227 is merged first and then add this after.

2021-04-28 14:51 UTC, ajsantander commented on publish/releases.json
> +		"name": "Alnair",
Done, updated this branch to develop and changed Alnair's minor to 44

2021-04-28 15:43 UTC, justinjmoses approved these changes

2021-04-28 18:00 UTC, merged