MultiCollateral/CollateralEth debt is not excluded correctly from debt calculations
Synthetixio/synthetix pull request #1243
Opened 2021-05-05 01:28 UTC by liamzebedee

Synths issued by the MultiCollateral and v1 Collateral ETH and sUSD contracts is incorrectly excluded by the debt cache. The debt is currently subtracted from the respective totalSupply's of each token, however, if the synth is exchanged into another synth, the debt may not be excluded here. 

This PR includes:

 * A test which demonstrates the bugged logic
 * Changes to fix it

2021-05-05 06:21 UTC, zyzek requested changes

2021-05-05 06:21 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +        for (uint i = 0; i < numValues; i++) {
If we're concerned about inefficiency due to this extra loop, we could compute `excludedDebt` inside `_issuedSynthValues` and return it as another value e.g. the return signature of `_currentSynthDebts` would become `(uint[] memory snxIssuedDebts, uint collateralIssuedDebt, bool anyRateIsInvalid)`.

2021-05-05 06:21 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +        excludedDebt = excludedDebt.add(susdValue);
Just do `uint excludedDebt = susdValue;`, no need for the declaration `uint excludedDebt = 0;` above.

2021-05-05 06:21 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +            if (collateralManager().isSynthManaged(key)) {
Not for this PR, but it strikes me that an external function call to the collateral manager for every synth is pretty inefficient. Surely it would be more effective to just return an array of the synths with non-snx collateral and iterate those.

2021-05-05 06:21 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +            if (key == sUSD) {
Given that the code here is identical, and code size might be an actual issue on L2 so I wonder whether collapsing the `sUSD` and `sETH` cases back into one conditional might actually be preferable here. Not too fussed either way, especially if we're well below the L2 contract size limit.

2021-05-05 06:21 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +            if (key == sETH) {
Tiny nitpick: this could be an `else if`.

2021-05-05 06:21 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +        total = total.sub(excludedDebt);
Worried that we might be able to break the whole system if `excludedDebt > total`.

Feels like we should either set the total system debt to zero in this case, or throw a more informative error message.

This seems like an odd case, but it could happen if, for example, everyone issued sUSD on the multicollateral contracts, converted to sBTC, then the price of sBTC collapsed, meaning there was not enough value left in the system to pay back the loans. This is just a top of the head thing so maybe I'm missing something here? Seems like a pretty fundamental problem if correct though.

2021-05-05 06:21 UTC, zyzek commented on test/contracts/DebtCache_bug.js
> +		describe('after minting sETH issued by non-SNX collateral, and the full supply of sETH is exchanged for another synth', async () => {
Do you think it's worth moving this test case into the main `Collateral.sol` test file?

2021-05-05 07:57 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +        total = total.sub(excludedDebt);
Hm, I guess they could issue against SNX to pay back the loans. So then we have:

1. Issue 50000 sUSD against ETH.
2. Convert sUSD into 1 sBTC
3. sBTC goes to zero
4. Issue 50000 more sUSD against SNX
5. repay the original debt
6. Now the circulating supply of synths is zero again, so the system debt is zero
7. Your SNX is free, so you repaid the debt for no cost.

Maybe there is something wrong with this analysis, but I feel like the debt pool ramifications of the multicollat system may not have been completely characterised.

2021-05-05 08:39 UTC, jacko125 commented on contracts/BaseDebtCache.sol
> +            if (collateralManager().isSynthManaged(key)) {
@zyzek  Good point, should have on the manager `managedSynths() return (bytes32[] keys)` to save gas. Checked that the CollateralManager doesn't have anything like that.

2021-05-05 11:16 UTC, jacko125 commented on contracts/BaseDebtCache.sol
> +            if (key == sUSD) {
Could reuse this block of code here: 

```            bool isSUSD = key == sUSD;
            if (isSUSD || key == sETH) {
                IEtherCollateral etherCollateralContract =
                    isSUSD ? IEtherCollateral(address(etherCollateralsUSD())) : etherCollateral();
     ```

2021-05-05 11:23 UTC, jacko125 commented on contracts/BaseDebtCache.sol
> +        excludedDebt = excludedDebt.add(susdValue);
@liamzebedee  

In the takeDebtSnapshot function it also removes the `collateralManager().totalShort()` from the total debt so it should be removed from the `takeSnapshot()` function. 

https://github.com/Synthetixio/synthetix/blob/master/contracts/DebtCache.sol#L23-L24

2021-05-05 19:46 UTC, justinjmoses commented on test/contracts/DebtCache_bug.js
> +contract('DebtCache', async accounts => {
Why not combine this as a new describe block in the DebtCache tests? This would introduce a new pattern `_bug` to test files which isn't very scalable.

2021-05-06 03:18 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +        excludedDebt = excludedDebt.add(susdValue);
good point

2021-05-06 03:22 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +        excludedDebt = excludedDebt.add(susdValue);
ugh, looks like some code is repeated. I'll try address this too so that we only calculate debt and issued synth values in one place, while maintaining the same external API.

2021-05-06 03:22 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +        for (uint i = 0; i < numValues; i++) {
Agreed, let's not add another O(n).

2021-05-06 03:23 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +            if (collateralManager().isSynthManaged(key)) {
Nice spot! @zyzek

2021-05-06 03:52 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +        total = total.sub(excludedDebt);
> Worried that we might be able to break the whole system if excludedDebt > total.

Isn't `excludedDebts` always smaller than `total`, since `total` is based in the total supply of each synth?

> Maybe there is something wrong with this analysis, but I feel like the debt pool ramifications of the multicollat system may not have been completely characterised. Do we think this is possible to abuse without the debt load going completely all the way to zero?

I think you're right. Basically, if synths created by MC loans go to $0, then the debt excluded will decrease, and thus the global debt will increase. Conversely, if the synths created by MC loans go to $infinity, then the debt excluded will increase, and the global debt will decrease. However, as I mentioned before, the global debt is calculated as the total supply of all synths, so it can't go negative. 

So you have:

 1. 5,000 sBTC MC debt, worth $250M
 2. 5,000 totalSupply of MC debt, worth $250M
 3. sBTC goes up 10x
 4. sBTC MC debt is $2,500M, totalSupply of MC debt is $2,500M

So the debt can never go negative. However, the MC synths can certainly begin to outweight SNX debt, such that the MC loans can pay off SNX debt. ie. there is arbitrage between the different loan systems

> Do we think this is possible to abuse without the debt load going completely all the way to zero?

I did some back of the spreadsheet calculations here - https://docs.google.com/spreadsheets/d/1yn7xDie2b3D3n0M2PUPc4piV3u0FkNjSZ_X_ISVIUYY/edit?usp=sharing

Maybe you can go into it and clarify it. I think what you're identifying is that cost of MC debt and SNX debt can be arbed? But I don't think it poses a risk to the total debt calculations.

2021-05-06 03:54 UTC, liamzebedee commented on test/contracts/DebtCache_bug.js
> +contract('DebtCache', async accounts => {
Yeah nah this was definitely temp. I just wanted to write a quick repro - what would be better, instead of this test, is some proper testing for the debt calculations on how it excludes various collateral subsystems (multi, ethercollateralv1).

2021-05-07 03:30 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +        total = total.sub(excludedDebt);
Left a scenario in the spreadsheet. This still seems like it's a problem. If the debt is all ETH-backed sUSD for example, then moves into sBTC, the total value of circulating synths can fall below the debt in the multicollateral contract.

The answer here is to check if `excludedDebt` exceeds the total synth value and clamp to zero if so. This still means that SNX issuers will be able to issue more sUSD for free in this case, I suppose. Another possibility is, for example, if the MC-issued debt is all denominated in sETH, if sETH appreciates after those synths have been converted to something else that did not appreciate so quickly, then this will decrease the system debt, allowing more issuance by SNX stakers.

2021-05-07 03:44 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +        (uint shortValue, ) = collateralManager().totalShort();
I was going to say we could do this inside the loop as well rather than adding an additional function call, but I guess `collateralManager().isSynthManaged(key)` doesn't actually guarantee anything about whether the synth is or is not shortable.

2021-05-07 03:49 UTC, zyzek requested changes

2021-05-07 03:49 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +                excludedDebt = excludedDebt.add(issuedSynths.multiplyDecimalRound(rates[i]));
Was going to suggest we could pull this out of the loop and put it next to the `totalShort` call below, but I realised internally that function fetches the rates individually rather than all at once, so I'm not clear on whether that would be more or less efficient, gas-wise. My hunch is that it would be better since `CollateralManager` won't iterate over synths it isn't managing.

2021-05-07 04:15 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +                excludedDebt = excludedDebt.add(issuedSynths.multiplyDecimalRound(rates[i]));
I did start having a go on this - https://github.com/Synthetixio/synthetix/tree/debt-cache-bug@CollateralManager.managedSynths

I'll see if there's enough time to work through a good change by EOD. Still waiting for hardhat fork to cache properly so I'm not slown down by this anymore.

2021-05-07 07:53 UTC, jacko125 commented on contracts/BaseDebtCache.sol
> +        total = total.sub(excludedDebt);
Interesting scenario, I guess in this case the SNX stakers would be able to mint sUSD up to the excess `excludedDebt` amount and still be able to withdraw their SNX as they won't incur any debt. Which would give them a free sUSD that is fully backed by other collateral.

2021-05-10 00:43 UTC, jacko125 commented on contracts/BaseDebtCache.sol
> +                excludedDebt = excludedDebt.add(issuedSynths.multiplyDecimalRound(rates[i]));
@zyzek  I guess including it inside the loop iterating over all synths was programatic way of ensuring that if we added a new synth type to the Multicollateral loans it would be automatically picked up.

2021-05-10 03:31 UTC, jacko125 commented on contracts/DebtCache.sol
> +        (uint[] memory currentValues, uint excludedDebt) = _issuedSynthValues(currencyKeys, currentRates);
@liamzebedee  @zyzek  How would this impact the partial debt cache updates for synths that only change? Would increase the gas usage for partial debt cache updates as it needs to load all of the excluded Debt?

2021-05-10 04:55 UTC, liamzebedee commented on contracts/DebtCache.sol
> +        (uint[] memory currentValues, uint excludedDebt) = _issuedSynthValues(currencyKeys, currentRates);
@jacko125 good question. There might be an issue in how we do the partial debt updates anyways right now:

 * note that `_updateCachedSynthDebtsWithRates` is called with `currencyKeys` which we will update, which is later passed down into `_issuedSynthValues`. 
 * in `_issuedSynthValues`, we exclude MultiCollateral debt during the loop over `currencyKeys`. This is supposed to save on gas by doing it in the `currencyKeys` loop, instead of doing a separate loop for all MC-issued synths. However, in this example, `currencyKeys` may not include all the MC synths.

> Would increase the gas usage for partial debt cache updates as it needs to load all of the excluded Debt?

It doesn't "load" all excluded debt atm. This is a problem with the current deployment and the code in the PR. The impact might not be huge, since we already do the regular debt snapshot.

2021-05-10 05:43 UTC, jacko125 commented on contracts/DebtCache.sol
> +        (uint[] memory currentValues, uint excludedDebt) = _issuedSynthValues(currencyKeys, currentRates);
@liamzebedee  

Got it, only when we pass in the `sETH, sUSD, sBTC` as keys to `_issuedSynthValues` would the excludeDebt include the MC-issued synths.

2021-05-10 05:53 UTC, jacko125 commented on test/contracts/DebtCache.js
> +					assert.bnEqual(totalNonSnxBackedDebt.add(rate), await debtCache.totalNonSnxBackedDebt());
@liamzebedee  this test should be adding `oneETH` as that is 1 ETH short opened instead of checking `rate`.

2021-05-10 08:16 UTC, jacko125 commented on contracts/DebtCache.sol
> +        (uint[] memory currentValues, uint excludedDebt) = _issuedSynthValues(currencyKeys, currentRates);
@zyzek 

Would be good to get your thoughts on the partial synth cache update as now we calculate the `excludedDebt` as nominal USD value instead of subtracting the `sETH supply` and `sUSD supply` for MC-loans before they are returned by `_totalIssuedSynths` for each synth caching. 

 This would mean that the `_cachedSynthDebt[key]` would be the `synth.totalSupply()` as returned by `_totalIssuedSynths` and would be inaccurately adding the excluded debt on partial debt cache updates for MC synths.

2021-05-10 09:42 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +                excludedDebt = excludedDebt.add(issuedSynths.multiplyDecimalRound(rates[i]));
I was just thinking one single call to `totalLong` would sweep away this complexity.

2021-05-10 09:51 UTC, zyzek commented on contracts/DebtCache.sol
> +        (uint[] memory currentValues, uint excludedDebt) = _issuedSynthValues(currencyKeys, currentRates);
I think the excluded debt component should be treated as its own 'Synth'. At any rate a debt component which can be updated independently by passing in a currency key corresponding to it, and with its own delta logic etc. I tend to think this should also be how cross-chain debt communication should be handled. I'm also wondering here, whether issuance and burning by the multicollat contracts are properly handled. As I recall, the mint function just adds sUSD debt, but if the mint is coming from an MC contract, it should not do this. This needs to be checked, but if it's correct, then multicollateral may be creating false volatility in the debt cache as loans opening and closing could be erroneously affecting the cached debt value.

2021-05-10 18:11 UTC, justinjmoses commented
@liamzebedee can you please add an entry for *Aloith* in `releases.json` in this PR and add the changed files?

2021-05-11 02:31 UTC, jacko125 commented on contracts/BaseDebtCache.sol
> +        return (total, isInvalid && isAnyNonSnxDebtRateInvalid);
@liamzebedee  `isAnyNonSnxDebtRateInvalid` would be overlapping with the same `invalid` flag because if one of the rates are in invalid already for `exchangeRates().ratesAndInvalidForCurrencies(currencyKeys)` , it would also be invalid with `isAnyNonSnxDebtRateInvalid`. Not sure if this is needed?

2021-05-11 02:43 UTC, jacko125 commented on contracts/DebtCache.sol
> +        // Always update the cached value of the excluded debt -- it's computed anyway.
@liamzebedee @zyzek 

Would be interesting to see how much extra gas this adds to the `exchange()` function when it calls down into here to update the cache for the 2x pairs. 

We could have a separate function for `synthetix.exchange()` that doesn't need to recompute the `excludedDebt` and leave the cached value for recalculating the ``cachedSum && currentSum`` so not to recompute the excludedDebt as that shouldn't have changed during the exchange function.

2021-05-11 07:55 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +    function totalNonSnxBackedDebt() external view returns (uint excludedDebt, bool isInvalid) {
Nice catch, I missed this

2021-05-11 08:00 UTC, liamzebedee commented on contracts/DebtCache.sol
> +        // Always update the cached value of the excluded debt -- it's computed anyway.
Yeah I will do some gas estimations tomorrow.

2021-05-12 01:38 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +        return (total, isInvalid && isAnyNonSnxDebtRateInvalid);
Hmmm - I think it's better to be defensive, even if we know `availableCurrencyKeys` is a superset of the synths that  `_totalNonSnxBackedDebt` will receive as input. We currently don't have tests for these `isInvalid` calculations re: the excluded debt, and the gas saving here is negligible. What do you reckon?

2021-05-12 14:52 UTC, jacko125 commented on contracts/DebtCache.sol
> +        uint excludedDebtSum;
@liamzebedee  excludedDebtSum should be set to the _cachedDebtSum when it's not recomputing the excluded Debt

2021-05-12 15:03 UTC, jacko125 approved these changes
LGTM

2021-05-12 17:23 UTC, justinjmoses commented on test/prod/MultiCollateral.prod.js
> +	xdescribe('when using multiple types of loans', () => {
This should no longer be needed once #1259 is merged. cc @ajsantander

2021-05-12 20:02 UTC, justinjmoses commented on contracts/BaseDebtCache.sol
> +        if (address(issuer().synths(sETH)) != address(0) && resolver.getAddress(CONTRACT_ETHERCOLLATERAL) != address(0)) {
do you think it's necessary to spend the extra gas to check that `sETH` exists? I can't imagine how EtherCollateral could exist in the resolver but no sETH? And further, even if so, the `sETH` rate would be invalid.

2021-05-12 20:04 UTC, justinjmoses commented on contracts/BaseDebtCache.sol
> +            excludedDebt = etherCollateralsUSD().totalIssuedSynths(); // Ether-backed sUSD
[np] might be better to add this to `excludedDebt` as it's order-dependent right now and if the order was ever switched this would override the existing value of `excludedDebt`

2021-05-12 20:08 UTC, justinjmoses commented on contracts/SafeDecimalMath.sol
> +    function floorsub(uint a, uint b) internal pure returns (uint) {
Because this is internal, it simply gets imported into the source right? So no need to worry about new deploys.

2021-05-12 20:09 UTC, justinjmoses commented on publish/deployed/kovan/config.json
> -		"deploy": false
Please no need to set these. Invoking `prepare-deploy` does this for you via `releases.json`

2021-05-12 20:09 UTC, justinjmoses commented on publish/deployed/mainnet/config.json
> -		"deploy": false
same as here

2021-05-12 20:11 UTC, justinjmoses approved these changes
A few comments and suggestions here and there.

2021-05-12 20:31 UTC, justinjmoses commented on contracts/BaseDebtCache.sol
> +        if (resolver.getAddress(CONTRACT_ETHERCOLLATERAL_SUSD) != address(0)) {
Because `DebtCache` uses `MixinResolver`, it ultimately runs `AddressResolver.requireAndGetAddress()` meaning that this can't happen. On L2, this contract equates to an empty contract: `EmptyEtherCollateral`. Thus, this check is unnecessary (as it defaults to returning `0` for total supply when empty)

2021-05-12 20:31 UTC, justinjmoses commented on contracts/BaseDebtCache.sol
> +        if (address(issuer().synths(sETH)) != address(0) && resolver.getAddress(CONTRACT_ETHERCOLLATERAL) != address(0)) {
Same point about the `EtherCollateral` contract.

2021-05-12 20:32 UTC, justinjmoses commented on contracts/BaseDebtCache.sol
> +        if (resolver.getAddress(CONTRACT_COLLATERALMANAGER) != address(0)) {
and again here - on L2 we deploy `EmptyCollateralManager`

2021-05-12 20:34 UTC, justinjmoses requested changes
A few suggestions, nothing major but should be considered.

2021-05-13 01:12 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +            excludedDebt = etherCollateralsUSD().totalIssuedSynths(); // Ether-backed sUSD
Good point

2021-05-13 02:13 UTC, justinjmoses approved these changes

2021-05-13 02:15 UTC, jacko125 approved these changes

2021-05-13 02:27 UTC, merged