Hook up futures to system debt.
Synthetixio/synthetix pull request #1294
Opened 2021-05-26 04:51 UTC by zyzek

2021-05-26 05:52 UTC, liamzebedee requested changes

2021-05-26 05:52 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +        ICollateralManager _collateralManager = collateralManager();
Oh, nice. 🙏

2021-05-26 05:52 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +            uint _futuresDebt,
I can see that you're separating the futuresDebt from the excludedDebt, presumably in order to better specify what parts of the debt we're recomputing (below with recomputeFuturesDebt) - is that a fair appraisal?

2021-05-26 05:52 UTC, liamzebedee commented on contracts/DebtCache.sol
> +        // Unused code until we circle back to refactor the debt system
When do we wanna do this?

2021-05-26 05:52 UTC, liamzebedee commented on contracts/DebtCache.sol
> +        // Unused code until we circle back to refactor the debt system
Given that we're launching futures on L2 only (IIRC), should we be feature flagging this debt logic so it only runs on L2? I don't think we're using the two debt caches anymore.

2021-05-26 05:52 UTC, liamzebedee commented on contracts/DebtCache.sol
> +        // Unused code until we circle back to refactor the debt system
I suppose this ties into the broader question of where are we hosting the source of truth for the debt pool, in context of launching the futures platform? Will there be two, one for L1 and L2, and then eventually moving to the off-chain pool?

2021-05-26 05:52 UTC, liamzebedee commented on contracts/DebtCache.sol
> -        cachedSum = cachedSum.floorsub(_cachedSynthDebt[EXCLUDED_DEBT_KEY]);
How come you're moving this into the `if(recomputeExcludedDebt)` block above? Even if we don't update the excluded debt, I'm fairly sure we still want to subtract it?

2021-05-26 10:03 UTC, zyzek commented on contracts/BaseDebtCache.sol
> +            uint _futuresDebt,
Futures debt is a positive contribution to the debt pool, so it can't be part of the excluded debt number. But it doesn't belong in the Synth debt values list; it's a distinct category. In principle I think both the futures debt and the excluded debt should just be in their own separate functions, but overhauling this interface isn't the purpose of this PR so I wanted to keep it as light touch as possible for now.

2021-05-26 11:17 UTC, zyzek commented on contracts/DebtCache.sol
> -        cachedSum = cachedSum.floorsub(_cachedSynthDebt[EXCLUDED_DEBT_KEY]);
In the end, we compute `debt = debt - (cachedSum - cachedExcludedDebt) + (currentSum - excludedDebtSum)` (`cachedExcludedDebt` is shorthand for `_cachedSynthDebt[EXCLUDED_DEBT_KEY]`).
But if `recomputeExcludedDebt` is false, then `excludedDebtSum` is initialised to `cachedExcludedDebt`, so we're really computing the following:

`debt - (cachedSum - cachedExcludedDebt) + (currentSum - cachedExcludedDebt)`
`debt - cachedSum + currentSum + cachedExcludedDebt - cachedExcludedDebt`
`debt - cachedSum + currentSum`

In other words, there is no effect if the we aren't recomputing the excluded debt, so we should just save the computation.

One caveat here: the floorsub screws up this logic. I haven't got a clear grasp on what it means logically for the cached value to hit the floor and the current value not to, or vice versa. One reason I've annotated that this logic doesn't feel quite right.

2021-05-26 11:17 UTC, zyzek commented on contracts/DebtCache.sol
> +        // Unused code until we circle back to refactor the debt system
Yes, since futures will only be on L2, we will eventually as part of the port-futures-to-L2 work have to generate a stubbed-out L1 version of the futures manager that returns 0 for the debt. Or we could generate different versions of the debt cache for each layer which only takes into account the debt components it needs.

2021-05-27 01:04 UTC, liamzebedee commented on contracts/DebtCache.sol
> +        // Unused code until we circle back to refactor the debt system
In terms of the tradeoff of engineering cost, option (1) with stubs seems easier, with the tradeoff being that you have to keep up-to-date with what's deployed on L1 vs. L2 to understand the gas costs of the contracts (as some calls will be stubbed and others won't).

2021-05-27 01:14 UTC, liamzebedee commented on contracts/BaseDebtCache.sol
> +            uint _futuresDebt,
Nice, that makes sense.

2021-05-27 02:11 UTC, liamzebedee approved these changes

2021-05-27 02:11 UTC, liamzebedee commented on contracts/DebtCache.sol
> -        cachedSum = cachedSum.floorsub(_cachedSynthDebt[EXCLUDED_DEBT_KEY]);
Right - this makes sense to me. Are we gonna get Iosiro to look at it too? 

If you feel like going the extra mile, I think we'd do well with a test for this logic block. Could be good to ease your mind re: the floorsub conundrum too.

@jacko125 feeding you in ☕, you should be aware of this change.

2021-05-28 03:00 UTC, zyzek commented on contracts/DebtCache.sol
> -        cachedSum = cachedSum.floorsub(_cachedSynthDebt[EXCLUDED_DEBT_KEY]);
I assume iosiro will look at all code changes; not sure how to test this without adding a public function in an inheriting test contract, and even then I don't think this behaviour will actually be used until the debt cache is refactored.

2021-05-28 03:01 UTC, zyzek commented on contracts/DebtCache.sol
> +        // Unused code until we circle back to refactor the debt system
Agreed.

2021-05-28 03:02 UTC, merged