Futures order fee charged from margin
Synthetixio/synthetix pull request #1314
Opened 2021-06-04 07:12 UTC by zyzek

2021-06-21 09:56 UTC, liamzebedee commented on contracts/FuturesMarket.sol
> +            0 <= _marginPlusProfitFunding(position, fundingSequenceIndex, price).sub(int(order.fee)); // Margin has not dipped negative due to fees, profit, funding
We can confirm an order where the `margin + profit - funding` is 0. Cool.

2021-06-21 10:21 UTC, liamzebedee requested changes

2021-06-21 10:21 UTC, liamzebedee commented on contracts/FuturesMarket.sol
> +        uint margin = _realiseMargin(position, fundingIndex, price, -int(order.fee));
So the fee is charged at time of confirmation, though it is set according to the skew at the time the order is submitted. 

I read in SIP-80 that the fee is an incentive to reduce skew:

> Users pay a fee whenever they open or increase a position. However, we wish to incentivise reduction of skew, so we distinguish between maker and taker fees. A maker is someone reducing skew and a taker is someone increasing it, and so we charge makers less than takers, possibly even zero insofar as this is possible in the presence of front-running

What would be the effect on the incentive if the market skew flips (eg. from long to short) in the tx before a user is confirms their order, potentially as a frontrun?

2021-06-21 10:21 UTC, liamzebedee commented on contracts/FuturesMarket.sol
> +        int newSize = int(margin.add(order.fee)).multiplyDecimalRound(order.leverage).divideDecimalRound(int(price));
Not sure if this applies in futures - but would it be beneficial to introduce some slippage parameter that bounds the user's margin in this case? Like Uniswap where your order is cancelled if the price slips too much.

2021-06-22 01:55 UTC, zyzek commented on contracts/FuturesMarket.sol
> +        uint margin = _realiseMargin(position, fundingIndex, price, -int(order.fee));
We will potentially over- or under-charge in some cases, so there is a slight incentive for the market to overcorrect. Ultimately I'm not to concerned, though, because the real lever is supposed to be the funding rate. From this perspective, the fee being computed ahead of time is intended to make sure the cost of entering a position is known ahead of time, so that the funding rate is more reliable to arbitrage.

2021-06-22 01:56 UTC, zyzek commented on contracts/FuturesMarket.sol
> +        int newSize = int(margin.add(order.fee)).multiplyDecimalRound(order.leverage).divideDecimalRound(int(price));
Yes, I agree this would be a great feature to have. It's actually one of the stretch tasks listed here: https://github.com/Synthetixio/issues/issues/102
If you want to implement it, feel free the break the stretch task out into a ticket of its own.

2021-06-24 01:42 UTC, liamzebedee commented on contracts/FuturesMarket.sol
> +        uint margin = _realiseMargin(position, fundingIndex, price, -int(order.fee));
Okay. We're comfortable with saying that the fee is a fixed fee, set ahead of time, paid to stakers. I'm okay with that.

2021-06-29 07:03 UTC, merged

2021-06-30 00:02 UTC, liamzebedee commented on test/contracts/FuturesMarket.js
> +		// In this section, where inscrutable numbers are being compared, we're
🙏