Add optimism scripts to run Optmism via npm
Synthetixio/synthetix pull request #1324
Opened 2021-06-09 00:17 UTC by leomassazza

2021-06-09 12:11 UTC, ajsantander requested changes
It does look good, and I do wanna merge it, but I'm a bit hesitant to the idea of adding 6 new npm scripts for something that is used only in a particular type of tests. Devs looking into this will probably be confused with all the different scripts.

IMO, we should have a single entry point (probably a hardhat task) that by default figures out what needs to be done. All these different flavors can be flags in the task. If you do go that way, much of this would have to be re-implemented via javascript, which should be fine. You can look at .circleci/pack.js for usage of the "execa" library, to see how to call shell commands from javascript.

Finally, I would suggest that we modify .circleci/src/jobs/job-integration-tests.yml to use these commands. Don't forget to run `npm run build:ci` afterwards to regenerate the master .circleci/config.yml file from the .circleci/src folder.

2021-06-10 04:21 UTC, leomassazza commented
> It does look good, and I do wanna merge it, but I'm a bit hesitant to the idea of adding 6 new npm scripts for something that is used only as a pre-step of running a particular type of tests. Devs looking into this will probably be confused as hell with all the different scripts.
> 
> IMO, we should have a single entry point (probably a hardhat task `npx hardhat ops`) that by default figures out what needs to be done. All these different flavors can be flags in the task that expose fine tuned functionality for advanced users. If you do go that way, much of this would have to be re-implemented via javascript, which should be fine. You can look at .circleci/pack.js for usage of the "execa" library, which allows you to call shell commands from javascript.
> 
> Finally, I would suggest that we modify .circleci/src/jobs/job-integration-tests.yml to use these commands. Don't forget to run `npm run build:ci` afterwards to regenerate the master .circleci/config.yml file from the .circleci/src folder.

@ajsantander changes applied

2021-06-10 12:41 UTC, ajsantander commented on hardhat/tasks/task-ops.js
> +	.addFlag('stop', 'Deploy an l1 instance before running the tests')
Wrong description?

2021-06-10 12:45 UTC, leomassazza commented on hardhat/tasks/task-ops.js
> +	.addFlag('stop', 'Deploy an l1 instance before running the tests')
yup. copy/paste failed

2021-06-10 12:51 UTC, ajsantander commented on hardhat/tasks/task-ops.js
> +				await _stop({ opsPath });
Why is this `_stop` awaited? Also other `_stop`'s don't seem to be awaited.

2021-06-10 12:57 UTC, leomassazza commented on hardhat/tasks/task-ops.js
> +				await _stop({ opsPath });
Good catch! I forgot to remove the await when moved from asynch to synch in execa

2021-06-10 13:43 UTC, ajsantander requested changes
This is awesome. Super clean and easy to read.

However, I'd love to see the CLI output in the start process and keep the process open.
This should be possible with `docker-compose up` (with no `-d` option).

I tried a few things but couldn't get something reliable. Honestly, I've always found execa weird and hard to get right if you're not doing basic things. And I feel like it's gotten weirder. Thus, I recommend that we go low level to node's child_process api (https://nodejs.org/api/child_process.html#child_process_class_childprocess), and gain more control. Something like this should work:

```
async function _start({ opsPath }) {
	console.log(gray('  start ops'));
	spawn('sh', ['-c', `cd ${opsPath}/ops && docker-compose up`], { stdio: 'inherit' });
	await new Promise(() => {}); // Keeps the process open
}
```

2021-06-10 15:19 UTC, ajsantander approved these changes
Thank you!

2021-06-10 17:20 UTC, merged