Implement FuturesMarketSettings contract for storing the market params
Synthetixio/synthetix pull request #1337
Opened 2021-06-15 10:27 UTC by i-stam

2021-06-21 04:18 UTC, zyzek requested changes

2021-06-21 04:18 UTC, zyzek commented on contracts/FuturesMarket.sol
> -    Parameters public parameters;
As this has been deleted, re-add a `parameters` function to preserve the interface:

```
function parameters() external returns (...) {
    return _marketSettings().getAllParameters(baseAsset);
}
```

I suspect this will make things easier for the integrations, but happy to be corrected if you disagree.

2021-06-21 14:22 UTC, i-stam commented on contracts/FuturesMarket.sol
> +    function recomputeFunding(uint price) external returns (uint lastIndex) {
Shouldn't it also be protected? We should prevent anyone from calling it arbitrarily right?

2021-06-22 07:46 UTC, i-stam commented on contracts/FuturesMarket.sol
> -    Parameters public parameters;
added

2021-06-22 07:47 UTC, i-stam commented on contracts/FuturesMarket.sol
> +    function assetPriceRequireNotInvalid() external view returns (uint) {
It has been removed after the latest refactoring.

2021-06-23 06:58 UTC, zyzek commented on contracts/FuturesMarket.sol
> +    function recomputeFunding(uint price) external returns (uint lastIndex) {
I don't think there are actually any real issues with allowing funding to be computed by anyone. In fact it's probably more accurate the more it's called. But let me think about this a bit and get back to you.

2021-06-23 12:52 UTC, i-stam commented on contracts/FuturesMarket.sol
> +    function recomputeFunding(uint price) external returns (uint lastIndex) {
I see. I just added it because there state that is being added when it is called, thus, it can lead to spam attacks and I am not sure about how it affects the system. I m going to investigate further.

2021-06-25 07:39 UTC, zyzek requested changes
I just realised we also need to add deployment step to deploy.js as well.

2021-06-25 07:39 UTC, zyzek commented on test/contracts/setup.js
> +			deps: [
This doesn't seem quite right.

1. Why does the market need all these dependencies like `SynthetixEscrow` and such?
2. Aren't we missing an entry in this list of the `FuturesMarketSettings` contract?
3. Doesn't `FuturesMarketETH` also need to be updated if `FuturesMarketBTC` does?
4. If some of these dependencies are actually required somewhere, e.g. `Issuer` for handling margin account deposits/withdrawals, shouldn't this be in the `FuturesMarketManager` entry?

2021-06-27 10:58 UTC, i-stam commented on test/contracts/setup.js
> +			deps: [
good catch, I think this is a mistake. I copied them there accidentally from the actual test file when I was testing and forgot to delete them. The problem is that the dependencies are not handled properly in the setup script. Imo when a contract is not accessed directly in a test file it shouldn't be mentioned explicitly but handled in the setup script via dependencies. Currently, the FuturesMarketManager contract is not deployed properly in the base branch too.

2021-06-27 10:59 UTC, i-stam commented
> I just realised we also need to add deployment step to deploy.js as well.

I was thinking of doing this when we actually have a few proper integration tests so we can actually see if it deployed properly.

2021-06-29 05:18 UTC, zyzek approved these changes

2021-06-29 05:32 UTC, merged