kovan-ovm-futures (refactored)
Synthetixio/synthetix pull request #1400
Opened 2021-07-12 06:29 UTC by liamzebedee

2021-07-12 06:46 UTC, zyzek requested changes

2021-07-12 06:46 UTC, zyzek commented on publish/deployed/kovan-ovm/config.json
> -		"deploy": false
`kovan-ovm` shouldn't be touched yet, I think.

2021-07-12 06:46 UTC, zyzek commented on publish/deployed/kovan-ovm-futures/feeds.json
> +	"SNX": { "asset": "SNX", "feed": "0x0" }
We'll need feeds for `SNX`, `ETH`, `BTC`, and `LINK`. These can all be copied from the `kovan-ovm` feeds file, as we can share aggregators between the two deployments.... Or are we running an oracle manually for this deployment?

2021-07-12 06:46 UTC, zyzek commented on publish/deployed/kovan-ovm-futures/feeds.json
> +	"SNX": { "asset": "SNX", "feed": "0x0" }
Might as well add the corresponding synths to the deployment while we're at it for debt pool calculation tests.

2021-07-13 01:10 UTC, zyzek approved these changes

2021-07-22 07:04 UTC, zyzek commented on publish/deployed/kovan-ovm-futures/config.json
> +{
If the deployment has actually completed, should these not be `false`?

2021-07-22 07:06 UTC, zyzek requested changes
Is `publish/deployed/local-ovm/deployment.json ` actually supposed to be committed?

2021-07-22 07:06 UTC, zyzek commented on publish/deployed/kovan-ovm-futures/synths.json
> +		"name": "sETH",
Didn't we need `sBTC` and `sLINK` as well?

2021-07-22 07:06 UTC, zyzek commented on publish/deployed/kovan-ovm-futures/config.json
> +{
If the deployment has actually completed, should these not be `false`?

2021-07-22 07:09 UTC, liamzebedee commented on publish/deployed/kovan-ovm-futures/synths.json
> +		"name": "sETH",
Do we? I thought synths.json are for synths we are enabling/deploying, whereas we just need their feeds.

2021-07-22 07:09 UTC, liamzebedee commented on publish/deployed/kovan-ovm-futures/config.json
> +{
Yeah I realise this now. Will update.

2021-07-23 02:09 UTC, zyzek approved these changes
Looks good to me.

2021-07-23 02:28 UTC, merged