Introduces an L2 governance bridge
Synthetixio/synthetix pull request #1402
Opened 2021-07-12 21:35 UTC by ajsantander

Part of https://github.com/Synthetixio/issues/issues/246

2021-07-15 19:50 UTC, ajsantander commented on contracts/MixinSystemSettings.sol
> +    bytes32 internal constant SETTING_CROSS_DOMAIN_RELAY_GAS_LIMIT = "crossDomainRelayGasLimit";
Since we're relaying a new kind of message to L2, it needs its own cross domain gas limit setting.

2021-07-15 19:51 UTC, ajsantander commented on hardhat/tasks/task-interact.js
> -						provider,
FYI: Fly by fix, this wasn't needed.

2021-07-15 19:52 UTC, ajsantander commented on publish/deployed/goerli-ovm/config.json
> +	},
FYI: Adding the new contracts in all the config.json's...
(Pls check that ovm deploys get OwnerRelayOnOptimism, and evm deploys get OwnerRelayOnEthereum)

2021-07-15 19:53 UTC, ajsantander commented on publish/releases.json
> +		"sips": [999]
TODO: Need SIP number here

2021-07-15 19:53 UTC, ajsantander commented on publish/src/commands/connect-bridge.js
> +		OwnerRelay: OwnerRelayOnEthereum,
FYI: This script also connects the owner relays now. I could have renamed the file to connect-bridges, but didn't want to mess up the diff for you guys.

2021-07-15 19:54 UTC, ajsantander commented on test/contracts/OwnerRelayOnEthereum.js
> +const chalk = require('chalk');
I encourage you to look at the mocking in the unit tests, it's interesting, especially in OwnerRelayOnOptimism.js

2021-07-15 19:55 UTC, ajsantander commented on test/contracts/SystemSettings.js
> +
Fly by tidy up: no code duplication pls 🙏

2021-07-15 19:56 UTC, ajsantander commented on contracts/OwnerRelayOnOptimism.sol
> +    function finalizeRelay(address target, bytes calldata data) external {
This is the gist of the PR

2021-07-15 19:57 UTC, ajsantander commented on contracts/OwnerRelayOnOptimism.sol
> +    function acceptOwnershipOn(address target) external {
Notice this accessory function: It allows us to nominate ownership and accept it, all purely L2 transactions. The idea is to use this function when we change the owner of all the L2 contracts to OwnerRelayOnOptimism, instead of having to relay dozens of `acceptOwnership` calls.

2021-07-15 19:58 UTC, ajsantander commented on test/integration/dual/relay.integration.js
> +					const tx = await OwnerRelayOnOptimism.connect(ownerL2).acceptOwnershipOn(
Using that handy `acceptOwnershipOn` function here.

2021-07-15 19:59 UTC, ajsantander commented on test/integration/dual/relay.integration.js
> +				const tx = await OwnerRelayOnEthereum.connect(ownerL1).initiateRelay(
✨ 
An L1 owner tx changes a system setting on L2.

2021-07-15 20:00 UTC, ajsantander commented on test/integration/dual/relay.integration.js
> +				const tx = await OwnerRelayOnEthereum.connect(ownerL1).initiateRelay(
🧙 
An L1 tx nominates a new owner on L2.

2021-07-15 20:01 UTC, ajsantander commented on test/integration/utils/bootstrap.js
> +	before('bootstrap layer 1 and layer 2 instances', async () => {
🚸

2021-07-15 20:04 UTC, ajsantander commented on test/integration/utils/bootstrap.js
> +	before('bootstrap layer 1 and layer 2 instances', async () => {
![come-on-maaate](https://user-images.githubusercontent.com/550409/125850383-ba072592-a144-4b4c-8b6e-b64f46cb5d17.jpeg)

2021-07-15 20:23 UTC, leomassazza commented on publish/releases.json
> +		"sips": [999]
SIP-167

2021-07-16 15:41 UTC, leomassazza commented on publish/releases.json
> +		"ovm": true,
ovm: false for OwnerRelayOnEthereum

2021-07-16 16:12 UTC, justinjmoses commented on publish/deployed/mainnet/config.json
> +	"OwnerRelayOnEthereum": {
so you shouldn't commit these - recall the prepare script will enable it

2021-07-16 21:41 UTC, leomassazza commented on test/contracts/OwnerRelayOnOptimism.js
> +		it('called the function on the target contract', async () => {
shouldn't we validate the ownership actually changed?

2021-07-16 21:55 UTC, leomassazza approved these changes
LGTM. Made a few comments. Please check those.

2021-07-16 22:50 UTC, K-Ho commented on contracts/OwnerRelayOnEthereum.sol
> +            uint32(getCrossDomainMessageGasLimit(CrossDomainMessageGasLimits.Relay))
Depends on how much you care about L1 gas costs, but you might want this to be variable - e.g. for a simple L2 tx you might want it to be set lower vs a more complicated L2 tx. Otherwise you could just default it to 11m gas

2021-07-19 16:53 UTC, ajsantander commented on contracts/OwnerRelayOnEthereum.sol
> +            uint32(getCrossDomainMessageGasLimit(CrossDomainMessageGasLimits.Relay))
Will do! Thanks @K-Ho

2021-07-19 17:00 UTC, ajsantander commented on publish/releases.json
> +		"ovm": true,
Fixed

2021-07-19 17:02 UTC, ajsantander commented on publish/deployed/mainnet/config.json
> +	"OwnerRelayOnEthereum": {
Right! Undoing...

2021-07-19 17:14 UTC, ajsantander commented on test/contracts/OwnerRelayOnOptimism.js
> +		it('called the function on the target contract', async () => {
Nope. What we're calling here is the mocked function `MockedOwnedL1.acceptOwnership()` which actually does nothing. In this test, we only want to assert that calling `OwnerRelayOnOptimism.acceptOwnershipOn(...)` ends up calling that mock.

What you are suggesting is tested here: https://github.com/Synthetixio/synthetix/pull/1402/files#diff-bace10c6169c2b1a2e3c7d69a63b775d5e11c3c5cba28636b2edf595e9bd80b7R50

2021-07-19 18:41 UTC, ajsantander commented
@leomassazza @justinjmoses 

I introduced a non-trivial change suggested by @K-Ho:
`OwnerRelayOnEthereum.initiateRelay(address target, bytes data)` becomes `OwnerRelayOnEthereum.initiateRelay(address target, bytes data, uint32 xGasLimit)`, so that we have finer control over L1 costs in the relay. If zero is used, the default in SystemSettings is taken.

2021-07-20 23:37 UTC, ajsantander commented on contracts/OwnerRelayOnEthereum.sol
> +            uint32(getCrossDomainMessageGasLimit(CrossDomainMessageGasLimits.Relay))
Implemented

2021-07-21 08:49 UTC, justinjmoses commented on publish/releases.json
> +			"minor": 999
version number check before merge :pray: - Dubhe is first in #1407

2021-07-21 08:51 UTC, justinjmoses commented on publish/src/commands/deploy/deploy-core.js
> +	if (useOvm) {
No - please don't switch on `useOvm` - you don't need to because the respective config.json files have the right flags - so just include both and trust the configs to figure it out.

2021-07-21 08:52 UTC, justinjmoses commented on test/contracts/OwnerRelayOnEthereum.js
> +		MockedMessenger = await smockit(
you don't want to use `prepareSmocks`?

2021-07-21 13:35 UTC, ajsantander commented on publish/releases.json
> +			"minor": 999
Ok, will do!

2021-07-21 13:36 UTC, ajsantander commented on publish/src/commands/deploy/deploy-core.js
> +	if (useOvm) {
Right!
Fixed.

2021-07-21 13:49 UTC, ajsantander commented on test/contracts/OwnerRelayOnEthereum.js
> +		MockedMessenger = await smockit(
My preference is to be more explicit, and show the reader exactly what is going on, without assuming that how `prepareSmocks` works. I also don't like the fact that you have to assign a set of addresses to the tool, and like to leave that to smockit.

But if you insist, I can update the PR to use the tool.

2021-08-17 17:09 UTC, i-stam commented on contracts/OwnerRelayOnEthereum.sol
> +        bytes memory messageData = abi.encodeWithSelector(IOwnerRelayOnOptimism(0).finalizeRelay.selector, target, data);
`IOwnerRelayOnOptimism.finalizeRelay.selector` should also work and it is a bit cleaner

2021-08-18 17:52 UTC, ajsantander commented on contracts/OwnerRelayOnEthereum.sol
> +        bytes memory messageData = abi.encodeWithSelector(IOwnerRelayOnOptimism(0).finalizeRelay.selector, target, data);
Incoming in https://github.com/Synthetixio/synthetix/pull/1466

2021-08-19 23:06 UTC, justinjmoses requested changes
Mostly nitpicks but one important fix wrt constructor arg ordering

2021-08-19 23:06 UTC, justinjmoses commented on publish/src/commands/deploy/configure-system-settings.js
> +		await runStep({
Note that adding this here will revert if SystemSettings isn't deployed.

2021-08-19 23:06 UTC, justinjmoses commented on publish/src/commands/deploy/deploy-core.js
> +		args: [account, addressOf(readProxyForResolver)],
The order here is flipped / let's make it consistent with the other contracts. (Owner is first then resolver IiRC)

2021-08-19 23:06 UTC, justinjmoses commented on publish/src/commands/deploy/deploy-core.js
> +		args: [account, addressOf(readProxyForResolver)],
Or rather the contract above has the wrong order

2021-08-24 12:28 UTC, ajsantander commented on contracts/OwnerRelayOnEthereum.sol
> +        emit RelayBatchInitiated(targets, payloads);
We intentionally tried to avoid this, since it would significantly increase the gas cost of a batched relay.

2021-08-24 12:29 UTC, ajsantander commented on contracts/TemporarilyOwned.sol
> +        expiryTime = now + _ownershipDuration;
Do you mean because of an arithmetic overflow?

2021-11-17 18:15 UTC, justinjmoses commented on publish/src/commands/deploy/deploy-core.js
> +		args: [account, addressOf(readProxyForResolver)],
actually I see why this is - because owner is temp for OwnerRelayOnOptimism. I think we should reverse the order of these definitions - so `OwnerRelayOnEthereum` is deployed first - as it uses the standard mechanism

2021-11-18 18:07 UTC, justinjmoses commented on contracts/TemporarilyOwned.sol
> +        require(_duration > 0, "Duration cannot be 0");
this is not required - allow `0` so that the owner can effectively end this early

2021-11-18 18:20 UTC, justinjmoses commented on publish/src/commands/deploy/configure-system-settings.js
> +		expected: input => input !== '0', // only change if zero
please add `readTarget: previousSystemSettings` as well as above (changed since you copied the block here)

2021-11-18 18:24 UTC, justinjmoses commented on test/contracts/TemporarilyOwned.js
> +				await onlyGivenAddressCanInvoke({
please also add the `reason`

2021-11-18 18:24 UTC, justinjmoses commented on test/contracts/TemporarilyOwned.js
> +		it('should not allow nominated owner to accept ownership after expiration', async () => {
👍🏼

2021-11-18 18:26 UTC, justinjmoses commented on test/contracts/TemporarilyOwned.js
> +		it('should not nominate new owner when not invoked by current contract owner', async () => {
can you also check to be sure you can't nominate or accept after expiry? You've tested the modifier above but should assert here that the modifier is actually being used.

2021-11-18 19:11 UTC, barrasso commented on contracts/TemporarilyOwned.sol
> +        require(_duration > 0, "Duration cannot be 0");
https://github.com/Synthetixio/synthetix/commit/b33a1cdefab43ac5368d064a731b78754d02c647

2021-11-18 19:12 UTC, barrasso commented on test/contracts/TemporarilyOwned.js
> +				await onlyGivenAddressCanInvoke({
https://github.com/Synthetixio/synthetix/commit/cb07d300cc1ce3aaa0cd211b1d5ac5c44cd1eafb

2021-11-18 19:12 UTC, barrasso commented on test/contracts/TemporarilyOwned.js
> +		it('should not nominate new owner when not invoked by current contract owner', async () => {
https://github.com/Synthetixio/synthetix/commit/cb07d300cc1ce3aaa0cd211b1d5ac5c44cd1eafb

2021-11-23 16:52 UTC, barrasso commented on publish/src/commands/deploy/configure-system-settings.js
> +		expected: input => input !== '0', // only change if zero
https://github.com/Synthetixio/synthetix/commit/5b3624a1ef0c5a04829633fe97e90f9b11c963e2

2021-11-23 21:31 UTC, justinjmoses approved these changes

2021-11-23 21:31 UTC, merged