Futures Market Settings v2
Synthetixio/synthetix pull request #1404
Opened 2021-07-14 02:24 UTC by liamzebedee

2021-07-19 06:54 UTC, zyzek requested changes

2021-07-19 06:54 UTC, zyzek commented on contracts/FuturesMarketData.sol
> +    function getAllParameters(bytes32 baseAsset) public view returns (Parameters memory) {
Not sure this needs to be exposed publicly given that it already exists on the market itself, and also in the various market summaries as well. But I guess I can see an argument for being able to fetch the parameters by asset without having to go through the manager first. I'll leave this up to you.

2021-07-19 06:54 UTC, zyzek commented on contracts/FuturesMarketSettings.sol
> +    function futuresMarketManager() internal view returns (IFuturesMarketManager) {
For consistency, I'd prefer a leading underscore for internal functions.

2021-07-19 06:54 UTC, zyzek commented on contracts/FuturesMarketSettings.sol
> +        require(_sUSD <= getFuturesMinInitialMargin(), "fee is greater than min margin");
Change this string to `min margin < liquidation fee` so that it's clear which fee we're talking about, while still fitting into 32 bytes.

2021-07-19 06:54 UTC, zyzek commented on contracts/FuturesMarketSettings.sol
> +    function futuresLiquidationFee() external view returns (uint) {
Not sure if there's still a need to prefix these with the word "futures" now that they're in a futures-specific contract. We can probably just go with `liquidationFee` and `minInitialMargin`.

2021-07-19 06:54 UTC, zyzek commented on contracts/FuturesMarketSettings.sol
> +    function allParameters(bytes32 _baseAsset)
`allParameters` -> `parameters` for consistency with the market contract function name. And we can probably rename `setAllParameters` similarly.

2021-07-19 06:54 UTC, zyzek commented on contracts/FuturesMarketSettings.sol
> +    /* ========== MUTATIVE FUNCTIONS ========== */
"Mutative" means that the functions change the contract's state, but there are views underneath this heading. Please make sure getters exist under the views heading and setters under the mutative heading, or else delete the inconsistent headings.

2021-07-19 06:54 UTC, zyzek commented on contracts/FuturesMarketData.sol
> +    function _getParameters(bytes32 baseAsset) internal view returns (Parameters memory) {
Rename to `_parameters` as per the comment I left on the settings contract. If you decide to leave `getAllParameters` then rename that one to just `parameters`.

2021-07-19 06:54 UTC, zyzek commented on contracts/MixinFuturesMarketSettings.sol
> +    function getAllParameters(bytes32 _baseAsset)
`getAllParameters` is inconsistent with the name on market itself, so just rename it to `getParameters`.

2021-07-19 23:07 UTC, liamzebedee commented on contracts/FuturesMarketSettings.sol
> +    function futuresMarketManager() internal view returns (IFuturesMarketManager) {
Ah, I see we have two patterns - one with `_` and one without. I can use the one without for this case.

2021-07-20 06:29 UTC, zyzek approved these changes

2021-07-20 06:30 UTC, merged