SIP-142 deprecate ethercollateral loans
Synthetixio/synthetix pull request #1414
Opened 2021-07-20 12:45 UTC by jacko125

2021-07-21 13:23 UTC, justinjmoses requested changes
Also we need an entry in releases.JSON for these changes

2021-07-21 13:23 UTC, justinjmoses commented on package.json
> +		"@nomiclabs/ethereumjs-vm": "^4.2.2",
Why this?

2021-07-22 12:59 UTC, jacko125 commented on package.json
> +		"@nomiclabs/ethereumjs-vm": "^4.2.2",
![image](https://user-images.githubusercontent.com/8297593/126642895-f3a11bec-969c-4211-9752-6b5b011b04b2.png)

2021-07-26 08:25 UTC, justinjmoses commented on publish/releases.json
> +		"name": "Mirfak",
Note: in terms of timing, this will likely come after the exchanging release on L2 this week and thus need to use the next release.

2021-07-26 08:28 UTC, justinjmoses approved these changes
Thanks! But let's HOLD on merging until after the L2 release.

2021-07-26 08:35 UTC, justinjmoses commented on package.json
> +		"@nomiclabs/ethereumjs-vm": "^4.2.2",
According to Kelvin, this is no longer needed with hardhat 2.5.0 - so if you've merged in develop you can remove this

2021-07-26 08:43 UTC, jacko125 commented on publish/releases.json
> +		"name": "Mirfak",
That's fine, will move it to next release

2021-08-04 10:13 UTC, merged