Collapsible shorts and collateral refactor
Synthetixio/synthetix pull request #1427
Opened 2021-07-27 03:01 UTC by barrasso

https://github.com/Synthetixio/issues/issues/257

https://github.com/Synthetixio/issues/issues/264

2021-07-27 23:41 UTC, jacko125 commented on contracts/Collateral.sol
> +        state.updateLoan(loan);
CollateralState can be internalised as a mapping in the collateral contracts.

2021-07-28 00:47 UTC, barrasso commented on contracts/Collateral.sol
> +        state.updateLoan(loan);
Tracking refactoring items here: https://github.com/Synthetixio/issues/issues/264

---------

Looking to review this PR as is and get it merged before continuing on with the next phases of refactoring-related items.

Though I am still working on fixing the outstanding tests to get this PR in a state so that it can be merged.

2021-07-28 12:17 UTC, jacko125 commented on contracts/Collateral.sol
> +        require(!_exchanger().hasWaitingPeriodOrSettlementOwing(repayer, sUSD), "Waiting or owing");
Don't think we need to check this here (which checks for fee reclamation) as they are using the sUSD collateral that's already locked to repay the short.

2021-07-28 12:21 UTC, jacko125 commented on contracts/Collateral.sol
> +        (uint expectedAmount, , ) = _exchanger().getAmountsForExchange(payment, sUSD, loan.currency);
@barrasso  We should return the fee amount here as well and send the fee portion of to the `FeePool` contract / notify fee to the feePool of the fee amount collected.

Otherwise we can keep the fees within the shorts contract and allow it to be claimed by the feePool when closing the period like this example https://github.com/Synthetixio/synthetix/blob/master/contracts/EtherWrapper.sol#L178-L196

2021-07-28 12:25 UTC, jacko125 requested changes
Looks good, have some comments on the new `repayWithCollateral` function

2021-07-28 12:26 UTC, barrasso commented on contracts/Collateral.sol
> +        (uint expectedAmount, , ) = _exchanger().getAmountsForExchange(payment, sUSD, loan.currency);
@jacko125 I saw that `_payFees` is included in `_processPayment`, do I still need to do a separate fee payment?

2021-07-28 12:31 UTC, barrasso commented on contracts/Collateral.sol
> +        (uint expectedAmount, , ) = _exchanger().getAmountsForExchange(payment, sUSD, loan.currency);
So my thinking is that instead of `_processPayment`, I'd want to:

1) Subtract the amount received from the loan.amount; `loan.amount = loan.amount - expectedAmount`

2) Pay the fee from the "exchange"; `_payFees(fee, sUSD)`

2021-07-28 12:45 UTC, barrasso commented on contracts/Collateral.sol
> +        (uint expectedAmount, , ) = _exchanger().getAmountsForExchange(payment, sUSD, loan.currency);
Or keep `_processPayment` as is, and just add `_payFees(fee, sUSD)` underneath it.

2021-07-28 12:54 UTC, barrasso commented on contracts/Collateral.sol
> +        (uint expectedAmount, , ) = _exchanger().getAmountsForExchange(payment, sUSD, loan.currency);
This worked:

```
// 7. Process the payment and pay the fees.
loan.amount = loan.amount.sub(expectedAmount);
_payFees(fee, sUSD);
```

2021-07-28 12:56 UTC, barrasso commented on contracts/Collateral.sol
> +        require(!_exchanger().hasWaitingPeriodOrSettlementOwing(repayer, sUSD), "Waiting or owing");
Resolved

2021-07-28 12:56 UTC, barrasso commented on contracts/Collateral.sol
> +        (uint expectedAmount, , ) = _exchanger().getAmountsForExchange(payment, sUSD, loan.currency);
Resolved

2021-07-29 14:22 UTC, ajsantander approved these changes
👍 
Only minor comments

2021-07-29 14:22 UTC, ajsantander commented on test/contracts/CollateralShort.js
> +	const deployUtil = async ({ resolver }) => {
Could avoid code duplication here?

2021-07-29 14:22 UTC, ajsantander commented on test/contracts/setup.js
> +			deps: [], // TODO should this include CollateralState?
Please resolve TODO

2021-07-29 14:22 UTC, ajsantander commented on test/integration/behaviors/short.behavior.js
> +				// before('repay loan with collateral', async () => {
Pls avoid commented code. If it's not needed, delete it. If it is, leave a comment explaining why it is currently disabled.

2021-07-29 14:52 UTC, barrasso commented on contracts/Collateral.sol
> +    function _checkLoanPayableWithCollateral(
Agreed -- that confused me as well. I will mark this as something to cleanup during the second phase of the refactor.

2021-07-29 14:53 UTC, barrasso commented on contracts/Collateral.sol
> +        require(IERC20(address(_synth(synthsByKey[key]))).balanceOf(payer) >= amount, "Not enough synths");
Resolved

2021-07-29 14:57 UTC, barrasso commented on contracts/Collateral.sol
> +        require(payment > 0, "Must be above 0");
Made these errors a bit more descriptive again. Will revisit again if needed to reduce contract size

2021-07-29 15:11 UTC, barrasso commented on test/contracts/setup.js
> +			deps: [], // TODO should this include CollateralState?
This will be removed as we move to an internal state mapping pattern in collateral

2021-08-02 11:50 UTC, jacko125 commented on contracts/Collateral.sol
> +        if (fee > 0) {
I'd expect fee to always be > 0 if there's an the exchange fee being charged.

2021-08-02 15:52 UTC, barrasso commented on contracts/Collateral.sol
> +        if (fee > 0) {
Resolved

2021-08-02 18:24 UTC, justinjmoses requested changes

2021-08-02 18:24 UTC, justinjmoses commented on contracts/CollateralUtil.sol
> +    function _exchangeRates() internal view returns (IExchangeRates) {
You need to add this to the resolver addresses required array (you should override the function as in `Collateral.resolverAddressesRequired()`)

2021-08-02 18:24 UTC, justinjmoses commented on contracts/CollateralUtil.sol
> +        addressResolverProxy = IAddressResolver(_resolver);
You also don't need this - `MixinSystemSettings` is `MixinResolver` so you have `resolver` already (again see `Collateral.sol` above)

2021-08-02 18:24 UTC, justinjmoses commented on test/integration/behaviors/short.behavior.js
> +			describe('open a loan, deposit and withdraw collateral, draw, repay with collateral, and close the loan', () => {
did you add repay functionality in here?

2021-08-02 18:24 UTC, justinjmoses commented on test/contracts/CollateralErc20.js
> +			amountToLiquidate = await util.liquidationAmount(loan, minCratio, collateralKey);
Hmm - I do think it's worth following the convention and moving tests of the util out to it's own test file `CollateralUtil.js` and removing dupes here that we don't need.

2021-08-02 18:24 UTC, justinjmoses commented on test/contracts/CollateralManager.js
> +	const deployUtil = async ({ resolver }) => {
So the point of `setup.setupAllContracts()` was to make it easier to deploy a bunch of interrelated contracts in one go - the one in the beginning can be added to by including `CollateralUtil`, `CollateralShort`, etc.

2021-08-03 10:20 UTC, jacko125 approved these changes

2021-08-03 17:45 UTC, barrasso commented on contracts/CollateralUtil.sol
> +        addressResolverProxy = IAddressResolver(_resolver);
Resolved: https://github.com/Synthetixio/synthetix/pull/1427/commits/9492059b49f5cd8e48b4b35da0e46b077635ae37

2021-08-03 17:45 UTC, barrasso commented on test/integration/behaviors/short.behavior.js
> +			describe('open a loan, deposit and withdraw collateral, draw, repay with collateral, and close the loan', () => {
Coming in second PR

2021-08-03 17:45 UTC, barrasso commented on test/contracts/CollateralErc20.js
> +			amountToLiquidate = await util.liquidationAmount(loan, minCratio, collateralKey);
Resolved: https://github.com/Synthetixio/synthetix/pull/1427/commits/9492059b49f5cd8e48b4b35da0e46b077635ae37

2021-08-03 17:45 UTC, barrasso commented on test/contracts/CollateralManager.js
> +	const deployUtil = async ({ resolver }) => {
Resolved: https://github.com/Synthetixio/synthetix/pull/1427/commits/9492059b49f5cd8e48b4b35da0e46b077635ae37

2021-08-03 17:46 UTC, barrasso commented on test/contracts/CollateralShort.js
> +	const deployUtil = async ({ resolver }) => {
Resolved: https://github.com/Synthetixio/synthetix/pull/1427/commits/9492059b49f5cd8e48b4b35da0e46b077635ae37

2021-08-05 01:46 UTC, justinjmoses requested changes
It's looking really slick - just some missing coverage and a few final points

2021-08-05 01:46 UTC, justinjmoses commented on test/contracts/CollateralManager.js
> +				'CollateralUtil',
[np] if you aren't using these, you may be able to get away with not explicitly defining them here but no biggie (if you have them as a dep in setupAllContracts then it will deploy one for you - if it's a mock then it'll just deploy a `GenericMock`). You use `contracts: [...]` to explicitly state which contracts you want to be created so you can assign them to variables to use in your testing

2021-08-05 01:46 UTC, justinjmoses commented on test/contracts/CollateralShort.js
> +			assert.bnClose(loan.collateral, toUnit(900).toString(), toUnit(0.1).toString());
You can also assert the event was emitted no? `LoanRepaymentMade`

2021-08-05 01:46 UTC, justinjmoses commented on test/contracts/CollateralShort.js
> +			assert.equal(loan.amount, toUnit(0).toString());
can you also check `lastInteraction`, and that the fees were paid?

2021-08-05 01:46 UTC, justinjmoses commented on test/contracts/CollateralUtil.js
> +
Can you add `ensureOnlyExpectedMutativeFunctions` and make sure there's nothing external?

2021-08-05 01:46 UTC, justinjmoses commented on test/contracts/CollateralUtil.js
> +		managerState = await CollateralManagerState.new(owner, ZERO_ADDRESS, { from: deployerAccount });
Do you need this? Can't you grab it and the manager from the setupAllContracts above?

2021-08-05 01:46 UTC, justinjmoses commented on test/contracts/CollateralUtil.js
> +		proxy = await ProxyERC20.new(owner, {
Look at `setup.mockToken()` - this might be sufficient for your needs

2021-08-05 17:44 UTC, barrasso commented on test/contracts/CollateralUtil.js
> +		proxy = await ProxyERC20.new(owner, {
Resolved: https://github.com/Synthetixio/synthetix/pull/1427/commits/e8b2d40edfc1d925020fcd26e7090e6fae0b3623

2021-08-05 17:44 UTC, barrasso commented on test/contracts/CollateralUtil.js
> +		managerState = await CollateralManagerState.new(owner, ZERO_ADDRESS, { from: deployerAccount });
Resolved: https://github.com/Synthetixio/synthetix/pull/1427/commits/e8b2d40edfc1d925020fcd26e7090e6fae0b3623

2021-08-05 17:44 UTC, barrasso commented on test/contracts/CollateralUtil.js
> +
Resolved: https://github.com/Synthetixio/synthetix/pull/1427/commits/e8b2d40edfc1d925020fcd26e7090e6fae0b3623

2021-08-05 17:44 UTC, barrasso commented on test/contracts/CollateralShort.js
> +			assert.bnClose(loan.collateral, toUnit(900).toString(), toUnit(0.1).toString());
Resolved: https://github.com/Synthetixio/synthetix/pull/1427/commits/e8b2d40edfc1d925020fcd26e7090e6fae0b3623

2021-08-05 17:44 UTC, barrasso commented on test/contracts/CollateralManager.js
> +				'CollateralUtil',
Resolved: https://github.com/Synthetixio/synthetix/pull/1427/commits/e8b2d40edfc1d925020fcd26e7090e6fae0b3623

2021-08-05 20:59 UTC, barrasso commented on test/contracts/CollateralShort.js
> +			assert.equal(loan.amount, toUnit(0).toString());
Resolved: https://github.com/Synthetixio/synthetix/pull/1427/commits/f552559caa7c2420b25be9f5ca2ffe6c5adab119

2021-08-05 21:17 UTC, justinjmoses approved these changes
:100:

2021-08-05 21:31 UTC, merged