Add L2 governance bridge relay backdoor
Synthetixio/synthetix pull request #1438
Opened 2021-07-29 19:01 UTC by mjlescano

This PR adds the method `directRelay` to the `OwnerRelayOnOptimism` contract so we can directly execute any relayed method before an EOL date. This is just a temporary precaution in case we encounter a bug on the new governance bridge and loss ownership of all the relayed contracts.

⚠️  The temporary owner and EOL date can only be assigned when calling the constructor of `OwnerRelayOnOptimism` and cannot be modified after that.

2021-07-29 19:51 UTC, ajsantander commented on contracts/OwnerRelayOnOptimism.sol
> +        emit RelayFinalized(target, data);
Perhaps this logic could be contained in an internal `_relay(...)` function that both call?

2021-07-29 19:52 UTC, ajsantander commented on contracts/TempOwned.sol
> +        require(tempOwnerEOL >= now, "The EOL date for executing this function already reached");
It's a good idea to keep errors < 32 chars so that it fits in a 32 byte word, which is kinda like the Ethereum storage unit size.

2021-07-29 19:54 UTC, leomassazza approved these changes
LGTM

2021-08-02 18:24 UTC, ajsantander commented on contracts/OwnerRelayOnOptimism.sol
> +        emit RelayFinalized(target, data);
This event should probably not be here but in `finalizeRelay(...)`

2021-08-02 18:26 UTC, ajsantander commented on contracts/test-helpers/TestableTempOwned.sol
> +    function getMeaningOfLife() external view onlyTemporaryOwner returns (uint) {
It's kinda weird to use an accessibility modifier on a view only function, because anything is public at a low level in Ethereum.

2021-08-16 15:49 UTC, ajsantander commented on contracts/TempOwned.sol
> +    uint internal tempOwnerEOL;
This can be a uint64

2021-08-16 20:35 UTC, ajsantander approved these changes

2021-08-17 00:00 UTC, justinjmoses commented on contracts/TempOwned.sol
> +contract TempOwned {
Maybe call this `TemporaryOwnership`? It's more explicit.

2021-08-17 00:02 UTC, justinjmoses commented on contracts/OwnerRelayOnOptimism.sol
> +        uint _tempOwnerEOL
Maybe instead of passing the EOL time, we pass the number of seconds it should be mutatable for? Like `LimitedSetup.sol` does?

2021-08-17 00:02 UTC, justinjmoses commented on contracts/OwnerRelayOnOptimism.sol
> +        uint _tempOwnerEOL
That way we avoid things like this in the deploy script:

```javascript
const EOL = Math.floor(new Date().getTime() / 1000) + TEMP_OWNER_DEFAULT_EOL;
```

2021-08-17 00:05 UTC, ajsantander commented on contracts/TempOwned.sol
> +contract TempOwned {
IMO your suggestion is prettier, but Mati's choice is more consistent with `Owned`

2021-08-17 00:06 UTC, ajsantander commented on contracts/OwnerRelayOnOptimism.sol
> +        uint _tempOwnerEOL
What would be the advantage of this vs specifying a date in the future that will no longer allow ownership, as it is currently implemented?

2021-08-17 16:02 UTC, ajsantander commented on contracts/TempOwned.sol
> +contract TempOwned {
Ok you win. Renaming to TemporarilyOwned!

2021-08-17 16:02 UTC, ajsantander commented on contracts/OwnerRelayOnOptimism.sol
> +        uint _tempOwnerEOL
Yep, it's less prone to mistakes. Changing.

2021-08-17 16:07 UTC, i-stam approved these changes
LGTM: left a minor comment (edit: let's use `block.timestamp` since `now` is deprecated in newer versions of solidity)

2021-08-17 16:07 UTC, i-stam commented on contracts/OwnerRelayOnOptimism.sol
> +        uint _tempOwnerEOL
I guess the EOL would be set in the constructor (`block.timestamp.add(duration)`) instead of passing the EOL. The basic sanity check is in `TempOwned() `constructor so it should be fine. I am wondering if we can make it more resilient to error.

2021-08-17 16:16 UTC, justinjmoses reviewed
A few items left - nothing major

2021-08-17 16:16 UTC, justinjmoses commented on contracts/TemporarilyOwned.sol
> +    uint public duration;
Can we use the same pattern that LimitedSetup does and store the timestamp but calculate it on construction?  https://github.com/Synthetixio/synthetix/blob/master/contracts/LimitedSetup.sol#L12  Then we simplify L22 below.

2021-08-17 16:16 UTC, justinjmoses commented on index.js
> +	TEMP_OWNER_DEFAULT_DURATION: 60 * 60 * 24 * 30 * 2, // 2 months
[np] technically there is no official "month" duration, so it's really just 60 days.

2021-08-17 16:16 UTC, justinjmoses commented on contracts/TemporarilyOwned.sol
> +    address public tempOwner;
[np] shouldn't we call this `temporaryOwner` to be consistent?

2021-08-17 16:16 UTC, justinjmoses commented on test/contracts/TemporarilyOwned.js
> +				await assert.revert(
It seems to have been missed from last round - I recommend using `onlyGivenAddressCanInvoke` rather than just trying a random account (it cycles through all given accounts)

2021-08-17 16:16 UTC, justinjmoses commented on test/integration/dual/relay.integration.js
> +		let originalMinimumStakeTime;
These dual tests are 🔥🔥🔥

2021-08-17 16:16 UTC, justinjmoses commented on test/integration/dual/relay.integration.js
> +		describe('when changing an L2 system setting with directRelay', () => {
Technically this is an L2 isolated test rather than dual, but I get it's easier to just connect it up here as we have the structure already.

2021-08-17 16:47 UTC, ajsantander commented on test/contracts/TemporarilyOwned.js
> +				await assert.revert(
Unfortunately, this function is web3 only, and this test is using ethers. Will other other manual checks tho.

2021-08-17 17:05 UTC, i-stam requested changes

2021-08-17 17:05 UTC, i-stam commented on contracts/TemporarilyOwned.sol
> +        initialTimestamp = now;
I think that a more elegant way would be this: `expiration = block.timestamp.add(duration);`

2021-08-17 17:05 UTC, i-stam commented on contracts/TemporarilyOwned.sol
> +        initialTimestamp = now;
no need for extra variables

2021-08-17 17:05 UTC, i-stam commented on contracts/TemporarilyOwned.sol
> +        require(now - initialTimestamp < duration, "Ownership expired");
and here the check would be simple: `block.timestamp < expiration`

2021-08-17 17:10 UTC, ajsantander commented on test/integration/dual/relay.integration.js
> +		describe('when changing an L2 system setting with directRelay', () => {
Yeah, agreed! Let's keep it here for now because it is easier to correlate with the rest of the tests.

2021-08-17 17:10 UTC, ajsantander commented on contracts/TemporarilyOwned.sol
> +        initialTimestamp = now;
Yep! Implemented. Thank you.

2021-08-17 17:11 UTC, ajsantander commented on contracts/TemporarilyOwned.sol
> +        require(now - initialTimestamp < duration, "Ownership expired");
Implemented!

2021-08-17 17:18 UTC, i-stam approved these changes

2021-08-17 17:43 UTC, merged