Futures order slippage
Synthetixio/synthetix pull request #1446
Opened 2021-08-05 07:02 UTC by liamzebedee

2021-08-09 08:46 UTC, zyzek requested changes

2021-08-09 08:46 UTC, zyzek commented on contracts/FuturesMarket.sol
> +        uint[2] memory priceBounds,
Why's this in an array? Is this a stack too deep thing?

2021-08-09 08:46 UTC, zyzek commented on test/contracts/FuturesMarket.js
> +	describe.only('Confirming orders', () => {
And there I thought the precommit constraints were supposed to catch .onlys

2021-08-09 08:46 UTC, zyzek commented on test/contracts/FuturesMarket.js
> +			const minPrice = startPrice.mul(toUnit(1).add(maxSlippage));
It looks to me like `minPrice` is greater than `maxPrice`, and under these conditions the order can never confirm, so much of the logic below isn't really testing anything.

Interestingly I guess if you submit an order with `currentPrice < minPrice`, the order won't confirm until the price rises above the specified point, which I guess means we have effectively created a limit order. Not sure whether we want to check at order submission time that the current price is within the bands or not.

2021-08-09 08:46 UTC, zyzek commented on test/contracts/FuturesMarketData.js
> +	const defaultPriceBounds = [ethers.constants.Zero, ethers.constants.MaxUint256];
We should be testing in the position details test below that these are present in the returned order struct and that they have accurate values.

2021-08-10 00:01 UTC, liamzebedee commented on contracts/FuturesMarket.sol
> +        uint[2] memory priceBounds,
Yepp.

2021-08-10 04:10 UTC, liamzebedee commented on test/contracts/FuturesMarket.js
> +			const minPrice = startPrice.mul(toUnit(1).add(maxSlippage));
@zyzek that's interesting. I guess we have limit orders now. 

Sorry, I messed up - fixing these now.

2021-08-10 04:14 UTC, liamzebedee commented on test/contracts/FuturesMarketData.js
> +	const defaultPriceBounds = [ethers.constants.Zero, ethers.constants.MaxUint256];
I've tested this here in order submission - is that sufficient? These params are only part of the order, not the position?

https://github.com/Synthetixio/synthetix/pull/1446/files#diff-ea3e2c01da4d3ffe85d68d81159997ff1b2a8ca320fdddf8cf5c2ff3ca165d98R1092

2021-08-10 04:36 UTC, zyzek commented on test/contracts/FuturesMarketData.js
> +	const defaultPriceBounds = [ethers.constants.Zero, ethers.constants.MaxUint256];
The test is to ensure that the data contract is surfacing all data that it should be surfacing.

2021-08-11 00:16 UTC, jacko125 commented
@liamzebedee 
Looks good the contract changes, 

So what happens is the order can't be confirmed when the slippage params are exceeding the max / min? But the order would still be valid and can be confirmed once the price moves into that range?

2021-08-11 03:58 UTC, jacko125 approved these changes

2021-08-11 04:15 UTC, liamzebedee commented
> So what happens is the order can't be confirmed when the slippage params are exceeding the max / min? But the order would still be valid and can be confirmed once the price moves into that range?

Exactly. Maybe at a later point we can choose to add order expiry. More higher priority items for now I guess.

2021-08-11 04:26 UTC, liamzebedee commented on test/contracts/FuturesMarketData.js
> +	const defaultPriceBounds = [ethers.constants.Zero, ethers.constants.MaxUint256];
Oh, I was looking at the wrong test. Yeah added this now.

2021-08-12 03:43 UTC, merged