Position ID, PositionOpened, PositionClosed added
Synthetixio/synthetix pull request #1461
Opened 2021-08-16 09:20 UTC by clementbalestrat

2021-08-16 09:25 UTC, clementbalestrat commented on contracts/FuturesMarket.sol
> +            emitPositionOpened(position.id, account);
@zyzek I'm wondering if it's ok to emit an event this early in the code?

2021-08-16 09:56 UTC, zyzek requested changes

2021-08-16 09:56 UTC, zyzek commented on contracts/FuturesMarket.sol
> +    // This increments for each position; zero reflects an order that does not exist.
`zero reflects an order` -> `zero reflects a position`

2021-08-16 09:56 UTC, zyzek commented on contracts/FuturesMarket.sol
>          _applyDebtCorrection(
In all these `_applyDebtCorrection` calls, it should be fine to construct these position objects the id argument equal to zero, as the ids aren't used. Would save a little gas in state queries.

2021-08-16 09:56 UTC, zyzek commented on contracts/FuturesMarket.sol
> +            emitPositionOpened(position.id, account);
It should be fine, but let's put it below in the `else` clause of the conditional where you're doing `emitPositionClosed`. That way we guarantee both that `newSize != 0` and `oldSize == 0`, and the opening and closing events are right next to one another.

While we're here, I noticed there's nothing stopping a user closing an already-closed position. I think we should probably revert inside `_submitOrder` if `leverage == position.size == 0`. Right now if a zero leverage order is submitted and the position size is already zero, then on confirmation it'll emit both a position opened and a position closed event. Probably undesirable.

2021-08-16 09:56 UTC, zyzek commented on contracts/FuturesMarket.sol
>              emitPositionModified(account, margin, 0, 0, 0);
Question: shouldn't we also put the position id inside `PositionModified`? We could also detect if a position is it's opening or closing by looking at how the position size changes.

2021-08-16 10:18 UTC, clementbalestrat commented on contracts/FuturesMarket.sol
>              emitPositionModified(account, margin, 0, 0, 0);
Yeah I just realised that. Adding it now

2021-08-16 10:27 UTC, clementbalestrat commented on contracts/FuturesMarket.sol
> +            emitPositionModified(position.id, account, margin, 0, 0, 0);
@zyzek do we even need to emitPositionModified when we know it's to close a position?

2021-08-16 10:28 UTC, clementbalestrat commented on contracts/FuturesMarket.sol
> +        emitPositionModified(positionId, account, 0, 0, 0, 0);
Same question here

2021-08-16 10:37 UTC, zyzek requested changes

2021-08-16 10:37 UTC, zyzek commented on contracts/FuturesMarket.sol
> +        if (leverage == position.size && position.size == 0) {
This should use the `revertIfError` structure so that we're not compiling these strings into the runtime bytecode and the reverts all follow the same pattern.

2021-08-18 02:45 UTC, zyzek approved these changes

2021-08-18 03:40 UTC, liamzebedee approved these changes
Looks really good Clem, approved

2021-08-18 04:11 UTC, jacko125 approved these changes
Clem, lgtm the new PositionId for each FuturesMarket

2021-08-18 04:23 UTC, merged