Futures orders confirm at spot
Synthetixio/synthetix pull request #1477
Opened 2021-08-23 00:02 UTC by zyzek

2021-08-23 03:39 UTC, clementbalestrat approved these changes

2021-08-23 04:00 UTC, jacko125 commented on contracts/FuturesMarket.sol
> +        _revertIfError(_maxLeverage(baseAsset) < _abs(desiredLeverage), Status.MaxLeverageExceeded);
@zyzek Thoughts on capping the `newSize` here to cap at the max leverage or giving some buffer to reduce the amount of rejected tx's especially if close to the max leverage a position.

2021-08-23 04:04 UTC, jacko125 commented on contracts/FuturesMarket.sol
> +        _revertIfError(size == 0, Status.NoPositionOpen);
Could check whether the position is open earlier?

2021-08-23 04:09 UTC, zyzek commented on contracts/FuturesMarket.sol
> +        _revertIfError(size == 0, Status.NoPositionOpen);
Good point, moving it up.

2021-08-23 04:24 UTC, zyzek commented on contracts/FuturesMarket.sol
> +        _revertIfError(_maxLeverage(baseAsset) < _abs(desiredLeverage), Status.MaxLeverageExceeded);
Good point, let's allow an extra 1% leverage above the maximum allowable.

2021-08-23 05:47 UTC, liamzebedee requested changes
Some minor questions - what you've done here is solid 👍

2021-08-23 05:47 UTC, liamzebedee commented on contracts/FuturesMarket.sol
> +    function _modifyPosition(
Hey, did you intend to remove the slippage protections altogether? Even though we fulfill at spot price, the user can still lose money if the price changes between tx submission and the tx being mined - eg. due to congestion, their tx is mined after a price update comes through. I don't think we want this, even if its low probability on Optimism.

2021-08-23 05:47 UTC, liamzebedee commented on contracts/FuturesMarket.sol
> +        uint margin,
@zyzek @clementbalestrat I noticed we removed `leverage` from the event - do we want to have to calculate this in the dapp and subgraphs for every position modification event? My intuition is that it's quicker to access this from the event. I'm thinking of a view like "position history" in the dapp, where we display the leverage for each modification.

2021-08-23 05:47 UTC, liamzebedee commented on contracts/FuturesMarket.sol
> +        int sizeDelta,
Just thought of this, perhaps specifying the delta is more complex than the absolute size - now, in order to modify the position, we must check for pending modifications to the position in order to compute the correct delta for a given size. It introduces some additional state the dapp needs to grab. Did we come up with any benefits with using a delta? Do you think the absolute value is less complex?

2021-08-23 05:57 UTC, zyzek commented on contracts/FuturesMarket.sol
> +        uint margin,
On the dapp design stuff, It's not clear to me whether it's position size or leverage we really want to display here. I'll defer to @clementbalestrat on this one. 

On the technicals of actually including an explicit `leverage` field, I don't think that's necessary, as it's retrievable by doing `size * price / margin`.

2021-08-23 06:04 UTC, zyzek commented on contracts/FuturesMarket.sol
> +        int sizeDelta,
I think the pending modifications question is probably solved on the front-end by disallowing any order to be submitted until any pending position modification transactions have confirmed.

I think extra complexity just depends on what the front end is actually doing. If we want to change the entire position to a specific size, then yeah, the current pattern would require calculating `desiredSize - currentSize`. On the other hand, if we change the interface to take an absolute value and someone wants to increase by `x` units, then they'll need to pass in `currentSize + x`. The internals of `_modifyPosition` do not really change mcuh either way.
The same question kind of applies to the `transferMargin` function, as presumably we want the interaction patterns to be the same?

I'm not particularly fussed either way, but perhaps @clementbalestrat has a front-end use case that will decide which one is best.

2021-08-23 06:07 UTC, zyzek commented on contracts/FuturesMarket.sol
> +    function _modifyPosition(
Hm, yeah I had assumed that slippage protection would be unnecessary with no confirmation delay, but I suppose your scenario is possible. I'll add a `_modifyPositionWithPriceBounds` function back in.

2021-08-25 02:09 UTC, jacko125 commented on contracts/FuturesMarket.sol
> +        int sizeDelta,
I feel that the delta here makes more sense where you would input the difference required, ie selling some units or increasing the units of the asset (buying) in the trade.

2021-08-25 03:45 UTC, liamzebedee approved these changes

2021-08-25 03:46 UTC, jacko125 approved these changes

2021-08-25 04:19 UTC, merged