emit sizeDelta with PositionModified event
Synthetixio/synthetix pull request #1485
Opened 2021-08-30 06:53 UTC by liamzebedee

2021-08-30 06:58 UTC, zyzek requested changes

2021-08-30 06:58 UTC, zyzek commented on contracts/FuturesMarket.sol
> +            emitPositionModified(newPosition.id, sender, newPosition.margin, 0, 0, 0, 0, fee);
This still needs the `sizeDelta`, if the position went from nonzero to zero size, then it necessarily means the delta was nonzero.

2021-08-30 07:00 UTC, zyzek requested changes

2021-08-30 07:00 UTC, zyzek commented on contracts/FuturesMarket.sol
> +        emitPositionModified(positionId, account, 0, 0, 0, 0, 0, 0);
Should the involuntary liquidation of a position include a sizeDelta that is the whole position size or not? I think probably it should, but maybe @clementbalestrat has some ideas on this too.

2021-08-31 01:33 UTC, zyzek approved these changes

2021-08-31 01:43 UTC, jacko125 approved these changes

2021-08-31 01:56 UTC, merged