ci: lavamoat and patch-package integration
Synthetixio/synthetix pull request #1517
Opened 2021-09-21 12:49 UTC by drptbl

2021-09-21 19:29 UTC, justinjmoses commented on README.md
> +Run `npm run setup` script after installing dependencies with `npm install`. It will trigger postinstall scripts for dependencies which are whitelited inside allowlist and apply our custom patches fo
QU: would a `postinstall` be the best way to do `setup`? I'd rather this be automated were possible.

2021-09-21 19:42 UTC, drptbl commented on README.md
> +Run `npm run setup` script after installing dependencies with `npm install`. It will trigger postinstall scripts for dependencies which are whitelited inside allowlist and apply our custom patches fo
It's not possible because all `postinstall` scripts (from dependencies and this repository) are disabled inside `.npmrc` file with `ignore-scripts=true` flag. This is done this way to make sure that no one runs a `postinstall` script from a dependency which is not in allowlist (it forces users to use `allow-scripts` command). Sadly, `npm` doesn't offer a way to disable `postinstall` scripts selectively for dependencies.

2021-09-21 19:47 UTC, drptbl commented on README.md
> +Run `npm run setup` script after installing dependencies with `npm install`. It will trigger postinstall scripts for dependencies which are whitelited inside allowlist and apply our custom patches fo
@justinjmoses I have updated the description in the readme. Actually, you don't have to run `npm install` before `npm run setup` because it's already included in it. All you have to do to setup the repo (and install dependencies) is to run `npm run setup`.

2021-09-22 15:47 UTC, drptbl commented on README.md
> +Run `npm run setup` script after installing dependencies with `npm install`. It will trigger postinstall scripts for dependencies which are whitelited inside allowlist and apply our custom patches fo
@justinjmoses As an alternative solution, we could switch to use `yarn@2` instead of `npm`.

`yarn` offers allowlist feature for `postinstall` scripts out-of-the-box:
https://next.yarnpkg.com/configuration/manifest#dependenciesMeta.built

Thanks to that, we could resign to use `@lavamoat/allow-scripts` with conjunction of `npm` and use pure `yarn@2` instead.

I'm not having any other ideas currently. My currently proposed solution is also what other repositories use, for ex. `metamask-extension`:
https://github.com/MetaMask/metamask-extension/blob/develop/package.json#L10

2021-09-23 08:31 UTC, justinjmoses commented on patches/solidifier+2.1.0.patch
> +@@ -1,14 +0,0 @@
Why doesn't this patch include everything in the fork? Or did you just remove the version info from the `package.json`?

2021-09-23 08:35 UTC, justinjmoses commented on README.md
> +Run `npm run setup` script after installing dependencies with `npm install`. It will trigger postinstall scripts for dependencies which are whitelited inside allowlist and apply our custom patches fo
Fair enough, but I don't really want to bring in yarn just for this. OK, since it's (running setup) super unlikely to be critical unless you are deploying I can get behind it. 

I am going to talk with @thekevinbrown about getting this fork into the parent so we don't even need `patch-package`

2021-09-23 08:35 UTC, drptbl commented on patches/solidifier+2.1.0.patch
> +@@ -1,14 +0,0 @@
Everything is included except version bump from `package.json`. I don't think that it would well taking in to an account that solidifer is referenced from `synthetix` repo as `solidifier@2.1.0`.

2021-09-23 14:52 UTC, justinjmoses requested changes
HOLD. Requesting an update to solidifier from @thekevinbrown

2021-09-29 22:47 UTC, justinjmoses approved these changes

2021-10-03 13:37 UTC, merged