Feat(DynamicFee): SIP-184 dynamic fees
Synthetixio/synthetix pull request #1563
Opened 2021-10-13 12:49 UTC by leckylao

- [x] Params.json (L1)
- [x] first implementation
- [x] Performance - have `lastDynamicFee` and `lastRoundSeen` for caching
- [x] Merge develop once https://github.com/Synthetixio/synthetix/pull/1127 merged
- [x] Add more test scenarios. 
- [x] Unit test
- [x] Add Exchanger test with/without dynamic fee
- [x] Add Exchanger test sBTC -> sUSD and sUSD -> sBTC with sBTC dynamic fee. sETH -> sBTC with both currency dynamic fee
- [x] integration test
- [ ] Audit
- [ ] Testnet deploy

2021-11-01 03:50 UTC, artdgn commented on contracts/DynamicFee.sol
> +            uint priceWeight = getPriceWeight(i, weightDecay);
> Both ways complexity should be the same that both need to calculate the decay 10 times right?

Not exactly. The previous way there is added complexity due to `.pow()` being calculated in every iteration inside the `getPriceWeight()`. That calculation runs it's own loop (doing multiplications). So that adds some complexity which can be removed. It's logarithmic, but still no need to run those extra internal loops.

> As DynamicFee is a library so looks like best place to store lastDynamicFee and lastRoundSeen would be on Exchanger the place that it get call. 

I think something along these lines, and probably the library interface would change a little. It would be something like `updateDynamicFee(uint lastDynamicFee, uint lastRoundSeen, address exchangeRates) returns (uint dynamicFee, uint lastRound)` or something. And inside there it would query `ExchangeRates` for the last round, and get the price data or something.

@leckylao

2021-11-04 12:35 UTC, jacko125 commented on contracts/DynamicFee.sol
> +        int priceDifferential = abs - int(threshold);
@leckylao So here we subtract the `threshold` instead of only reporting it if it is above the threshold?

2021-11-04 12:52 UTC, jacko125 commented on contracts/DynamicFee.sol
> +    ) public pure returns (uint) {
shouldn't this be external ?

2021-11-04 12:57 UTC, jacko125 commented on contracts/DynamicFee.sol
> +        uint[] memory prices,
Given that we need the last 10 prices from the oracle, could we not store the last 10 rounds in our own ExchangeRates contract for example (as an improvement over making 10x external calls to the oracle).

Then only fetch the latest prices if they are not stored in the ExchangeRates and persist them to storage as well? This might be more expensive gas wise given we are writing to storage. 

Also has CL looked into improving their interface to allow retrieving a list of roundID / prices with one call?

2021-11-04 13:00 UTC, jacko125 commented on contracts/DynamicFee.sol
> +            dynamicFee = (dynamicFee.multiplyDecimal(roundDecay)).add(priceDifferential);
@leckylao Might be worth having you run through this PR and the logic here for calculating the `dynamicFee` to make sure we're on the right track. 

Would you apply the `roundDecay` to the priceDifferential by `priceDifferential.multiplyDecimal(roundDecay)` if you want to decay the priceDifferential based on the number of rounds it was before?

2021-11-05 01:27 UTC, leckylao commented on contracts/DynamicFee.sol
> +    ) public pure returns (uint) {
It's also being used in `getDynamicFee`  https://github.com/Synthetixio/synthetix/pull/1563/files/a999fe36ae951fb9f55124dd057bd0f3a68402d3#diff-6019708811a67d9f46fdf302d9455ff6d5f2016232a8de6753a33ef1dc218405R56

2021-11-05 01:27 UTC, leckylao commented on contracts/DynamicFee.sol
> +        int priceDifferential = abs - int(threshold);
I break it down into two lines, essentially it's `return abs - int(threshold) > 0 ? uint(abs - int(threshold)) : uint(0);`

2021-11-05 01:27 UTC, leckylao commented on contracts/DynamicFee.sol
> +            dynamicFee = (dynamicFee.multiplyDecimal(roundDecay)).add(priceDifferential);
Yes, I have that on the first place. @artdgn points out this way could store the `lastDynamicFee` and `lastRoundSeen` for improvement. And I've checked test case passed in both ways. Will implement the improvement once I have fixed all tests
https://github.com/Synthetixio/synthetix/pull/1563/commits/8aa8c5e5e0ff25504f9487a2fc0dbe5f9d47c1f9#file-contracts-dynamicfee-sol-L58

2021-11-05 01:27 UTC, leckylao commented on contracts/DynamicFee.sol
> +        uint[] memory prices,
Yes, I am thinking to have a separate PR to try reading the feed round data from cache first using `_rate` which is already there. That way the whole system can also benefits from it as when frequent exchange it would be just reading from cache. 
https://github.com/Synthetixio/synthetix/blob/develop/contracts/ExchangeRates.sol#L446

Not necessary need to be persistent in storage as it's just cacheing, if cacheing not found would just go fetch again as it's doing currently.

Here's the last update from CL. Still ongoing conversations
https://discord.com/channels/413890591840272394/809168416350928946/896036115570655323

2021-11-05 01:39 UTC, leckylao commented on contracts/DynamicFee.sol
> +            dynamicFee = (dynamicFee.multiplyDecimal(roundDecay)).add(priceDifferential);
> I'm not sure about the calculation in this revision. It seems to apply the decay exponentially more than needed because it multiplies by `roundDecay` instead of just by `weightDecay`. This code would result for e.g. 4 iterations in this: Iteration 1: `dynamicFee = 0 * weightDecay ^ 9 + priceDiff9 = priceDiff9` Iteration 2: `dynamicFee = priceDiff9 * weightDecay ^ 8 + priceDiff8` Iteration 3: `dynamicFee = (priceDiff9 * weightDecay ^ 8 + priceDiff8) * weightDecay ^ 7 + priceDiff7 = priceDiff9 * weightDecay ^ 15 + priceDiff8 * weightDecay ^ 7 + priceDiff7` Iteration 4: `dynamicFee = priceDiff9 * weightDecay ^ 21 + priceDiff8 * weightDecay ^ 13 + priceDiff7 * weightDecay ^ 6 + priceDiff6` ... Which is probably incorrect.
> 
> Wouldn't the code in [#1563 (comment)](https://github.com/Synthetixio/synthetix/pull/1563#discussion_r736116702) be more correct and result in this ?: Iteration 1: `dynamicFee = 0 * weightDecay + priceDiff9 = priceDiff9` Iteration 2: `dynamicFee = priceDiff9 * weightDecay + priceDiff8` Iteration 3: `dynamicFee = (priceDiff9 * weightDecay + priceDiff8) * weightDecay + priceDiff7 = priceDiff9 * weightDecay ^ 2 + priceDiff8 * weightDecay + priceDiff7` Iteration 4: `dynamicFee = priceDiff9 * weightDecay ^ 3 + priceDiff8 * weightDecay ^ 2 + priceDiff7 * weightDecay + priceDiff6` Which is what we need?

Nah, it's round decay then it would match Afif's data. Can run you through on the Monday brief session.

2021-11-05 01:43 UTC, leckylao commented on contracts/DynamicFee.sol
> +            uint priceWeight = getPriceWeight(i, weightDecay);
> > Both ways complexity should be the same that both need to calculate the decay 10 times right?
> 
> Not exactly. The previous way there is added complexity due to `.pow()` being calculated in every iteration inside the `getPriceWeight()`. That calculation runs it's own loop (doing multiplications). So that adds some complexity which can be removed. It's logarithmic, but still no need to run those extra internal loops.

Can run through the roundDecay with Afif on the Monday brief session. 

> > As DynamicFee is a library so looks like best place to store lastDynamicFee and lastRoundSeen would be on Exchanger the place that it get call.
> 
> I think something along these lines, and probably the library interface would change a little. It would be something like `updateDynamicFee(uint lastDynamicFee, uint lastRoundSeen, address exchangeRates) returns (uint dynamicFee, uint lastRound)` or something. And inside there it would query `ExchangeRates` for the last round, and get the price data or something.
> 
> @leckylao

Then the library would have dependancy on the ExchangeRates and need to get it from AddressResolver which is another dependancy. The idea of using it as library is less dependancy and can be import anywhere else to use it.

2021-11-05 05:40 UTC, artdgn commented on contracts/DynamicFee.sol
> +            uint priceWeight = getPriceWeight(i, weightDecay);
> Then the library would have dependancy on the ExchangeRates and need to get it from AddressResolver which is another dependancy.

That's not what I meant. You pass in the address in `updateDynamicFee(uint lastDynamicFee, uint lastRoundSeen, address exchangeRates)` and then there is no dependency on resolver, just need to import the interface.

2021-11-23 07:40 UTC, leckylao commented
Gas cost for Synthetix.exchange:

Before implementation is 500666 Gwei:
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/148800/142986153-b07707c0-1ad1-409f-8e68-d91ac574eac1.png">

After implementation is 740175 Gwei:
![image](https://user-images.githubusercontent.com/148800/142986290-ee33a1dc-d92d-4dc7-af9a-88373bb8f27d.png)

After optimisation is 5845863 Gwei:
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/148800/142985965-d7a7c52a-3c51-42ae-9e51-fbb262905c2b.png">

2021-11-24 02:25 UTC, artdgn requested changes
Good stuff, but I think there some gaps (but maybe I'm missing something):
1. More testing for the dynamic fee calculation - I've pointed out below some test scenarios that I think are important.
2. Testing of dynamic fee being correctly used and persisted in actual `exchange()` functionality (it seems disabled in exchange tests). And more test cases to cover the pairs logic and the caching logic.
3. The refactor for gas optimisation in ExchangeRates for latest rate seems to possibly increase gas usage.
3. The refactor for gas optimisations in exchange() seems to not be needed - doesn't look to be reducing gas.
4. The gas usage measerement is probably too optimistic because in most `exchange()` tests dynamic fee is disabled.
5. There seems to be a an issue with dynamic fee and direction of trade (only destination is used).
6. There seems to be an issue with currentRoundId state in Rates that can be set to arbitrary user values and the incrementing looks prone to get out of sync with oracle.
7. Wasn't sure about reentrancy risks due to calling only internal contracts and not arbitrary external contracts.
8. The actual calculation of the dynimic fee still looks weird and not according to the spec. I think the conclusion of the discussion is that more test cases, and more clarity in the test cases as to what they're testing are needed.


There more details at specific line numbers in the review.

2021-11-24 02:25 UTC, artdgn commented on test/contracts/BaseSynthetix.js
> +			await exchangeRates.updateRates([sEUR], [toUnit('1')], timestamp1, { from: oracle });
why were these changes needed? doesn't it make testing harder by not being able to tell if exchange rate is used correctly or not (when exchange rate is 1)

2021-11-24 02:25 UTC, artdgn commented on test/contracts/TestableDynamicFee.js
> +	it('Can get dynamic fee round 15-24', async () => {
can you add some details on what part of the dynamic fee calculation this range is testing? can we upload the reference table to github gist, or as tests data so that it can be used for future test updates?

2021-11-24 02:25 UTC, artdgn commented on test/contracts/TestableDynamicFee.js
> +	it('Can get dynamic fee round 34-43', async () => {
same thing - as a reader / maintainer I have no idea what this is testing or what to the values should be (both for setup and the expected result)

2021-11-24 02:25 UTC, artdgn commented on test/contracts/TestableDynamicFee.js
> +	});
I think it would be good to have ranges and setups that test these parts of the dynamic fee calculation:
1. When price diffs are all below threshold.
2. When price diffs are all above threshold.
3. When some price diffs are above, and some below threshold.
4. When there was a caching gap longer than 10 rounds.
5. When there was a caching gap shorter than 10 rounds.
6. That with caching and without caching (e.g. gap) - there values are the same.
7. That if there was no caching gap longer than 10 rounds, dynamic fee is persisted correctly (doesn't start from 0, but starts from previous values from before 10 rounds)
8. Reverse trades BTC->USD have same dynamic fee as USD->BTC
9. ETH->BTC, BTC->ETH trades have correct dynamic fee (max of either side?)

2021-11-24 02:25 UTC, artdgn commented on test/contracts/Exchanger.spec.js
> +					await systemSettings.setExchangeDynamicFeeRounds('0', { from: owner });
It looks like dynamic fee in actual exchanges is never tested - always disabled. If so, we should add test cases that test that dynamic fee is correctly used and deducted during exchanges. That it's correctly in test cases that probe:
1. Different kinds of directions - BTC->USD, USD->BTC, ETH->BTC, BTC->ETH - otherwise we're not covering the logic that relates to sUSD.
2. That dynamic fee is persisted correctly after exchanges and is used in next exchange.
3. That caching works correctly with gaps and without gaps and results in same results.

2021-11-28 09:54 UTC, leckylao commented on test/contracts/TestableDynamicFee.js
> +	});
Thanks for the test cases suggestion. After I added more cases turns out that current formula is not correct so I have to rollback to the previous formula. Which is good as now it align with the SIP. 

And I have to remove the `lastExchangeDynamicFeeRate` cache as it doesn't really work. Different dynamic fee using different rounds and they have different `roundDecay`. Additionally the the last dynamic fee contains the last 10 rounds. When using for the new calculations it will need to subtract the additional rounds. So not worth it.

2021-11-30 05:11 UTC, leckylao commented
> Gas cost for Synthetix.exchange:
> 
> Before implementation is 500666 Gwei: <img alt="image" width="1401" src="https://user-images.githubusercontent.com/148800/142986153-b07707c0-1ad1-409f-8e68-d91ac574eac1.png">
> 
> After implementation is 740175 Gwei: ![image](https://user-images.githubusercontent.com/148800/142986290-ee33a1dc-d92d-4dc7-af9a-88373bb8f27d.png)
> 
> After optimisation is 572653 Gwei: <img alt="image" width="1408" src="https://user-images.githubusercontent.com/148800/142986466-855dce0a-5d14-4d63-938b-bf5f01d95fc9.png">

Gas cost after adding dynamic fee for `sourceCurrencyKey`

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/148800/143989295-49788a30-e072-47cb-b0a8-b8fb3059463f.png">

2021-12-07 00:54 UTC, barrasso requested changes

2021-12-09 00:39 UTC, leckylao commented on contracts/ExchangeRates.sol
> +    function _getRateAndUpdatedTimeAtRound(bytes32 currencyKey, uint roundId) internal view returns (uint rate, uint time) {
The propose here is to make it consistent with the function `_getRateAndUpdatedTime` as the code are pretty much the same and with the `AtRound` to indicate accept `roundId`.

2021-12-09 00:39 UTC, leckylao commented on contracts/ExchangeRatesWithDexPricing.sol
> -            (uint rate, uint time) = _getRateAndTimestampAtRound(currencyKey, roundId);
Right, good point. Will rollback so don't need to deploy this contract

2021-12-09 00:39 UTC, leckylao commented on contracts/Exchanger.sol
>          uint sourceAmountAfterSettlement = _settleAndCalcSourceAmountRemaining(sourceAmount, from, sourceCurrencyKey);
So that it can has less cost to suspend the system? As circuit breaker only need to check the rate.

2021-12-09 00:39 UTC, leckylao commented on publish/deployed/mainnet/params.json
> +		"value": "1"
Yes, `EXCHANGE_DYNAMIC_FEE_ROUNDS` takes minimum value 2 to be effective, setting it to 1 on Mainnet in order to disable it on L1 and not being override back to default 10 after new `SystemSettings` deployment.

2021-12-09 00:39 UTC, leckylao commented on test/contracts/CollateralShort.js
> +			await exchangeRates.updateRates([sETH], ['100'].map(toUnit), timestamp, {
Dynamic Fee applies when minimal 2 rates available.

2021-12-09 00:39 UTC, leckylao commented on test/contracts/DebtCache.js
> +				// Disable Dynamic fee so that we can neglect it.
Through this way so that we know what impact it could brings in and only disable if it's not relevant and in intention.

2021-12-09 00:39 UTC, leckylao commented on test/contracts/Exchanger.spec.js
> +								bnCloseVariance,
Good point, should disable dynamic fee instead to test for `ExchangeEntryAppended` match.

2021-12-09 00:39 UTC, leckylao commented on test/contracts/TestableDynamicFee.js
> +	it('Can get dynamic fee from dynamic-fee-calc.csv round 13-22, all below threshold', async () => {
Made sense, changing it to "according to SIP feasibility spreadsheet"

2021-12-09 00:48 UTC, leckylao commented on test/contracts/Exchanger.spec.js
> +								bnCloseVariance,
Oh, actually it's not caused by dynamic fee. It's actually because introducing of the cache rate so that the actual exchange rate might not be the same from the view function `getAmountsForExchange`. As it's not enquiring the same round data. `exchanger.getAmountsForExchange` is getting the current round rate but ExchangeEntry rate is the historical rate.

2021-12-09 06:59 UTC, artdgn requested changes
- Still have some concerns about setRate caching w.r.t to roundId == 0 case.
- Would prefer to see the reference spreadsheet comitted as without it the tests for dynamic fee aren't maintainable.
- Some other small issues.

2021-12-09 06:59 UTC, artdgn commented on contracts/ExchangeRates.sol
> +        if (rate == _rates[currencyKey][currentRoundForRate[currencyKey]].rate) return;
nit: inline returns don't seem to be the usual style in the solidity in this codebase, and can be confusing to keep track when reasoning about where the method returns

2021-12-09 06:59 UTC, artdgn commented on contracts/ExchangeRates.sol
> +            currentRoundForRate[currencyKey] = roundId;
what happens when user passes 0 as round id in `mutativeEffectiveValueAndRatesAtRound`, what will oracle return and what will be cached in `_setRate()`? What will be the effect of that causing an increment in `currentRoundForRate[currencyKey]` because of the `roundId == 0` flow?

2021-12-09 06:59 UTC, artdgn commented on contracts/ExchangeRates.sol
> +            // Note: this will effectively start the rounds at 1, which matches Chainlink's Agggregators
Still not sure if this flow needs to be in this contract if it's only used for testing. Shouldn't it be extended in a `Testable...` contract instead adding complexity and surface area in this contract?

I'm reading this again and again and it still doesn't sit right with me.

It seems that maybe anyone can increment `currentRoundForRate[currencyKey]` at will as much as they want by passing a `0` as round id in the `mutativeEffectiveValueAndRatesAtRound`. Can that cause some cache poisoning or some accounting bugs?

2021-12-09 06:59 UTC, artdgn commented on contracts/Exchanger.sol
> +        (uint[] memory rates, ) = exchangeRates().ratesAndUpdatedTimeForCurrencyLastNRounds(currencyKey, 4, 0);
nit: mysterious `4` magic number should probably be a named constant (I know it's not new code, but still might be nice to fix since the line is touched).

2021-12-09 06:59 UTC, artdgn commented on contracts/Exchanger.sol
> +        uint currentRoundId = exchangeRates().currentRoundForRate(currencyKey);
can this be manipulated externally through `mutativeEffectiveValueAndRatesAtRound` and the ability to pass `0` roundId to increment `currentRoundForRate`?

2021-12-09 06:59 UTC, artdgn commented on contracts/MixinSystemSettings.sol
> +        threshold = getExchangeDynamicFeeThreshold();
gas: can be further improved by using `getUIntValues` to get multiple values from `flexibleStorage` in a single call.

2021-12-09 06:59 UTC, artdgn commented on contracts/SystemSettings.sol
> +    /// @notice Set exchange dynamic fee threshold constant default 40bps
nit: can probably mention that value is not in bips but is decimal ratio

2021-12-09 06:59 UTC, artdgn commented on contracts/SystemSettings.sol
> +        flexibleStorage().setUIntValue(SETTING_CONTRACT_NAME, SETTING_EXCHANGE_DYNAMIC_FEE_ROUNDS, rounds);
can be 0?

2021-12-09 06:59 UTC, artdgn commented on contracts/SystemSettings.sol
> +        flexibleStorage().setUIntValue(SETTING_CONTRACT_NAME, SETTING_EXCHANGE_MAX_DYNAMIC_FEE, maxFee);
can be 0?

2021-12-09 06:59 UTC, artdgn commented on test/contracts/CollateralShort.js
> +			await exchangeRates.updateRates([sETH], ['100'].map(toUnit), timestamp, {
Is there a test for fewer than 10 rounds available?

2021-12-09 06:59 UTC, artdgn commented on test/contracts/TestableDynamicFee.js
> +	it('Can get dynamic fee according to SIP feasibility spreadsheet round 13-22, all below threshold', async () => {
can you please commit the spreadsheet as a csv with the formulas as text so that future maintainers can reference that if needed to update / check the tests?

2021-12-09 23:28 UTC, artdgn commented on contracts/ExchangeRates.sol
> +            currentRoundForRate[currencyKey] = roundId;
Seems that anyone can poison the cache by calling it with 0 - and setting several future rates to the current rate. Which will result in incorrect rate being used when future rounds happen because poisoned cached values will be used.

It seems that this whole currentRoundId incrementing should be avoided.

2021-12-09 23:28 UTC, artdgn commented on contracts/ExchangeRates.sol
> +            // Note: this will effectively start the rounds at 1, which matches Chainlink's Agggregators
Added the exploit scenario above.

2021-12-09 23:29 UTC, artdgn commented on contracts/ExchangeRates.sol
> +        if (rate == _rates[currencyKey][currentRoundForRate[currencyKey]].rate) return;
It works but it's easy to miss so hurts readability IMO. Still a nit though.

2021-12-09 23:54 UTC, artdgn commented on contracts/SystemSettings.sol
> +        flexibleStorage().setUIntValue(SETTING_CONTRACT_NAME, SETTING_EXCHANGE_DYNAMIC_FEE_ROUNDS, rounds);
:+1: maybe worth to add that into the comment

2021-12-09 23:55 UTC, artdgn commented on contracts/SystemSettings.sol
> +        flexibleStorage().setUIntValue(SETTING_CONTRACT_NAME, SETTING_EXCHANGE_MAX_DYNAMIC_FEE, maxFee);
Is there a use case for setting this to 0? aren't you disabling dynamic fee by setting rounds to 0 or 1?

2021-12-09 23:56 UTC, artdgn commented on contracts/Exchanger.sol
> +        (uint[] memory rates, ) = exchangeRates().ratesAndUpdatedTimeForCurrencyLastNRounds(currencyKey, 4, 0);
just a named constant in the contract that is set to 4.

2021-12-11 11:01 UTC, leckylao commented on contracts/SystemSettings.sol
> +        flexibleStorage().setUIntValue(SETTING_CONTRACT_NAME, SETTING_EXCHANGE_MAX_DYNAMIC_FEE, maxFee);
This is to cap max dynamic fee to 1 (100%), otherwise it could go negative/overflow.

2021-12-14 05:00 UTC, justinjmoses commented on publish/deployed/mainnet/params.json
> +		"value": "1"
You should just remove this though - this is only meant for overrides @leckylao

2022-01-11 11:00 UTC, artdgn commented
work continued in https://github.com/Synthetixio/synthetix/pull/1642 , closing this one

2022-01-11 11:00 UTC, closed without merging