Futures liquidation fee update
Synthetixio/synthetix pull request #1594
Opened 2021-11-05 04:52 UTC by artdgn

Updates the futures liquidation related logic for the first two items of https://github.com/synthetixio/issues/issues/352:
1. Proportional liquidation fee - to incentivise liquidations of larger positions first. Tentatively set to 35 bps.
2. Proportional liquidation margin buffer - to prevent negative margin liquidation, and to allow proportional fee to be paid to the fee pool. Tentatively set at 25 bps. If this buffer will not be needed in practice for safety (or for fees), the value can be set to 0 in the future.

These two values now allow controlling the proportional liquidation margin, and the allocation of that margin upon liquidation to the liquidator and fee pool. 

Other important changes in this PR:
- Adding the parameters to `FuturesMarketSettings`: `liquidationFeeBPs` and `liquidationBufferBPs`
- Adding new views to `FuturesMarket`: `liquidaionFee` and `liquidationMargin`
- Changing the logic of `_liquidationPrice` to calculate unrecorded funding using the current price.
- Changing the event and debt adjustment during `_liquidatePosition` to use the current price instead of the `liquidationPrice` (which may be higher or lower than actual price at that time, depending on the parameters, buffer, and oracle price).
- Sending any positive remainder of the margin to Fee Pool after deducting the `liquidationFee` (that goes to liquidator).

2021-11-09 06:27 UTC, liamzebedee requested changes

2021-11-09 06:27 UTC, liamzebedee commented on contracts/FuturesMarket.sol
> +            int(position.lastPrice).add(int(liqMargin).sub(int(position.margin)).divideDecimalRound(positionSize)).sub(
This may be a dumb question but I definitely don't claim to be an expert in this area, so please, educate me. Why use the `lastPrice` here when we calculate the liqMargin above using the `currentPrice`?

2021-11-10 02:12 UTC, artdgn commented on contracts/FuturesMarket.sol
> +            int(position.lastPrice).add(int(liqMargin).sub(int(position.margin)).divideDecimalRound(positionSize)).sub(
According to the derivation in the comments above, `lastPrice` is used in order to calculate the profit / loss, which is ` (futurePrice - lastPrice) * positionSize` (which was the price the position was opened / updated at). This is because the formula is trying to solve for the `futurePrice` at which the position will be liquidatable. Using `currentPrice` would give incorrect P&L w.r.t. to position opening price (at which point the "the loan" from the debt pool was taken).

Liquidation margin is calculated using the current price because it's the best estimation we can do currently - because we can't really solve for the actual future liquidation margin because we don't know how funding in the future will affect it (because it depends on 1) time passage and future skew 2) at what times it's being recorded due to other transactions).

Previously liquidation margin was a constant parameter, but making it proportional to price & position introduces this imprecision in solving for liquidation price for the future.

The imprecision is not an issue for the actual liquidation transaction - because then `futurePrice` is `currentPrice`. It's also small when calculated close to the possible liquidation time.

The comments above the code are using trying to give more details about the derivation, but probably can be improved, any idea for what extra details needs to go there?

2021-11-11 04:19 UTC, zyzek commented on contracts/FuturesMarket.sol
> +            return 0;
Instead of returning zero, it is possible to return an estimated fee by returning `_liquidationFee(size, _liquidationPrice(...))` no?

2021-11-11 04:45 UTC, artdgn commented on contracts/FuturesMarket.sol
> +            int(position.lastPrice).add(int(liqMargin).sub(int(position.margin)).divideDecimalRound(positionSize)).sub(
I think you've left a similar comment in your review below, will respond there.

2021-11-11 04:46 UTC, artdgn commented on contracts/FuturesMarketSettings.sol
> +    function setLiquidationFeeBPs(uint _bps) external onlyOwner {
Fair point, will see how I can make it more consistent.

2021-11-11 04:49 UTC, zyzek commented on contracts/FuturesMarket.sol
> +            int(position.lastPrice).add(int(liqMargin).sub(int(position.margin)).divideDecimalRound(positionSize)).sub(
Oops, somehow managed to duplicate the comment. Sorry about that.

2021-11-11 04:53 UTC, artdgn commented on contracts/FuturesMarketSettings.sol
> +    function setLiquidationFeeBPs(uint _bps) external onlyOwner {
Do you see any reason for such differences? If we see a reason it should be easy enough to add, otherwise, better to have fewer parameters probably.

2021-11-11 05:17 UTC, artdgn commented on contracts/FuturesMarket.sol
> +        return proportionalFee > minFee ? proportionalFee : minFee;
The problem with that is that the fee is what needs to be `max()`ed so that the keeper isn't underincentivised. And the `_liquidationFee()` is used separately in during liquidation to determine the payment sent to the keeper.

This would mean that if we make the liquidation margin calculation more straight forward like you suggested, it would use a slightly different calculation to the actual fee, and so would be slightly inconsistent (and also require ensuring both get updated correctly in any future changes).

I think both approaches are close enough to not split hairs, but I prefer the current one for the internal consistency, and encapsulation of the liquidationFee calculation in one function.

--------------------

> The minimum initial margin requirement actually accounts properly for the buffer

Not sure about that one, as the minimum initial margin is not really tied to any position size I think, so there's no buffer that can be applied in all cases.

2021-11-11 05:25 UTC, artdgn commented on contracts/FuturesMarket.sol
> +            return 0;
It's possible to calculate, but it seemed to me a strange value to return - a fee for a price at which the liquidation cannot be done, so won't ever be paid (because what will be paid - is for a different price, so a different fee). 

More specifically it seemed that this function is what actually should be used by liquidators (because `canLiquidate()` doesn't have enough information to decide how profitable this liquidation is). So it makes sense to have 0 fee for liquidation that cannot happen in the context of a liquidator using this function in a script.

I will add a comment to explain this reasoning in the code.

2021-11-11 05:33 UTC, artdgn commented on contracts/FuturesMarketSettings.sol
> +        require(_minLiquidationFee() <= _minMargin, "min margin < liquidation fee");
I think the initial margin enforces minimum margin even in the absence of a position, so the only thing we can check in that case is that it covers the `minLiqudiationFee`, because can't really assume a position size until they try to open it. 

Currently min-fee is set at `20` and min-margin is at `100`.

2021-11-12 00:08 UTC, artdgn commented on contracts/FuturesMarket.sol
> +            int(position.lastPrice).add(int(liqMargin).sub(int(position.margin)).divideDecimalRound(positionSize)).sub(
Thanks, will have a more thorough think through these scenarios in terms of debt and post back my conclusions here.

2021-11-12 01:47 UTC, jacko125 commented on contracts/FuturesMarket.sol
> +        return _abs(positionSize).multiplyDecimalRound(price).mul(_liquidationBufferBPs()).div(10000);
@artdgn What's the reason to div by 10,000 ?

2021-11-12 01:57 UTC, zyzek commented on contracts/FuturesMarket.sol
> +            int(position.lastPrice).add(int(liqMargin).sub(int(position.margin)).divideDecimalRound(positionSize)).sub(
I'll add that other than this last point, I'm more or less satisfied that the PR looks pretty solid. As long as the debt considerations are being kept in mind, I'll leave it to full-time contributors for further review and approval (I haven't looked at test cases, config files and so on).

2021-11-12 03:38 UTC, artdgn commented on contracts/FuturesMarket.sol
> +        return _abs(positionSize).multiplyDecimalRound(price).mul(_liquidationBufferBPs()).div(10000);
Hey, it's because it seemed simplest to set those fees in basis points instead of decimals. This is because they are always discussed and documented in basis points - so it seemed the most natural unit for them instead of decimals. I can make them decimals if it's too confusing.

2021-11-12 04:29 UTC, jacko125 commented on contracts/FuturesMarket.sol
> +            return 0;
Perhaps a view function of the possible liquidation fees based on position size regardless would be useful for the keeper bots to sort / organise which positions have the most fees if they become liquidatble? 

The price to pass in per unit of base asset would be the position.liquidationPrice ?

2021-11-12 04:29 UTC, jacko125 commented on contracts/FuturesMarket.sol
> +        return proportionalFee > minFee ? proportionalFee : minFee; // not using _max() helper because it's for signed ints
Feels like the comment here at the end of line isn't needed

2021-11-12 04:52 UTC, jacko125 approved these changes
Happy with the changes. What are the default liquidation fee ratio % and buffer % in mind that we will set for deployment ? And then these can be added to sip-80

2021-11-12 05:13 UTC, artdgn commented on contracts/FuturesMarket.sol
> +            int(position.lastPrice).add(int(liqMargin).sub(int(position.margin)).divideDecimalRound(positionSize)).sub(
Had a deeper look into the debt calculations:

1. It seems that for the subject of liquidations, the liquidation price actually makes no difference for the debt calculations. This is because the new position is of 0 size and 0 margin, so the price used doesn't matter. So the new position adds no debt and the old position's debt is subtracted at its last price.
```
// in _liquidatePosition
        _applyDebtCorrection(
            Position(0, 0, 0, price, fundingIndex),
            Position(0, position.margin, positionSize, position.lastPrice, position.fundingIndex)
        );

// _positionDebtCorrection

    function _positionDebtCorrection(Position memory position) internal view returns (int) {
        return
            int(position.margin).sub(
                position.size.multiplyDecimalRound(int(position.lastPrice).add(fundingSequence[position.fundingIndex]))
            );
    }

// _applyDebtCorrection

    function _applyDebtCorrection(Position memory newPosition, Position memory oldPosition) internal {
        int newCorrection = _positionDebtCorrection(newPosition);
        int oldCorrection = _positionDebtCorrection(oldPosition);
        _entryDebtCorrection = _entryDebtCorrection.add(newCorrection).sub(oldCorrection);
    }
```

2. Unrelated to the liquidation related debt calculation I don't really understand the role of the funding rate component of the debt correction calculation. It seems to me that the FR shouldn't be included in it. Because for a new position - there is no funding component in the debt added (the position is new), and for a modified position the funding is already counted in the updated margin along with the P&L. So I think it should probably be removed. I'll follow up on that out of band and if needed it will be a separate PR.

2021-11-12 05:15 UTC, artdgn commented on contracts/FuturesMarket.sol
> +        return proportionalFee > minFee ? proportionalFee : minFee; // not using _max() helper because it's for signed ints
the comment is there because it was suggested to use `_max()` in the reivew, and without this comment someone might have the same idea in future - and the comment will spare them the trouble :)

2021-11-12 05:24 UTC, artdgn commented
> Happy with the changes. What are the default liquidation fee ratio % and buffer % in mind that we will set for deployment ? And then these can be added to sip-80

Yeah the sip will need to be updated, but perhaps worth to wait to make a single update with all the changes in this task.

The values I've set right now is:
- 35 bps for fee incentive (so $35 for each 10K in notional risk).
- 25 bps for buffer. The logic is that if actual liquidation price is on average 0.5% worse than the first liquidation price - the stakers will not be impacted.

2021-11-16 04:03 UTC, merged