Sip 185 debt shares
Synthetixio/synthetix pull request #1601
Opened 2021-11-15 00:53 UTC by dbeal-eth

Implements [SIP-185](https://sips.synthetix.io/sips/sip-185/)

notes:
* Upon deployment, for both networks, this SIP will require running a one time`importAddresses` script to migrate the debt from the old `SynthetixState` to `SynthetixDebtShares`. how will this be done with the multisig on mainnet?
* SIP says "The precision of the debt shares will be 18 decimal places." In accordance with this, tests have been modified to accept higher tolerance for debt calculations.
* many of the tests in the `Liquidations` unit test should probably be moved to `Issuer` becuase the functionality being tested is actually in the `Issuer` contract. For now I have just adjusted the tests.

2021-11-15 17:32 UTC, barrasso requested changes
Looks good overall -- just had some minor comments. Also, needs some moar coverage

2021-11-15 17:32 UTC, barrasso commented on contracts/SynthetixDebtShare.sol
> +    function sharePercentOnPeriod(address account, uint periodId) public view returns (uint) {
[np] `sharePercentOnPeriod` could also be declared `external`

2021-11-15 17:32 UTC, barrasso commented on contracts/SynthetixDebtShare.sol
> +    function finishSetup() public onlyOwner {
[np] `importAddresses` and `finishSetup` can be declared `external`

2021-11-16 00:17 UTC, dbeal-eth commented on contracts/FeePool.sol
>      ) public optionalProxy_onlyOwner onlyDuringSetup {
wouldn't that be out of scope for this PR?

2021-11-16 01:24 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +    function finishSetup() public onlyOwner {
https://github.com/Synthetixio/synthetix/pull/1601/commits/834ec9d650cf2905bed85769d99f8a5a30703d33

2021-11-16 01:24 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +    function sharePercentOnPeriod(address account, uint periodId) public view returns (uint) {
https://github.com/Synthetixio/synthetix/pull/1601/commits/834ec9d650cf2905bed85769d99f8a5a30703d33

2021-11-16 01:24 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +    function sharePercent(address account) public view returns (uint) {
https://github.com/Synthetixio/synthetix/pull/1601/commits/834ec9d650cf2905bed85769d99f8a5a30703d33

2021-11-16 18:11 UTC, dbeal-eth commented on contracts/FeePool.sol
>                  // Gas optimisation - to reuse debtEntryIndex if found new applicable one
https://github.com/Synthetixio/synthetix/pull/1601/commits/bff2fb6400d807b30f10d4164883e2d641fc000c

2021-11-16 18:12 UTC, dbeal-eth commented on contracts/FeePool.sol
>              // We can skip the period, as no debt minted during period (next period's startingDebtIndex is still 0)
https://github.com/Synthetixio/synthetix/pull/1601/commits/9043de18ee9abe340fddad027f8a782e2fc1676e

2021-11-16 18:12 UTC, dbeal-eth commented on contracts/FeePool.sol
>      ) public optionalProxy_onlyOwner onlyDuringSetup {
https://github.com/Synthetixio/synthetix/pull/1601/commits/9043de18ee9abe340fddad027f8a782e2fc1676e

2021-11-21 12:26 UTC, jacko125 commented on contracts/BaseSynthetix.sol
> +        if (issuer().debtBalanceOf(account, "sUSD") > 0) {
Why not check whether the account has any debt shares and if 0, you could save more gas and skip this check for transferring ?

2021-11-21 12:30 UTC, jacko125 commented on contracts/FeePool.sol
> +        if (userOwnershipPercentage == 0) {
@dbeal-eth  Have to be careful here that they can still claim previous fee periods even if they now have burned all their debt / no current debt shares %. 

This is why it checked that their `debtEntryIndex == 0` as well which meant they never minted debt before.

2021-11-21 22:56 UTC, dbeal-eth commented on contracts/BaseSynthetix.sol
> +        if (issuer().debtBalanceOf(account, "sUSD") > 0) {
I think I just wanted to reuse the `issuer` dependency. You are right, checking the debt shares contract directly would make more sense.

2021-11-21 22:56 UTC, dbeal-eth commented on contracts/FeePool.sol
> +        if (userOwnershipPercentage == 0) {
is there a unit test, or an easy way to write one?

2021-11-23 11:57 UTC, jacko125 commented on contracts/FeePool.sol
> +        if (userOwnershipPercentage == 0) {
I think best way to test is 

- Mint sUSD in period 1
- Close period 1
- Should have rewards / fees claimable in period 1 
- Burn all debt 
- Should still have rewards / fees claimable in period 1

2021-11-29 04:08 UTC, jacko125 commented on contracts/Issuer.sol
> +        require(amount > 0, "Issuer: cannot issue 0 synths");
Save them gas on this check

2021-11-29 04:23 UTC, jacko125 commented on contracts/SynthetixDebtShare.sol
> +    function finishSetup() external onlyOwner {
Love how this is just a toggle for finalizing the import

2021-11-29 04:25 UTC, jacko125 approved these changes
LGTM most of the changes.

2021-11-29 05:01 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        require(amount > 0, "Issuer: cannot issue 0 synths");
if this check is not included, a test fails because the issuer tries to issue 0 synths and ultimately succeeds in doing so

2021-11-29 05:03 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +    function finishSetup() external onlyOwner {
the owner calls it once it has finished calling `importAddresses`, at which point it will not be able to call `importAddresses` any more. You will see later this week, it will be included in the script.

its not flippable back to false intentionally, its just to record if the contract is still in a sort of initialization mode or not.

2022-01-13 22:07 UTC, dbeal-eth commented on test/contracts/DebtCache.js
> +				await synthetix.transfer(account1, toUnit('10000'), { from: owner });
this test is changed because the amount of SNX sent initially is not enough to cover the case where issued synths are low enough to allow testing of the final assertion to not transfer SNX if issued debt

2022-01-13 22:07 UTC, barrasso approved these changes

2022-01-18 06:03 UTC, artdgn requested changes
Mainly small issues and questions.

2022-01-18 08:53 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +            return uint(-1);
doesn't work in this version of solidity.

2022-01-18 09:04 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +        for (int i = int(accountPeriodHistoryCount) - 1;i >= int(MAX_PERIOD_ITERATE < accountPeriodHistoryCount ? accountPeriodHistoryCount - MAX_PERIOD_ITERATE : 0);i--) {
1. an example? tbh I'm not seeing how this would be more readable
2. By the time, a caller would probably prefer that the function drop out in order to save gas rather than trying to binary search for really old values. Also binary search would still fail in the case of extremely large number of values (ex 60k). So rather than adding the functionality which still only works in some cases (which we don't really need), I just didn't add the bin search
3. the loop is required because it would not be gas efficient for fee pool to iterate from outside the contract
4. are you saying simplify the declaration by adding a second `if` condition within the loop? in that case, why not just add line before:
```
uint maxIterate = int(MAX_PERIOD_ITERATE < accountPeriodHistoryCount ? accountPeriodHistoryCount - MAX_PERIOD_ITERATE : 0);
```

2022-01-18 09:05 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +        totalSupplyOnPeriod[newPeriodId] = totalSupplyOnPeriod[currentPeriodId];
good idea

2022-01-18 09:07 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +    function transferFrom(address from, address to, uint256 amount) external onlyAuthorizedBrokers {
right now the only authorized broker we are going to have is the L2 bridge contract, for transferring debt to L2.

we can still add the functionality to let users "approve" a broker I suppose but it really seems like an unnecessary transaction

2022-01-18 09:11 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +        uint amount;
don't know how I missed this :laughing:

2022-01-18 12:33 UTC, artdgn commented on contracts/SynthetixDebtShare.sol
> +            return uint(-1);
right right :+1:

2022-01-19 04:45 UTC, artdgn commented on contracts/SynthetixDebtShare.sol
> +        for (int i = int(accountPeriodHistoryCount) - 1;i >= int(MAX_PERIOD_ITERATE < accountPeriodHistoryCount ? accountPeriodHistoryCount - MAX_PERIOD_ITERATE : 0);i--) {
I think if you don't want to add the binary search:

1. It would be nice to enable someone to perform the binary search externally by adding a length getter:
```solidity
function balancesLength(address account) external view returns (uint) {
    return balances[account].length;
}
```
I think given that this contract is not upgradeable, this would be an important addition to make the data easily usable from outside.

2. Just making the code block a bit more readable, and possibly adding a short circuit would be great. Maybe something like:
```solidity
        uint balancesLength = balances[account].length;
        // no history: short circuit everything
        if (balancesLength == 0) {
            return 0; 
        }
        PeriodBalance memory entry;
        uint maxIterate = balancesLength > MAX_PERIOD_ITERATE ? balancesLength - MAX_PERIOD_ITERATE : 0;
        for (uint i = balancesLength - 1; i >= maxIterate; i--) {
            entry = balances[account][i];
            if (entry.periodId <= periodId) {
                return entry.amount;
            }
        }
        return 0;
```

3. > Also binary search would still fail in the case of extremely large number of values (ex 60k).

Can be implemented with limits (what indices to search between), and 60k weeks is more than a 1000 years :)

2022-01-19 04:55 UTC, artdgn commented on contracts/SynthetixDebtShare.sol
> +    function transferFrom(address from, address to, uint256 amount) external onlyAuthorizedBrokers {
To me it seems that the blast radius / surface area this `authorizedBroker` has, is very large in this contract and so the whole system. 

The reasons I think it makes sense to add the approve workflow:
1. It reduces the blast radius of any issue with `authorizedBroker` from "the whole protocol needs to stop and migrate" to "approvals need to be revoked and a few users need to be refunded"
2. It reduces the protocol's centralisation (in theory and practice).
3. Approvals transactions are cheap, and people are already used to them when bridging.
4. The workflow is right there in the standard that is being implemented, if the only reason to actively remove a security feature is minor gas savings - it may not be a good tradeoff.

2022-01-19 05:10 UTC, artdgn commented on contracts/SynthetixDebtShare.sol
> +        return 0;
Should this revert instead of returning 0? I know we don't like reverting views, a caller of this method has no way of knowing if users has actually 0 debt or if the loop went out of bounds.

An alternative is to return a tuple of `(uint amount, bool valid)` and to return `valid = false` if the loop went out of bounds.

2022-01-19 05:10 UTC, artdgn commented on contracts/SynthetixDebtShare.sol
> +    function sharePercentOnPeriod(address account, uint periodId) external view returns (uint) {
Same as `balanceOfOnPeriod` - this would return 0 if the loop goes out of bounds. I see same two solutions - either this reverts (because `balanceOfOnPeriod` reverts), or it returns another `bool valid` which the caller would use to know if the debt was really 0 or is just unknown.

2022-01-19 21:01 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +    function transferFrom(address from, address to, uint256 amount) external onlyAuthorizedBrokers {
you do realize that if a user has their debt share balance transferred from them, thats a good thing for them, right? the only attack vector we truly have to worry about here is that a user transfers their *own* debt to a place where they don't have to repay it, So really the only one who really should be approving is the protocol itself (hence `authorizedBroker`)

1) nobody needs to be refunded. at most, the protocol loosese money 2) debt shares are inherently completely centralized and controlled by us. if it was decentralized, the whole system wouldn't work 3) not cheap in friction and dev time :) 4) despite what it looks like, debt shares are not ERC20 compatible and they never will be, and if we treat it as such its just useless

2022-01-19 21:05 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +        if (accountBalanceCount == 0) {
this code doesn't work correctly because, in the case that the `else` case is taken, the `lastBalance` is not taken into account from `prevPeriodId`

2022-01-19 21:06 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +        if (accountBalanceCount == 0) {
i understand that your concern is that this code is too hard to parse, so I will see if there is anything that can be done to reduce the comprehension barrier

2022-01-19 21:10 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +        uint amount;
3783e05b

2022-01-19 21:10 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +    function _supplyBalance(address account, uint amount) internal {
3783e05b

2022-01-19 21:12 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +            balances[account].push(PeriodBalance(balances[account][accountBalanceCount - 1].amount.add(amount), currentPeriodId));
didn't split into temp variables, but did split the line

this whole function will be re-evaluated to improve clarity in other ways.

3783e05b

2022-01-19 21:12 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +        emit Transfer(address(from), address(to), amount);
3783e05b

2022-01-19 21:16 UTC, dbeal-eth commented on test/contracts/SynthetixDebtShare.js
> +				await synthetixDebtShare.setCurrentPeriodId(toUnit('10'), { from: issuer });
period can be any uint128

2022-01-19 21:17 UTC, dbeal-eth commented on test/contracts/SynthetixDebtShare.js
> +				reason: 'SynthetixDebtShare: only issuer can mint/burn',
mislabel

2022-01-19 21:27 UTC, dbeal-eth commented on test/contracts/SynthetixDebtShare.js
> +				reason: 'SynthetixDebtShare: only issuer can mint/burn',
6104a06b

2022-01-19 21:27 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +    function approve(address spender, uint256 amount) external {
6104a06b

2022-01-19 22:11 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +    mapping(address => bool) public authorizedBrokers;
da67a273

2022-01-19 22:11 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +    mapping(address => PeriodBalance[]) public balances;
da67a273

2022-01-19 22:12 UTC, dbeal-eth commented on contracts/SynthetixDebtShare.sol
> +        return 0;
1c8d00c

2022-01-21 02:46 UTC, artdgn commented on test/contracts/SynthetixDebtShare.js
> +				await synthetixDebtShare.setCurrentPeriodId(toUnit('10'), { from: issuer });
Yes, but it seems like a strange value and so it may be a sign of some kind of copy paste mix up when writing the test.

2022-02-03 21:54 UTC, barrasso reviewed
few minor comments

2022-02-03 21:54 UTC, barrasso commented on package.json
> -		"@gnosis.pm/safe-service-client": "1.1.0",
should we revert this and keep the upgraded gnosis sdk?

2022-02-03 21:54 UTC, barrasso commented on publish/deployed/mainnet/owner-actions.json
> -{}
revert this?

2022-02-03 21:54 UTC, barrasso commented on publish/src/commands/owner.js
> +				console.log('go2');
a couple of console.logs in here

2022-02-03 21:54 UTC, barrasso commented on publish/src/commands/owner.js
> +					to: '0x0e16A6876210841577b233C4165d7B7EdF640b8a',
unnecessary change here?

2022-02-04 19:07 UTC, merged