add liquidation tests in integration
Synthetixio/synthetix pull request #1625
Opened 2021-12-08 14:52 UTC by dbeal-eth

still needs to be filled out with a couple more checks but overall
the process is there.

wondering if a little bit more code should be added to the helpers for
rates? let me know if this code is clean enough or not.

2021-12-08 16:03 UTC, barrasso approved these changes
LGTM, just need to run linter

2021-12-15 05:30 UTC, justinjmoses commented on test/integration/behaviors/liquidations.behavior.js
> +					await skipLiquidationDelay({ ctx });
I'd put this wait in a `describe` block so it reads `when the liquidation delay passes`

2021-12-15 05:30 UTC, justinjmoses commented on test/integration/behaviors/liquidations.behavior.js
> +				});
can you also check sUSD has been burned from `otherUser`?

2021-12-15 05:32 UTC, justinjmoses requested changes
Just a few small things, but 100% the right direction.

Can you also fix the `fork-tests` - you can use the `updateExchangeRatesIfNeeded` helper

2021-12-16 23:21 UTC, justinjmoses commented on test/integration/behaviors/liquidations.behavior.js
> +							await Synthetix.debtBalanceOf(otherUser.address, toBytes32('sUSD')),
it burns sUSD from `otherUser` right? the debt balance of `someUser` should go down and the sUSD balance should go down for `otherUser`

2021-12-17 17:03 UTC, barrasso commented on test/integration/behaviors/liquidations.behavior.js
> +					await skipLiquidationDelay({ ctx });
https://github.com/Synthetixio/synthetix/pull/1625/commits/7387c9ec0f7b803bab7267f2b8a51a00cbaf6281

2021-12-22 21:47 UTC, barrasso commented on test/integration/behaviors/liquidations.behavior.js
> +							await Synthetix.debtBalanceOf(otherUser.address, toBytes32('sUSD')),
https://github.com/Synthetixio/synthetix/commit/11dad8196b1b8a61bc8c751ebffbb8fb2c5c9d8d

2021-12-22 21:47 UTC, barrasso commented on test/integration/behaviors/liquidations.behavior.js
> +				});
https://github.com/Synthetixio/synthetix/commit/11dad8196b1b8a61bc8c751ebffbb8fb2c5c9d8d

2021-12-26 03:46 UTC, justinjmoses commented on test/integration/behaviors/liquidations.behavior.js
> +						assert.notEqual(await Synthetix.balanceOf(someUser.address), '100000000000000000000');
[np] I'd at least use `assert.bnLt` rather than `notEqual`

2021-12-26 03:46 UTC, justinjmoses approved these changes
Approved! Just one minor nitpick

2021-12-29 22:18 UTC, barrasso commented on test/integration/behaviors/liquidations.behavior.js
> +						assert.notEqual(await Synthetix.balanceOf(someUser.address), '100000000000000000000');
https://github.com/Synthetixio/synthetix/pull/1625/commits/658db9280e3f0ea6d82bdd5398f2edb80b10451f

2021-12-30 14:32 UTC, merged