Feat(SystemSettings): SIP-193 Reduce size for SystemSettings
Synthetixio/synthetix pull request #1627
Opened 2021-12-08 23:18 UTC by leckylao

2021-12-15 05:43 UTC, justinjmoses commented on contracts/SystemSettingsLib.sol
> +    ) public {
not `external`?

2021-12-15 05:44 UTC, justinjmoses commented on contracts/SystemSettingsLib.sol
> +    function setIssuanceRatio(
can you please ignore the re-entrancy errors in slither in this file?

2021-12-20 15:38 UTC, barrasso commented on contracts/MixinSystemSettings.sol
> -    bytes32 internal constant SETTING_NEW_COLLATERAL_MANAGER = "newCollateralManager";
Safe to remove these 👍 Following SIP-135: `minCratio` and `collateralManager` are now set in `Collateral.sol`.

2021-12-26 05:23 UTC, justinjmoses commented on contracts/SystemSettings.sol
> +            MIN_FEE_PERIOD_DURATION,
these are only used in `SystemSettingsLib` so they could be moved over there instead of passed in as args

2021-12-26 05:23 UTC, justinjmoses commented on contracts/SystemSettings.sol
> +            MIN_CROSS_DOMAIN_GAS_LIMIT,
these limit definitions can be moved into the lib

2021-12-26 05:24 UTC, justinjmoses commented on contracts/SystemSettings.sol
> +            SETTING_CONTRACT_NAME,
i say redefine this `SETTING_CONTRACT_NAME` in the lib to avoid passing it each and every time

2021-12-26 05:30 UTC, justinjmoses commented on test/contracts/SystemSettings.js
> +			const encodeEventSignature = AbiCoder.encodeEventSignature({
This can be done without an extra package in `package.json`: see https://github.com/Synthetixio/synthetix/blob/develop/test/etherscan/spec.js#L113

2021-12-26 05:30 UTC, justinjmoses requested changes
A few minor changes but overall looking good!

2021-12-26 08:45 UTC, leckylao commented on test/contracts/SystemSettings.js
> +			const encodeEventSignature = AbiCoder.encodeEventSignature({
> This can be done without an extra package in `package.json`: see https://github.com/Synthetixio/synthetix/blob/develop/test/etherscan/spec.js#L113

I had thought of that initially but the problem is need to set up the web3 instance which is too verbose for this case. And the `web3-eth-abi` is actually an existing package on other dependancy https://raw.githubusercontent.com/Synthetixio/synthetix/develop/package-lock.json. So it's not a new package and putting it in will let the git hook pass on the require missing package.

2021-12-26 08:49 UTC, leckylao commented
After moving public constant it reduced size more down from 64% to 61%
<img width="699" alt="image" src="https://user-images.githubusercontent.com/148800/147403294-c13f6239-c45e-4f6f-8021-c8b9196ed16d.png">

2022-01-10 02:10 UTC, artdgn requested changes
Some readability and maintainability concerns with the contract separation and testing code.

2022-01-10 02:10 UTC, artdgn commented on contracts/MixinSystemSettings.sol
>      function getInteractionDelay(address collateral) internal view returns (uint) {
What the reasoning for separating the setters from the getters, especially if they rely on this intimate knowledge of the storage mapping schema? 

Shouldn't the getters go to the lib as well? If the intention to split them is for contract size savings, than to me it makes more sense to split such that each setter is near it's getter (so e.g. some values are in the lib, and some are here, or have two libs or something). 

Maybe a "core" settings contract that also uses an "ExtraSettingsLib" that houses the extras? It seems that this getters and setters split makes things less readable, and breaks encapsulation of implementation details too much.

This would also reduce the long method signatures and passing of constants.

2022-01-10 03:39 UTC, leckylao commented on contracts/MixinSystemSettings.sol
>      function getInteractionDelay(address collateral) internal view returns (uint) {
Didn't touch much on `MixinSystemSettings.sol`, mainly removed the non-using functions. And the getters are mainly one line so not much can reduce.

2022-01-10 03:39 UTC, leckylao commented on test/contracts/setup.js
> +		if (/^SystemSettings$/.test(artifact._json.contractName)) {
Not sure how it could be refactored outside of the if. And it should be self explanatory that special linking library when SystemSettings otherwise normal linking. 

> Also, isn't this regex equivalent to just a comparison (===) ?
I think so, would leave it for now.

2022-01-10 03:39 UTC, leckylao commented on test/integration/behaviors/stake.behavior.js
> +		const SNXAmount = ethers.utils.parseEther('1000');
It fixes this one. 
https://app.circleci.com/pipelines/github/Synthetixio/synthetix/9775/workflows/f2026f37-4e7f-4a23-9127-b1d31f20adac/jobs/101109?invite=true#step-109-1867

2022-01-10 03:49 UTC, leckylao commented on contracts/SystemSettings.sol
> +        SystemSettingsLib.setWaitingPeriodSecs(
> why not use the usual library syntax by adding `using SystemSettingsLib for IFlexibleStorage` and then calling `flexibleStorage().setWaitingPeriodSecs(...)` instead?

Hmmm, the SystemSettingsLib looks more clear to me than `flexibleStorage().setWaitingPeriodSecs(...)`

> And also maybe avoid the casting to address here and to the interface the lib..

Example pls?

2022-01-10 03:49 UTC, leckylao commented on contracts/SystemSettingsLib.sol
> +        bytes32 settingName,
The `settingName` is originally defined at `MixinSystemSettings.sol` and using there for the getters. So passing it in from there to make single source of variable definition.

2022-01-11 10:48 UTC, artdgn submitted a review, later dismissed

2022-01-11 10:53 UTC, artdgn commented
Contract sizes:
```
├─────────────────────────────────┼────────┼───────────┼──────────────────┼──────────┤
│ SystemSettingsLib               │ 13158  │ 12.85 KB  │ 53.54%           │          │
├─────────────────────────────────┼────────┼───────────┼──────────────────┼──────────┤
...
├─────────────────────────────────┼────────┼───────────┼──────────────────┼──────────┤
│ SystemSettings                  │ 14440  │ 14.1 KB   │ 58.76%           │          │
├─────────────────────────────────┼────────┼───────────┼──────────────────┼──────────┤
```

2022-01-11 19:00 UTC, justinjmoses commented on contracts/MixinSystemSettings.sol
>      function getInteractionDelay(address collateral) internal view returns (uint) {
This is so contracts can mix in the getting of these without having to go externally to the `SystemSettings` contract - they can go directly to `FlexibleStorage`. (So, gas savings)

2022-01-11 19:05 UTC, justinjmoses commented on contracts/SystemSettings.sol
> +    using SystemSettingsLib for IFlexibleStorage;
This is quite a cute solution to how to invoke this

2022-01-11 19:17 UTC, justinjmoses requested changes
A few changes here and there to address, nothing major

2022-01-11 19:17 UTC, justinjmoses commented on contracts/SystemSettings.sol
>          emit CrossDomainMessageGasLimitChanged(_gasLimitType, _crossDomainMessageGasLimit);
why not move this event as well?

2022-01-11 19:17 UTC, justinjmoses commented on contracts/SystemSettingsLib.sol
> +        bytes32 settingName,
We could technically have this library extend from `MixinSystemSettings` - and then not need to pass through the keys...

2022-01-11 19:17 UTC, justinjmoses commented on contracts/SystemSettingsLib.sol
> +        // slither-disable-next-line reentrancy-events
Want to do this for the whole file instead?

2022-01-11 19:17 UTC, justinjmoses commented on contracts/SystemSettingsLib.sol
> +        uint _issuanceRatio
can you fix these slither complaints by removing the leading underscore?

2022-01-11 19:17 UTC, justinjmoses commented on package.json
> +		"web3-eth-abi": "1.6.0"
why is this needed? you can grab it as we do here: https://github.com/Synthetixio/synthetix/blob/feat/reduce-system-settings-size/test/etherscan/spec.js#L102 - please remove this and update SystemSettings.js to use the aforementioned technique

2022-01-11 19:17 UTC, justinjmoses commented on test/contracts/setup.js
> +		if (/^SystemSettings$/.test(artifact._json.contractName)) {
So he means do the SafeDecimalMath linking to `artifact` regardless and then if SystemSettings, then also link `SystemSettingsLib`. I believe that would work the same way but not 100% sure...

2022-01-12 00:52 UTC, artdgn commented on contracts/SystemSettings.sol
>          emit CrossDomainMessageGasLimitChanged(_gasLimitType, _crossDomainMessageGasLimit);
looks like the reason is the usage of the enum `CrossDomainMessageGasLimits` in the sig, which is used in the getter mixin

2022-01-12 00:57 UTC, artdgn commented on contracts/SystemSettingsLib.sol
> +        bytes32 settingName,
I've tried something similar and libraries can't inherit (at least in sol 0.5) from contracts of libraries. 

They can use (be linked), and than we can have a SettingsGettersLib and SettingsSettersLib (that uses the getters one), but it all seems over complicated at that point and the correct and simple solution IMO is to just reduce the contract size by splitting contracts into settings by domain (a bit similar to how it's done with e.g. futures settings). But that would be a very big refactor with questionable payoff at this point.

2022-01-12 01:44 UTC, artdgn commented on contracts/SystemSettingsLib.sol
> +        // slither-disable-next-line reentrancy-events
Slither doesn't really support that, we can exclude the file or the detector entirely. I think it's pretty safe to disable `reentrancy-events` detector entirely as it only relates to events https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities-3 and the usual pattern is to emit at the end of a method, which almost always triggers the detector.

2022-01-12 07:18 UTC, artdgn commented on package.json
> +		"web3-eth-abi": "1.6.0"
I've moved the events back into contract from the library, the contract size is 68%, but testing the events is much more readable and simple now

2022-01-12 07:19 UTC, artdgn commented
Contract sizes:
```
├─────────────────────────────────┼────────┼───────────┼──────────────────┼──────────┤
│ SystemSettingsLib               │ 8189   │ 8 KB      │ 33.32%           │          │
├─────────────────────────────────┼────────┼───────────┼──────────────────┼──────────┤

..
├─────────────────────────────────┼────────┼───────────┼──────────────────┼──────────┤
│ SystemSettings                  │ 16967  │ 16.57 KB  │ 69.04%           │          │
├─────────────────────────────────┼────────┼───────────┼──────────────────┼──────────┤

```

2022-01-12 07:24 UTC, artdgn commented
If we need to further reduce size later we can bundle all the atomic params getter into a single getter that returns a struct and use that instead of the individual getter calls. This will also be more gas efficient due to smaller amount of external calls probably.

2022-01-13 00:25 UTC, justinjmoses approved these changes

2022-01-13 00:26 UTC, merged