fix(ExchangeRates): Remove currentRound auto incrementation
Synthetixio/synthetix pull request #1630
Opened 2021-12-11 08:25 UTC by leckylao

- setting sUSD on constructor;
- moved currentRound auto increment into internalUpdateRates

2021-12-13 01:11 UTC, artdgn reviewed
I was sure we said that removing the curreRate state variable is the best course of action.

The only place it's used right now is the exchanger for getting the last cached rate for dynamic fee to get the correct set of prices. It can be removed there because  you already have the roundIds in the `_exchange` method that you can pass into the fees method to get the historic prices. 

This way, this whole issue with coupling, and incrementing, etc can be avoided.

2021-12-13 01:11 UTC, artdgn commented on contracts/ExchangeRates.sol
> +        currentRoundForRate[currencyKey] = roundId;
I was under the impression that we've agreed that `currentRoundForRate` should be removed because it introduces more risks, potential for bugs, and too much coupling (between rates and exchanger contract).

2021-12-13 02:56 UTC, leckylao commented on contracts/ExchangeRates.sol
> +        if (sourceCurrencyKey != "sUSD") _setRate(sourceCurrencyKey, roundIdForSrc, sourceRate, time);
It does has the != sUSD check in _setRate, here is when reading the sUSD rate don't try to set it. Will put a comment there.

2021-12-13 02:56 UTC, leckylao commented on contracts/ExchangeRates.sol
> +        currentRoundForRate[currencyKey] = roundId;
This is the first iteration. And `currentRoundForRate` is more for improvement due to the tightly coupling and timeframe.

2021-12-13 05:47 UTC, artdgn commented on contracts/ExchangeRates.sol
> +        if (sourceCurrencyKey != "sUSD") _setRate(sourceCurrencyKey, roundIdForSrc, sourceRate, time);
I meant to remove the `require` in _setRate, and instead just return if it's sUSD. 

So in `_setRate` instead of 
```
require(currencyKey != "sUSD", "Rate of sUSD cannot be updated, it's always UNIT.");
``` 
```
if (currencyKey == "sUSD") {
  // no caching is done for sUSD
  return;
}
``` 
This way, there is no need to have those ifs elsewhere and:
- code is easier to read (less ifs)
- whoever is calling setRate doesn't need to check the currency

2021-12-13 23:14 UTC, artdgn requested changes
That's great, now that `currentRoundForRate` is not used, I think it should be possible to remove it also from the `ExchangeRates` contract.

2021-12-13 23:14 UTC, artdgn commented on contracts/Exchanger.sol
> +        if (roundId == 0) roundId = exchangeRates().getCurrentRoundId(currencyKey);
I don't think this method should try to be smart about the roundId it's getting. It's better to avoid using 0 as a special case if we can. This will reduce coupling, edge cases, and surface area for bugs. This method should just work with the roundId it's getting IMO because it's a low level method.

2021-12-13 23:14 UTC, artdgn commented on contracts/Exchanger.sol
> +        exchangeFeeRate = _feeRateForExchange(sourceCurrencyKey, destinationCurrencyKey, 0, 0);
same comment as above.

2022-01-18 23:51 UTC, justinjmoses commented
Closed in favor of #1649

2022-01-18 23:51 UTC, closed without merging