Sip 184 merge develop
Synthetixio/synthetix pull request #1642
Opened 2022-01-08 12:45 UTC by leckylao

2022-01-10 02:20 UTC, artdgn commented
Should https://github.com/Synthetixio/synthetix/pull/1563 be closed in favour of this one?

2022-01-10 05:28 UTC, artdgn requested changes

2022-01-10 05:28 UTC, artdgn commented on test/integration/utils/rates.js
> +		// deploy an aggregator
As these are integration tests, this should probably try to add rates if they're missing, and not always. So probably the check needs to be altered and not removed - it should check probably if there are enough rates, and if there aren't - add them.

2022-01-10 05:28 UTC, artdgn commented on test/integration/utils/rates.js
> +	const MockAggregatorFactory = await createMockAggregatorFactory(ctx.users.owner);
as in the other PR - this method shouldn't deploy and add aggregators, this should be a separate explicit setup step, otherwise this could hide a broken scenario or fork test

2022-01-10 05:29 UTC, artdgn commented
Also, would be nice to see an updated gas usage report.

2022-01-10 06:59 UTC, leckylao commented on contracts/Exchanger.sol
> +        require(!exchangeRates().anyRateIsInvalidAtRound(synthKeys, roundIds), "Src/dest rate invalid or not found");
Similar that the function is meant the be consistent with function `_ensureCanExchange` so not necessary changing the legacy function would just leave it for now and mark as improvement.

2022-01-10 06:59 UTC, leckylao commented on contracts/MixinSystemSettings.sol
> +    function getExchangeDynamicFeeThreshold() internal view returns (uint) {
It's being used in configure-system-settings.js and SystemSettings.js. Especially the `runStep` to keep the same configure after new deployment of `SystemSettings`.

2022-01-10 06:59 UTC, leckylao commented on contracts/MixinSystemSettings.sol
> +    function getExchangeMaxDynamicFee() internal view returns (uint) {
It's fetching from different functions though, might just leave it for now.

2022-01-10 06:59 UTC, leckylao commented on contracts/SystemSettings.sol
> +    function exchangeDynamicFeeThreshold() external view returns (uint) {
It's being used in configure-system-settings.js and SystemSettings.js. Especially the `runStep` to keep the same configure after new deployment of `SystemSettings`.

2022-01-10 06:59 UTC, leckylao commented on test/dynamic-fee-calc.csv
> +,round,price,ΔP (bp),boost,dynamic_fee (bp),,deviation threshold (bp)
Would be refer back to the xlsx spreadsheet.

2022-01-10 06:59 UTC, leckylao commented on test/integration/behaviors/stake.behavior.js
> +		const SNXAmount = ethers.utils.parseEther('100000');
Was trying to fix this but unfortunately works on the other PR but not this one
https://app.circleci.com/pipelines/github/Synthetixio/synthetix/9775/workflows/f2026f37-4e7f-4a23-9127-b1d31f20adac/jobs/101109?invite=true#step-109-1867

2022-01-10 06:59 UTC, leckylao commented on test/integration/utils/rates.js
> +	await _setMissingRates({ ctx });
I am not too familiar with the aggregator stuff and how to change that. As you added this part would you mind having a new PR on top of this to change it?

2022-01-13 00:16 UTC, artdgn commented on contracts/ExchangeRates.sol
> +    function anyRateIsInvalidAtRound(bytes32[] calldata currencyKeys, uint[] calldata roundIds)
It looks like the array variants are more gas efficient in terms of number of external calls vs. checking each rate separately.

2022-01-17 22:19 UTC, artdgn commented
Work continued in https://github.com/Synthetixio/synthetix/pull/1649

2022-01-17 22:19 UTC, closed without merging