SIP 148: Liquidatooor
Synthetixio/synthetix pull request #1647
Opened 2022-01-11 00:28 UTC by barrasso

Introduces the upgraded liquidation mechanism as described in SIP-148: https://sips.synthetix.io/sips/sip-148/

Tracking Issue: https://github.com/Synthetixio/issues/issues/397

2022-02-03 18:55 UTC, noahlitvin commented on contracts/LiquidatorRewards.sol
> +        // Ensure the provided reward amount is not more than the balance in the contract.
I think we'd at least need `rewardRate = reward` here?

2022-02-03 19:04 UTC, barrasso commented on contracts/LiquidatorRewards.sol
> +        // Ensure the provided reward amount is not more than the balance in the contract.
Agreed

2022-02-11 06:00 UTC, artdgn requested changes
Had some concerns about the implementation both in terms of mechanism and some of the calculations.

2022-02-20 05:56 UTC, barrasso commented on contracts/LiquidatorRewards.sol
> +contract LiquidatorRewards is Owned, MixinSystemSettings, ILiquidatorRewards, ReentrancyGuard {
> I think the StakingRewards mechanism relies on some assumptions about time and rewards rate, that make it fair, but that that don't hold here.

Totally agree. I've taken a first stab at removing the time-based components, but I think it still needs some tweaking.

> The core issue being that the rewards are being rewarded in a non-aligned way (for instaneous debt, instead of time-aware debt).

Assuming the 7-day burn lock isn't a strong enough of a disincentive, we'll need to think of an alternative method where we could "take a snapshot" of everyone's debt share balance each time a liquidation occurs and distribute the rewards instantaneously.

2022-02-20 06:01 UTC, barrasso commented on contracts/LiquidatorRewards.sol
> +            rewardsToken.approve(address(rewardEscrowV2()), reward);
Resolved https://github.com/Synthetixio/synthetix/pull/1647/commits/fdefc8f311f941bb74f3ce42897bfb3d3273fb17

2022-02-20 06:02 UTC, barrasso commented on contracts/LiquidatorRewards.sol
> +                    (accumulatedRewards).mul(1e18).div(totalSupply().add(uint(amount)))
Resolved https://github.com/Synthetixio/synthetix/pull/1647/commits/fdefc8f311f941bb74f3ce42897bfb3d3273fb17

2022-02-20 06:02 UTC, barrasso commented on contracts/Issuer.sol
> +                collateralForAccount.divideDecimal(SafeDecimalMath.unit().add(selfLiquidationPenalty)),
Resolved https://github.com/Synthetixio/synthetix/pull/1647/commits/fdefc8f311f941bb74f3ce42897bfb3d3273fb17

2022-02-20 06:02 UTC, barrasso commented on contracts/Issuer.sol
>          if (amountToLiquidate == amountToFixRatio) {
Resolved https://github.com/Synthetixio/synthetix/pull/1647/commits/fdefc8f311f941bb74f3ce42897bfb3d3273fb17

2022-02-20 06:03 UTC, barrasso commented on contracts/Issuer.sol
> +        // Reduce debt share of delinquent account by the amount to liquidate.
https://github.com/Synthetixio/synthetix/pull/1647/commits/fdefc8f311f941bb74f3ce42897bfb3d3273fb17

2022-02-22 16:27 UTC, dbeal-eth requested changes
I think this needs more testing, and some of the existing tests changed for reasons that I think should be explained for clarity.

also we need to consider storage values a little more, such as whether or not we should continue using a new eternal stroage contract, or use flexible storage?

2022-02-22 16:27 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        uint selfLiquidationPenalty = liquidator().selfLiquidationPenalty();
is there a reason for indirection here?

2022-02-22 16:27 UTC, dbeal-eth commented on contracts/Issuer.sol
> +    function selfLiquidateAccount(
np it seems wierd that this function is mutative, but it doesn't  do everything needed for liquidation. it implies that there could be more than one invoker of this function, and the invoker could do different things depending. But that would basically never be the case...

2022-02-22 16:27 UTC, dbeal-eth commented on contracts/LiquidatorRewards.sol
> +    IERC20 public sds; // SynthetixDebtShare
if we redeploy debt shares, does that mean we have to redeploy this contract too?

2022-02-22 16:27 UTC, dbeal-eth commented on contracts/LiquidatorRewards.sol
> +        return synthetixDebtShare().balanceOf(account).mul(rewardPerToken().sub(userRewardPerTokenPaid[account])).div(1e18).add(rewards[account]);
use `multiplyDecimal` instead of `mul` and then `div(1e18)`

2022-02-22 16:27 UTC, dbeal-eth commented on contracts/LiquidatorRewards.sol
> +            snx.approve(address(rewardEscrowV2()), reward);
probably best to do an infinite approval whenever address resolver addresses are refreshed, but we can confirm what the auditors think

2022-02-22 16:27 UTC, dbeal-eth commented on contracts/LiquidatorRewards.sol
> +        // console.log("reward: %s", reward);
remove comments

2022-02-22 16:27 UTC, dbeal-eth commented on contracts/LiquidatorRewards.sol
> +                (lastUpdateTime).mul(accumulatedRewards).mul(1e18).div(supply)
divide decimal instead of `mul(1e18).div(supply)`

2022-02-22 16:27 UTC, dbeal-eth commented on contracts/LiquidatorRewards.sol
> +                (lastUpdateTime).mul(accumulatedRewards).mul(1e18).div(supply)
thsi parenthesis around `lastUpdateTime) is confusing with the `.add` from before and unnecessary

2022-02-22 16:27 UTC, dbeal-eth commented on contracts/SystemSettingsLib.sol
> +    uint public constant MIN_LIQUIDATION_DELAY = 43200; // 12 hours
does solidity not support `12 hours;`?

2022-02-22 16:27 UTC, dbeal-eth commented on publish/src/commands/deploy/configure-legacy-settings.js
> +			contract: 'EternalStorageLiquidator',
random question I just thought of: are we going to need to redeploy the existing `EternalStorageLiquidations` because of this rename, or are we just reusing

2022-02-22 16:27 UTC, dbeal-eth commented on test/contracts/CollateralErc20.js
> +			const renAmount = new BN('46428571');
how did you come out with these numbers? just trying to validate the change of the test

2022-02-22 16:27 UTC, dbeal-eth commented on test/contracts/CollateralEth.js
> +		assert.bnEqual(await ceth.minCratio(), toUnit('1.35'));
uh?

2022-02-23 17:04 UTC, barrasso commented on test/contracts/CollateralEth.js
> +		assert.bnEqual(await ceth.minCratio(), toUnit('1.35'));
Since the `liquidationPenalty` has increased to 30%, we had to increase the `minCratio` of `CollateralEth` and `CollateralShort` to be greater than 130% otherwise `CollateralUtil.liquidationAmount` will try to divide by zero at this line: 

`uint sUSDamount = dividend.divideDecimal(divisor);`

2022-02-23 17:11 UTC, barrasso commented on publish/src/commands/deploy/configure-legacy-settings.js
> +			contract: 'EternalStorageLiquidator',
Good point, maybe it makes sense to leave this alone and revert the name change so we don't have to redeploy.

2022-02-23 17:20 UTC, barrasso commented on contracts/BaseSynthetix.sol
> +        uint flagReward = liquidator().flagReward();
out of scope

2022-02-23 17:20 UTC, barrasso commented on contracts/BaseSynthetix.sol
> +        uint liquidateReward = liquidator().liquidateReward();
also out of scope

2022-02-23 17:24 UTC, barrasso commented on contracts/Issuer.sol
> +        if (amountToLiquidate >= amountToFixRatio) {
Yeah it's a good point. Arthur proposed this change I suppose to cover the case in which there may be a rounding error or something where these values are not exactly equal.

2022-02-23 17:54 UTC, barrasso commented on publish/src/commands/deploy/configure-legacy-settings.js
> +			contract: 'EternalStorageLiquidator',
What are the implications if we do continue on with this name change? Can we reuse the existing `EternalStorageLiquidations` and copy over the state to this new contract? 

I tried to revert the name change and was getting a undefined error at:
```js
await cache['EternalStorageLiquidations'].setAssociatedContract(instance.address, {...}
```

Does the name after `EternalStorage{NAME}` actually have to match the naming convention of the contract it is associated with? ie. `Liquidator`

2022-02-23 17:58 UTC, barrasso commented on contracts/Issuer.sol
> +        if (amountToLiquidate >= amountToFixRatio) {
https://github.com/Synthetixio/synthetix/commit/86b55b9213e2864763ff0df0242859f7df9b972f

2022-02-23 17:58 UTC, barrasso commented on contracts/Issuer.sol
> +        require(!exchanger().hasWaitingPeriodOrSettlementOwing(account, sUSD), "sUSD needs to be settled");
https://github.com/Synthetixio/synthetix/commit/86b55b9213e2864763ff0df0242859f7df9b972f

2022-02-23 17:58 UTC, barrasso commented on contracts/Issuer.sol
> +        uint selfLiquidationPenalty = liquidator().selfLiquidationPenalty();
https://github.com/Synthetixio/synthetix/commit/86b55b9213e2864763ff0df0242859f7df9b972f

2022-02-23 17:58 UTC, barrasso commented on contracts/SystemSettingsLib.sol
> +    uint public constant MIN_LIQUIDATION_DELAY = 43200; // 12 hours
https://github.com/Synthetixio/synthetix/commit/86b55b9213e2864763ff0df0242859f7df9b972f

2022-02-23 19:00 UTC, dbeal-eth commented on contracts/BaseSynthetix.sol
> +        uint flagReward = liquidator().flagReward();
what does out of scope mean in this case? this should reduce scope?

2022-02-23 19:01 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        require(!exchanger().hasWaitingPeriodOrSettlementOwing(account, sUSD), "sUSD needs to be settled");
yea sorry this was np wording, just trying to make the error as obvious as possible

2022-03-01 22:46 UTC, barrasso commented on contracts/BaseSynthetix.sol
> +        uint flagReward = liquidator().flagReward();
sorry meant `undeclared identifier`. I can't access `getFlagReward()` here because this base class only inherits `MixinResolver` and not `MixinSystemSettings`.

2022-03-01 23:01 UTC, barrasso commented on contracts/LiquidatorRewards.sol
> +    IERC20 public sds; // SynthetixDebtShare
now that I think about it... yes.

2022-03-30 17:34 UTC, justinjmoses commented on publish/src/commands/deploy/configure-legacy-settings.js
> +			contract: 'EternalStorageLiquidator',
So there's this:

We wrote `FlexibleStorage` to solve the EternalStorage problem. There's no need to deploy a new EternalStorage contract for each contract - you use the existing `FlexibleStorage` and read/write to it using your contract name via the AddressResolver. Look at how we do it in `Issuer` here: https://github.com/Synthetixio/synthetix/blob/master/contracts/Issuer.sol#L807-L811. We can rewrite Liquidations to do this for reading and writing to storage. And IIRC, we don't need to port the existing liqudations storage data over unless there are any open liquidations.

2022-03-30 17:35 UTC, justinjmoses commented on publish/src/commands/deploy/configure-legacy-settings.js
> +			contract: 'EternalStorageLiquidator',
As for the naming convention - it's only really important in the unit tests `setup.js` - but it is a nice convention.

2022-04-05 03:35 UTC, dbeal-eth requested changes
sorry, but I don't think we should be doing kovan deployment.

2022-04-05 03:35 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        amountToLiquidate = liquidator().calculateAmountToFixCollateral(
i might be confused, but if we are using `amountToLiquidate` to determine amount for liquidating, wouldn't this be a partial liquidation (assuming a "full" liquidation erases all the user's sUSD and any SNX required to cover the amount erased)

2022-04-05 03:35 UTC, dbeal-eth commented on contracts/Issuer.sol
> +            amountToLiquidate = _snxToUSD(collateralForAccount.divideDecimal(SafeDecimalMath.unit().sub(penalty)), snxRate);
shouldn't it be the other way around, where `amountToLiquidate` is the total debt shares for the user, and `totalRedeemed` is the corresponding value of the SNX + the liquidation penalty?

2022-04-05 03:35 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        if (!isSelfLiquidation) {
what if the account is self liquidated and they have fixed their c-ratio, but they have the liquidation flag on their account?

2022-04-05 03:35 UTC, dbeal-eth commented on contracts/Liquidator.sol
> +    function calculateAmountToFixCollateral(
since `debtBalance` and `collateral` are already passed into this function, wouldn't it just be better to pass in the resulting `collateral` by removing the penalty that way?

2022-04-05 03:35 UTC, dbeal-eth commented on contracts/LiquidatorRewards.sol
> +            synthetixDebtShare().balanceOf(account).mul(rewardPerShare().sub(userRewardPerSharePaid[account])).div(1e18).add(
```
synthetixDebtShare().balanceOf(account).mul(rewardPerShare().sub(userRewardPerSharePaid[account])).div(1e18)
```

->
```
synthetixDebtShare().balanceOf(account).multiplyDecimal(rewardPerShare().sub(userRewardPerSharePaid[account]))
```

2022-04-05 03:35 UTC, dbeal-eth commented on contracts/LiquidatorRewards.sol
> +            IERC20(address(synthetix())).approve(address(rewardEscrowV2()), reward);
significant gas benefit would be to put this approval as infinite in the constructor. All that doing the approval here accomplishes is preventing funds from being sent from another function, which can be verified is not the case in this file

2022-04-05 03:35 UTC, dbeal-eth commented on contracts/LiquidatorRewards.sol
> +        return (IERC20(address(synthetix())).balanceOf(address(this))).div(sharesSupply);
i just realized, shouldn't this function record the total synthetix accumulated in the contract, not the current balance of SNX?

otherwise, as user's start redeeming their SNX, the balance will go down and so will the corresponding `rewardPerShare` even though that value should only be able to increase

2022-04-05 03:35 UTC, dbeal-eth commented on test/contracts/LiquidatorRewards.js
> +		it('rewards balance should increase if new rewards come in', async () => {
where is the call to `earned`?

2022-04-05 03:35 UTC, dbeal-eth commented on test/contracts/LiquidatorRewards.js
> +			assert.bnLt(postEarnedBal, initialEarnedBal);
if you call `getRewards()`, then you claim all your rewards from the contract, so `postEarnedBal` should be `0`

2022-04-05 03:35 UTC, dbeal-eth commented on test/contracts/LiquidatorRewards.js
> +	describe('getReward()', () => {
need to add more tests for this function:

* if rewards are claimed twice
* if rewards are claimed when there are no rewards
* if two accounts are staking `earned()` remains the same for the account which did not call `getRewards`

2022-04-05 03:35 UTC, dbeal-eth commented on test/contracts/LiquidatorRewards.js
> +	});
need to add general purpose test to verify if debt shares balance changes, either by user changing their debt balance, or by total debt shares changing. The user's rewards should change in accordance with either of those values with respect to time, even if the user does not touch the `liquidatorRewards` contract

2022-04-05 03:35 UTC, dbeal-eth commented on test/integration/behaviors/liquidations.behavior.js
>  						);
might want to add a quick test to verify claiming of liquidator rewards after the fact

2022-04-07 21:41 UTC, dbeal-eth commented on contracts/BaseSynthetix.sol
> +    function liquidateSelf(address account) external systemActive optionalProxy returns (bool) {
`address account` not needed here

2022-04-07 21:45 UTC, justinjmoses commented on contracts/Issuer.sol
> +        }
This change could be quite gas intensive. Can you please run the fork tests with and without this to compare gas on mint, burn, transfer and claim? 🙏🏼

2022-04-07 21:50 UTC, justinjmoses commented on contracts/Liquidator.sol
> +    function _hasEnoughCollateral(address account) internal view returns (bool) {
maybe `hasEnoughSNXBalance` to clarify it's difference from `Synthetix.collateral` which includes escrow

2022-04-07 21:53 UTC, barrasso commented on contracts/BaseSynthetix.sol
> +        uint remainingReward = totalRedeemed.sub(liquidateReward.add(flagReward));
check if remainingReward > 0

2022-04-07 21:55 UTC, barrasso commented on contracts/BaseSynthetix.sol
> +        uint remainingReward = totalRedeemed.sub(liquidateReward.add(flagReward));
add tests for this

2022-04-07 21:56 UTC, barrasso commented on test/integration/behaviors/liquidations.behavior.js
> +			({ owner, user4, user5, user6 } = ctx.users);
change names to flagger, liquidator, liquidated

2022-04-07 21:58 UTC, barrasso commented on test/integration/behaviors/liquidations.behavior.js
> +						assert.bnLt(await SynthetixDebtShare.balanceOf(user4.address), beforeDebt);
check actual values

2022-04-07 22:08 UTC, barrasso commented on test/contracts/Liquidator.js
> +						});
also check that the liquidation flag is cleared here

2022-04-07 22:27 UTC, barrasso commented on contracts/Issuer.sol
> +        if (address(liquidatorRewards()) != address(0)) {
We should also consider if we even want to add this check to `_collateral`. Is it worth the gas increase?

2022-04-18 05:42 UTC, barrasso commented on contracts/Issuer.sol
> +        }
Did some testing and measured about ~10-15% increases in gas usage with this change.

2022-04-20 06:25 UTC, barrasso commented on contracts/Issuer.sol
> +        amountToLiquidate = liquidator().calculateAmountToFixCollateral(
Yeah the terms are a bit confusing, but we're using `amountToLiquidate` here to calculate the amount of debt to burn in order to reach the target c-ratio (this is considered a "full liquidation"). 

A "full liquidation" essentially means an account can only get liquidated **once**.  It'll either attempt to fix their cratio with their SNX collateral, or it will clear all collateral and debt.

A "partial liquidation" is when an account is liquidated for an arbitrary amount of sUSD (`susdAmount`).
 e.g. you could "partially" liquidate someone by calling the function multiple times in $5 intervals.

This SIP doesn't allow for partial liquidations anymore -- that's why `uint susdAmount` was removed from this function.

2022-04-20 06:40 UTC, barrasso commented on contracts/Issuer.sol
> +            amountToLiquidate = _snxToUSD(collateralForAccount.divideDecimal(SafeDecimalMath.unit().sub(penalty)), snxRate);
In this case, the amount of SNX to be redeemed is greater than the amount of account's collateral balance.

So, we need to set `totalRedeemed` to the account's collateral balance. It shouldn't matter about the penalty here since all the SNX is being redeemed anyway.

And then `amountToLiquidate` is the amount of debt to burn (equivalent to the value of the redeemed SNX).

2022-04-20 07:17 UTC, barrasso commented on contracts/LiquidatorRewards.sol
> +            IERC20(address(synthetix())).approve(address(rewardEscrowV2()), reward);
Good point. Although I was wondering if we put an infinite approval in the constructor, what happens when we deploy a new `Synthetix` contract? Wouldn't we need to do another approval somehow?

2022-04-21 19:07 UTC, barrasso commented on contracts/BaseSynthetix.sol
> +        uint remainingReward = totalRedeemed.sub(liquidateReward.add(flagReward));
added check in https://github.com/Synthetixio/synthetix/pull/1647/commits/44262613afb644a98a5637db95df83692c79c6d6


unit tests pending

2022-04-21 19:08 UTC, barrasso commented on contracts/BaseSynthetix.sol
> +    function liquidateSelf(address account) external systemActive optionalProxy returns (bool) {
https://github.com/Synthetixio/synthetix/pull/1647/commits/44262613afb644a98a5637db95df83692c79c6d6

2022-04-21 19:09 UTC, barrasso commented on contracts/Issuer.sol
> +        if (address(liquidatorRewards()) != address(0)) {
removed this for now (https://github.com/Synthetixio/synthetix/pull/1647/commits/44262613afb644a98a5637db95df83692c79c6d6) as I don't think the marginal benefit to minters is worth the gas usage increase across the board

2022-04-21 19:10 UTC, barrasso commented on contracts/Issuer.sol
> +        if (!isSelfLiquidation) {
https://github.com/Synthetixio/synthetix/pull/1647/commits/44262613afb644a98a5637db95df83692c79c6d6

2022-04-21 19:11 UTC, barrasso commented on contracts/Liquidator.sol
> +    function _hasEnoughCollateral(address account) internal view returns (bool) {
https://github.com/Synthetixio/synthetix/pull/1647/commits/44262613afb644a98a5637db95df83692c79c6d6

2022-04-22 20:44 UTC, barrasso commented on contracts/Liquidator.sol
> +    function calculateAmountToFixCollateral(
Could you elaborate on this?

2022-04-23 00:05 UTC, dbeal-eth commented on contracts/Liquidator.sol
> +    function calculateAmountToFixCollateral(
sorry, this was really poorly written

based on the name of the function and the alternatives available, i think its kind of out of scope to factor in the additional parameter `isSelfLiquidation` to figure out what penalty to put into the equation.

the problem is this function has so many args and nuances to the args that it might be better to just have a generic function `calculateAmountToFixCollateral(address account)` which does the whole shebang for a given account passed to `liquidateDelinquentAccount`

also, this function does not take into account the liquidation rewards--only the penalty. Therefore, it is necessary to pass in the `collateralForAccount.sub(liquidationReward)` or else their account will remain undercollateralized after liquidation is completed

2022-04-24 06:15 UTC, barrasso commented on test/integration/behaviors/liquidations.behavior.js
> +			({ owner, user4, user5, user6 } = ctx.users);
https://github.com/Synthetixio/synthetix/commit/f5537535433620c4b0bfec8d672598de1da7b97f

2022-04-27 09:15 UTC, barrasso commented on contracts/LiquidatorRewards.sol
> +        return (IERC20(address(synthetix())).balanceOf(address(this))).div(sharesSupply);
https://github.com/Synthetixio/synthetix/pull/1647/commits/34afd173fdb4bbb33f7da07e9abd32aac9720fc6

2022-04-27 09:15 UTC, barrasso commented on contracts/LiquidatorRewards.sol
> +            synthetixDebtShare().balanceOf(account).mul(rewardPerShare().sub(userRewardPerSharePaid[account])).div(1e18).add(
https://github.com/Synthetixio/synthetix/pull/1647/commits/34afd173fdb4bbb33f7da07e9abd32aac9720fc6

2022-04-27 09:16 UTC, barrasso commented on test/contracts/LiquidatorRewards.js
> +			assert.bnLt(postEarnedBal, initialEarnedBal);
https://github.com/Synthetixio/synthetix/pull/1647/commits/34afd173fdb4bbb33f7da07e9abd32aac9720fc6

2022-04-27 22:30 UTC, barrasso commented on test/integration/behaviors/liquidations.behavior.js
>  						);
https://github.com/Synthetixio/synthetix/pull/1647/commits/34afd173fdb4bbb33f7da07e9abd32aac9720fc6

2022-04-28 01:39 UTC, barrasso commented on test/integration/behaviors/liquidations.behavior.js
> +						assert.bnLt(await SynthetixDebtShare.balanceOf(user4.address), beforeDebt);
https://github.com/Synthetixio/synthetix/pull/1647/commits/7e9d1d23c861da261c7f103b75fc1aa4541a297e

2022-04-28 01:39 UTC, barrasso commented on test/integration/behaviors/liquidations.behavior.js
>  						);
https://github.com/Synthetixio/synthetix/pull/1647/commits/7e9d1d23c861da261c7f103b75fc1aa4541a297e

2022-04-28 08:05 UTC, barrasso commented on test/contracts/LiquidatorRewards.js
> +	describe('getReward()', () => {
https://github.com/Synthetixio/synthetix/commit/5d8824ac463f5ce92977f81a5b94ff095ead1edc

2022-04-28 08:05 UTC, barrasso commented on test/contracts/LiquidatorRewards.js
> +		it('rewards balance should increase if new rewards come in', async () => {
https://github.com/Synthetixio/synthetix/commit/5d8824ac463f5ce92977f81a5b94ff095ead1edc

2022-04-30 20:47 UTC, dbeal-eth requested changes

2022-04-30 20:47 UTC, dbeal-eth commented on test/contracts/LiquidatorRewards.js
> +		});
can we add one more compound test somewhere in this file where (for example)

1. user A mints 100 debt shares
2. user B mints 100 debt shares
3. 10 sUSD of liquidation rewards are collected after someone is liquidated
4. user A claims
5. user C mints 100 debt shares

ensure user B still has same amount of rewards as what user A claimed

its sort a similar test to the `earned()` test added previously where we ensure that other users are not affected by one user's actions (in this case, a new user coming in and increasing the `sharesSupply` should not affect already earned rewards)

2022-05-11 17:35 UTC, dbeal-eth requested changes

2022-05-11 17:35 UTC, dbeal-eth commented on contracts/BaseSynthetix.sol
> +            if (totalRedeemed > (flagReward.add(liquidateReward))) {
nit unnecessary extra parenthesis

2022-05-11 17:35 UTC, dbeal-eth commented on contracts/SystemSettingsLib.sol
> +    uint public constant MIN_LIQUIDATION_DELAY = 24 hours;
we might want to let the council set this to a lower minimum value. in severe market conditions, 6 hour liquidations seem like somethign taht could be a real option they could legit take. who are we to stop them?

2022-05-11 17:35 UTC, dbeal-eth commented on test/contracts/LiquidatorRewards.js
> +			assert.bnEqual(await liquidatorRewards.earned(stakingAccount1), ZERO_BN);
might want to add a call to `notifyRewardAmount` here to drive home that nobody can earn when there is no staking

2022-05-11 22:36 UTC, barrasso commented on contracts/SystemSettingsLib.sol
> +    uint public constant MIN_LIQUIDATION_DELAY = 24 hours;
consulted with spartan council in discord

2022-05-13 02:05 UTC, barrasso commented on contracts/BaseSynthetix.sol
> -        liquidatorRewards().getReward(account);
removed this because the rewards get escrowed anyway and didn't add much value.

plus it reset `messageSender` (bc of the approval call from within LiquidatorRewards)

2022-05-13 02:06 UTC, barrasso commented on contracts/Issuer.sol
> -
removed because the penalty is already accounted for in `calculateAmountToLiquidate`

2022-05-13 02:07 UTC, barrasso commented on contracts/Issuer.sol
> -
removed because we don't actually burn any debt (no sUSD is taken out of circulation), only debt share balance changes.

2022-05-13 05:21 UTC, dbeal-eth commented on contracts/Liquidator.sol
> +            keccak256(abi.encodePacked(_getKey(LIQUIDATION_DEADLINE, account), account))
we are double packing and hashing here (`_getKey` already doess `keccak256(abi.encodePacked())`). If we are trying to do this to get a rekey, its not necessary because `Liquidations` was renamed to `Liquidator` and that affects the final storage slot in `FlexibleStorage`.

since its unnecessary code complexity and increases gas, its recommended to revert to old code and just use flexible storage

2022-05-13 05:21 UTC, dbeal-eth commented on contracts/Liquidator.sol
> +            keccak256(abi.encodePacked(_getKey(LIQUIDATION_DEADLINE, _account), _account)),
same here

2022-05-13 05:21 UTC, dbeal-eth commented on contracts/SystemSettings.sol
> +    event FlagRewardUpdated(uint newReward);
might be good to rename these something like `LiquidationFlagRewardUpdated`

2022-05-13 05:33 UTC, dbeal-eth approved these changes

2022-05-13 05:34 UTC, merged