Optimism Forking with Hardhat
Synthetixio/synthetix pull request #1656
Opened 2022-01-21 00:35 UTC by dbeal-eth

This PR uses the newly released forking support on hardhat to run `fork` tests on optimism, as well as allowing the starting of a fork by just running `npx hardhat node --network mainnet --use-ovm`

Notes:
* I ran into an insane number of issues debugging owners for both the forked and the integration tests, so there are a lot of misc test chagnes in oredr to deal with that. Also,
* I think we should get rid of the `directRelay` test, now that we have locked the relay system and we don't need to redeploy it ever again, its just making the management of these tests much harder
* Had to change the synth for the redeemer test to `sBTC` since `sDEFI` does not exist on mainnet l2

Let me know if I missed anything else.

2022-01-21 00:48 UTC, justinjmoses requested changes

2022-01-21 00:48 UTC, justinjmoses commented on .circleci/src/jobs/job-fork-tests.yml
> +  - run:
Can we split out into two jobs - `job-fork-tests` and `job-fork-tests-ovm`? The reason `job-test-integration` isn't split out is due to the need to run the complex ops tool in the background (though frankly, now that it's using caching we should probably split these as well). This makes it easier to identify flakes and where the error is without having to open the CI job

2022-01-21 03:30 UTC, dbeal-eth commented on .circleci/src/jobs/job-fork-tests.yml
> +  - run:
good idea

2022-01-21 17:44 UTC, justinjmoses requested changes
Something is up with the merge - it's trying to undo the peacock changes to deployment.json

2022-01-21 17:44 UTC, justinjmoses commented on hardhat/tasks/task-test-integration.js
> +			if (taskArguments.useFork) {
[np] we could probably dedupe a bunch of code here as the l1 and l2 tasks are looking pretty similar but I get you want to put this PR to bed so it's just a nitpick

2022-01-21 17:44 UTC, justinjmoses commented on publish/deployed/kovan-ovm/deployment.json
> +			"address": "0x2F737bf6a32bf3AcBef4d5148DA507569204Fb61",
This is mistaken - `0x129fd2f3a799bD156e8c00599760AfC2f0f953dA` is what it should be - looks like you don't have the latest develop merged in

2022-01-21 18:40 UTC, dbeal-eth commented on hardhat/tasks/task-test-integration.js
> +			if (taskArguments.useFork) {
appreciate your understanding

2022-01-21 19:45 UTC, justinjmoses commented on hardhat/tasks/task-test-integration.js
> +				buildPath: buildPath,
[np] can just use `buildPath` here as shorthand

2022-01-21 19:45 UTC, justinjmoses commented on index.js
> +			deployer: '0x3C05B1239B223c969540FeFc0270227a2B00e047',
we use the same deployer as mainnet

2022-01-21 19:46 UTC, justinjmoses commented on test/integration/l2/directRelay.l2.integration.js
> +		describe.skip('when changing an L2 system setting with directRelay', () => {
can you just comment why you are skipping this?

2022-01-21 19:46 UTC, justinjmoses commented on test/integration/l2/directRelay.l2.integration.js
> +describe.skip('tempOwner directRelay integration tests (L2)', () => {
why not conditionally skip if fork? we do that elsewhere in a `before` block

2022-01-24 21:26 UTC, justinjmoses commented on test/integration/l2/directRelay.l2.integration.js
> +describe.skip('tempOwner directRelay integration tests (L2)', () => {
still ping on this.

2022-01-24 21:26 UTC, justinjmoses commented on test/integration/l2/directRelay.l2.integration.js
> +		describe.skip('when changing an L2 system setting with directRelay', () => {
why skip this specifically if the whole thing is skipped?

2022-01-24 21:27 UTC, justinjmoses approved these changes
Just a few comments left.

2022-01-24 23:07 UTC, dbeal-eth commented on test/integration/l2/directRelay.l2.integration.js
> +describe.skip('tempOwner directRelay integration tests (L2)', () => {
for some reason I get this error when I try to use `this.skip()` from within, like we do in other tests:

```
TypeError: this.skip is not a function
```

Maybe because the before to skip is in a top level `describe` block?

I added `this.skip()` to nested tests, lets see how that works.

2022-01-26 05:13 UTC, merged