SIP-165 Debt Orcale
Synthetixio/synthetix pull request #1694
Opened 2022-02-08 21:49 UTC by dbeal-eth

In this PR you will find impl for [SIP-165](https://sips.synthetix.io/sips/sip-165/).

From a code perspective, this entails:
* `FeePool` and `Issuer` are changed to use the chainlink oracle instead of `DebtCache` and `SynthetixDebtShare` directly
* `FeePool` now closes its fee period across networks (using optimism relay call) to allow for synchronized sharing of close parameters between networks
* Tests now use a dummy oracle `SingleNetworkAggregatorDebtInfo` to retrieve debt values for this network, meaning most unit tests can work exactly the same as before.

Notes:
* The SC has indicated that inflation should be divided evenly between networks based on amount of debt shares on each network, so this has been implemented. Also, fees will remain on the network they originate from for the time being
* Dual Integration test was added to verify fee pool closure

2022-02-11 04:07 UTC, barrasso reviewed
First pass LGTM. Some minor comments

2022-02-11 04:07 UTC, barrasso commented on test/integration/dual/staking.integration.js
> +describe('stakingt & claiming integration tests (L1, L2)', () => {
[np] typo: "stakingt"

2022-02-11 05:08 UTC, dbeal-eth commented on contracts/SingleNetworkAggregators.sol
> +contract BaseSingleNetworkAggregator is Owned, AggregatorV2V3Interface {
its not a test helper, it will be deployed and used initially until chainlink oracles are ready, or as a backup

2022-02-11 05:10 UTC, dbeal-eth commented on contracts/FeePool.sol
> +    function allNetworksSnxBackedDebt() internal view returns (uint256 debt, uint256 updatedAt) {
do you know why internal functions have underscores btw? I still have yet to figure this out...

2022-02-11 12:42 UTC, barrasso commented on contracts/FeePool.sol
> +    function allNetworksSnxBackedDebt() internal view returns (uint256 debt, uint256 updatedAt) {
It's just a naming convention for functions and variables that are supposed to be internal or private to the contract. 
Sometimes it's also used to avoid shadowing variables. 

Technically it isn't needed (unless you got a linter like solint), but it does improve readability when scanning through contracts imo.
 
Like without reading all the keywords I can quickly say: "OK, this function is internal so it's not called by anyone else."

2022-03-03 00:57 UTC, artdgn approved these changes
Various small issues and questions. 

From futures point of view, as long as `takeDebtSnapshot()` is being respected by each chain for counting the debt (and it looks like it's being respected in `Issuer._totalIssuedSynths()` by calling `debtCache().cacheInfo()`), I see no issue.

2022-03-03 00:57 UTC, artdgn commented on test/integration/dual/closeFeePeriod.integration.js
> +			it('has new fee pool', async () => {
nit: `new fee period`

2022-03-03 00:57 UTC, artdgn commented on test/integration/dual/closeFeePeriod.integration.js
> +			it('has correct params', async () => {});
would it make sense to add a sanity check that L2 debt has indeed effect on claims when closing from L1?

2022-03-03 21:40 UTC, dbeal-eth commented on contracts/FeePool.sol
> +    function allNetworksDebtSharesSupply() internal view returns (uint256 sharesSupply, uint256 updatedAt) {
reccomended to just look directly at the aggregator provided by chainlink--shortly after release, we will provide additional subgraph functionality to record the data on the aggregator

2022-03-03 21:46 UTC, dbeal-eth commented on test/contracts/BaseSynthetix.js
> +					// make aggregator debt info rate stale
its a 2 part operation, so forst we set timestamp to current time, and then it fast forwards past the stale period after that

2022-03-03 21:48 UTC, dbeal-eth commented on test/integration/dual/closeFeePeriod.integration.js
> +			it('has new fee pool', async () => {
86b41d87

2022-03-03 21:50 UTC, dbeal-eth commented on test/integration/dual/closeFeePeriod.integration.js
> +			it('has correct params', async () => {});
for now removed this empty test case. validation of fee closure routine is covered in a nother integration test

2022-03-09 15:50 UTC, dbeal-eth commented on contracts/FeePool.sol
> +        (, int256 rawIssuedSynths, , uint issuedSynthsUpdatedAt, ) = AggregatorV2V3Interface(requireAndGetAddress(CONTRACT_EXT_AGGREGATOR_ISSUED_SYNTHS))
will be impl

2022-03-10 00:34 UTC, artdgn requested changes
Two main points:
- Checking the values coming from the other oracle
- Logical error in condition check order

2022-03-10 00:34 UTC, artdgn commented on contracts/Issuer.sol
> +    // SIP-65: Decentralized circuit breaker
nit: 165

2022-03-10 00:34 UTC, artdgn commented on contracts/Issuer.sol
> +        (, int256 rawRatio, , uint ratioUpdatedAt, ) = AggregatorV2V3Interface(requireAndGetAddress(CONTRACT_EXT_AGGREGATOR_DEBT_RATIO))
should the second oracle be checked as well, them being separate contracts and possibly failing not at the same time?

2022-03-10 00:34 UTC, artdgn commented on contracts/Issuer.sol
> +    function _verifyCircuitBreaker() internal returns (bool) {
nit: return value is unclear from the name, maybe `_circuitBreakerOk`?

2022-03-10 00:34 UTC, artdgn commented on contracts/Issuer.sol
> +        } else if (fresh == 0) {
`fresh == 0` should be first condition to check, if both are 0 (fresh contract, and oracle misconfigured), deviation returned is 1.

2022-03-10 00:34 UTC, artdgn commented on test/contracts/Issuer.js
> +					await synthetix.issueSynths(toUnit('1'), { from: account1 });
nit: is this line needed?

2022-03-10 00:34 UTC, artdgn commented on test/contracts/Issuer.js
> +				it('circuit breaks when debt changes dramatically', async () => {
would be wise to check the edge cases as well
- last == 0
- fresh == 0
- fresh == 0 and last == 0 (which should fail with current code I believe)

2022-03-10 00:40 UTC, dbeal-eth commented on test/contracts/Issuer.js
> +					await synthetix.issueSynths(toUnit('1'), { from: account1 });
yes

2022-03-10 00:48 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        } else if (fresh == 0) {
oracle may return `0` if there is no debt in the system, and that is not an error. if last is not set, then we have no data to go off of, so we shouldn't break the circuit.

whats important is that the value doesn't *become* 0 during normal operation, which the next condition will successfully catch.

so, in order for this case to occur, we have to be doing a release, and the oracle has to suddenly be misconfigured. 

I think we are ok.

2022-03-10 00:51 UTC, dbeal-eth commented on contracts/Issuer.sol
> +    function _verifyCircuitBreaker() internal returns (bool) {
the function also has the side effect of triggering issuance suspension so i thought calling it an `_is` function would have worse problem.

2022-03-10 00:57 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        (, int256 rawRatio, , uint ratioUpdatedAt, ) = AggregatorV2V3Interface(requireAndGetAddress(CONTRACT_EXT_AGGREGATOR_DEBT_RATIO))
believe it or not, the second oracle (hereafter referred to as the `IssuedSynths` oracle) is not actually used to measurable extent in the `Issuer`, because if you look at the one function where `allNetworks

Also the `IssuedSynths` oracle, unlike the `DebtRatio` oracle or other price oracles, is sensitive to legitimate changes in value, where it can swing wildly in either direction if a large staker mints or burns.

Right now, the only thing the `IssuedSynths` oracle is really used for is calculating the amount of SNX to mint in `FeePool`, but that only happens once a week. If there is a mis-mint of debt, it can be corrected (since the minted supply will be sitting undistributed for most of a week)

Since both the `IssuedSynths` and `DebtRatio` are pushed by the same oracle code, if there was actually an issue that affected `IssuedSynths`, it would likely affect `DebtRatio` as well, and trigger the circuit breaker anyway, so because of all the reasons above, its been left out of the breaker check

2022-03-10 01:01 UTC, dbeal-eth commented on test/contracts/Issuer.js
> +				it('circuit breaks when debt changes dramatically', async () => {
fresh == 0 and last == 0 is actually verified as part of this test, since it would fail or trigger issuance suspension on the first `issueSynths` call.

`fresh == 0` and `last != 0` would happen if either 1) all debt was burned, or 2) the oracle is borked. in either case, we would expect it to suspend. This test can be added.

`fresh != 0` and `last == 0` only happens if the contract is uninitialized, so it has no data to go off of and shouldn't break. to test this, we would have to deploy and hook up a new Issuer in the unit test I believe

2022-03-10 01:02 UTC, dbeal-eth commented on contracts/Issuer.sol
> +    function _verifyCircuitBreaker() internal returns (bool) {
anothre option is to call it `_operateCircuitBreaker`

2022-03-10 01:13 UTC, dbeal-eth commented on contracts/Issuer.sol
> +    // SIP-65: Decentralized circuit breaker
c375a938

2022-03-10 01:14 UTC, dbeal-eth commented on test/contracts/Issuer.js
> +				it('circuit breaks when debt changes dramatically', async () => {
tightened up the tests to verify that `totalIssuedSynths` is actually 0 at the beginning of the test, and to burn all synths in the burn circuit breaker test c375a938

2022-03-10 02:00 UTC, artdgn commented on contracts/Issuer.sol
> +        } else if (fresh == 0) {
> so, in order for this case to occur, we have to be doing a release, and the oracle has to suddenly be misconfigured

Not suddenly, it might be misconfigured by the same release

> oracle may return 0 if there is no debt in the system

That's a fair point, but it only brings out a more important point - how do we tell between "oracle is broken" and "there is no debt".

2022-03-10 02:04 UTC, artdgn commented on contracts/Issuer.sol
> +        (, int256 rawRatio, , uint ratioUpdatedAt, ) = AggregatorV2V3Interface(requireAndGetAddress(CONTRACT_EXT_AGGREGATOR_DEBT_RATIO))
The deviation check might be the wrong check, but some validation still needs to be done. Surely the oracle can return bad values, and surely not every value can be a legitimate value. One possibility is to maybe to combine subtraction and division. If the diff is more that 1M and the deviation is more than 30% - break circuit. This way large values are possible when large values already exist, but large deviations for small values don't break the circuit.

2022-03-10 02:08 UTC, artdgn commented on contracts/Issuer.sol
> +        (, int256 rawRatio, , uint ratioUpdatedAt, ) = AggregatorV2V3Interface(requireAndGetAddress(CONTRACT_EXT_AGGREGATOR_DEBT_RATIO))
> Right now, the only thing the IssuedSynths oracle is really used for

and 

> Since both the IssuedSynths and DebtRatio are pushed by the same oracle code

Is IMO a combination of assumptions that might not hold true, and surely the code doesn't ensure this. This might still result in bad values returned and more trouble than adding basic validation on the numbers returned from oracle.

What is the risk / downside of adding those checks?

2022-03-10 02:12 UTC, artdgn commented on test/contracts/Issuer.js
> +				it('circuit breaks when debt changes dramatically', async () => {
> Guess what? thats tested here also (thats why other comment from earlier "Is this really needed", yes it is needed or else it fails because last == 0 still)

might be good to add a comment there explaining this gotcha to make the test maintainer's life easier

2022-03-10 02:14 UTC, artdgn commented on test/contracts/Issuer.js
> +					await synthetix.issueSynths(toUnit('1'), { from: account1 });
please a code comment to explain it (the gotcha), as I still don't get it (and I would be puzzled if I were to touch this test)

2022-03-10 14:36 UTC, barrasso commented on contracts/Issuer.sol
> +    function _verifyCircuitBreaker() internal returns (bool) {
`_checkCircuitBreaker`?  😀

OR

call it `_circuitBreakerDidSuspendIssuance` and invert the boolean values

2022-03-10 14:43 UTC, barrasso commented on contracts/Issuer.sol
> +        (, int256 rawRatio, , uint ratioUpdatedAt, ) = AggregatorV2V3Interface(requireAndGetAddress(CONTRACT_EXT_AGGREGATOR_DEBT_RATIO))
Don't see any risk in adding these checks - I also think we should have moar validation. But I do see the downside of losing time testing on kovan. Let's consider which of those checks are absolutely necessary and whip up another PR in the meantime.

2022-03-10 14:46 UTC, barrasso approved these changes
I think this is good to merge into develop and test on Kovan for now. 
Also, the auditors haven't raised any major concerns. 

We can consider additional verification checks & circuit breakers in parallel, and then create a new PR later if needed.

2022-03-10 22:48 UTC, merged