SIP-227 Synths Bridge
Synthetixio/synthetix pull request #1754
Opened 2022-04-07 03:40 UTC by dbeal-eth

Implementation for [SIP-227](https://sips.synthetix.io/sips/sip-227/)

Notes:
* chainlink has to do their end of the work to account for comparing the events on the send and receive side to ensure correct accounting of debt
* any synth can theoretically transferred from L2 to L1. However, in reality, we should probably just start with sUSD right now because other synths could have problems (ex. if synth only exists on L2 but not L1, and chainlink would have to account for the expected value of the synths in transit which makes a complicated problem even more complicated)
* Updated `BaseSynthetixBridge` so that we could keep things more symmetric and reduce code duplication.
* withdraw tests are not currently working due to them never being impl to work (this is the same with the withdraw tests that we have had the whole time)

2022-04-07 04:43 UTC, artdgn requested changes
I think permissiveness should be tightened (sUSD only, modifiers). Some more documentation might be nice.

Have not looked at the tests yet (due to requesting changes).

2022-04-07 04:43 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        issuer().issueFreeSynths(currencyKey, destination, amount);
require currencyKey sUSD?

2022-04-07 04:43 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +    event InitiateSynthTransfer(bytes32 indexed currencyKey, address indexed destination, uint256 amount);
nit: uint256 here, just uint above

2022-04-07 04:43 UTC, artdgn commented on contracts/Issuer.sol
> +                msg.sender == resolver.getAddress(CONTRACT_SYNTHETIXBRIDGETOOPTIMISM) ||
nit: one of these addresses is not set (so will be 0?), so we should check which one it is and use the other one for this condition. msg.sender cannot be 0 of course, but `require(msg.sender == address(0))` is a weird thing to have.

2022-04-07 04:43 UTC, artdgn commented on contracts/Issuer.sol
> +    function issueFreeSynths(
would be good to add documentation to these new methods. in which context they can be used and what does `Free` mean (memory, will, speech, beer, puppies?)

perhaps `issueBridgedSynths` and `burnBridgedSynths`?

2022-04-07 04:43 UTC, artdgn commented on contracts/Issuer.sol
> +    function _onlyBrokers() internal view {
I think it will be safer to create a second modifier instead of broadening this one's permissiveness.

With this code, now every one of the 3 brokers can call any one of the modifier protected methods. 

But in reality 1 broker needs to call one set of methods, and the other 2 brokers need to call another set - so separate modifiers will be more strict.

2022-04-07 04:43 UTC, artdgn commented on contracts/Issuer.sol
> +        require(address(synths[currencyKey]) != address(0), "Issuer: synth doesn't exist");
require sUSD?

2022-04-07 04:43 UTC, artdgn commented on contracts/Issuer.sol
> +        synths[currencyKey].burn(from, amount);
shoudn't this use `_burnSynths` and update all the related accounting? (circuit breaker, debt register, cached susd debt)? Should nont of the accounting be updated, even debtCache? The supply does change, so next snapshot will update it?

If this doesn't need to happen, explaining this in comments would probably be important.

2022-04-07 04:43 UTC, artdgn commented on contracts/Issuer.sol
> +        require(address(synths[currencyKey]) != address(0), "Issuer: synth doesn't exist");
require sUSD?

2022-04-07 04:43 UTC, artdgn commented on contracts/SynthetixBridgeToOptimism.sol
>          synthetixERC20().transferFrom(synthetixBridgeEscrow(), to, amount);
nit: slither complains about not checking return value, which is true. AFAIS Synthetix.transferFrom does return value, so we might as well check it here (otherwise this method assumes `transferFrom` is `safeTransferFrom` but it has no reason to assume or know that implementation detail)

2022-04-07 04:43 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        );
so what happens if the issue on the other side fails for some reason? (circuit breaking, pausing)

2022-04-07 16:40 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +    function counterpart() internal view returns (address);
if its not implemented than the compiler will fail, or if you try to construct at runtime it will fail because its an abstract contract

2022-04-07 16:40 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +            //uint32(getCrossDomainMessageGasLimit(CrossDomainMessageGasLimits.Withdrawal))
whoops, was debugging

2022-04-07 16:41 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        issuer().burnFreeSynths(currencyKey, msg.sender, amount);
not certain yet, will be determined in discussion later today. most likely it will check a systemSetting

2022-04-07 16:41 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        bytes memory messageData =
probably

2022-04-07 16:43 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        issuer().issueFreeSynths(currencyKey, destination, amount);
this function has no benefit in checking the currency key because the corresponding initiate function should be doing that check. It would only serve to increase the risk of undelivered funds.

note that the `finalize` function must have the same parameters as the `initialize` function after crossing the bridge

2022-04-07 16:44 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        require(address(synths[currencyKey]) != address(0), "Issuer: synth doesn't exist");
definitely shouldn't add it here, this function is intended to allow issuance without the corresponding debt. There would be no benefit in restricting it here because its not a multi-chain aware function

2022-04-07 16:49 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        synths[currencyKey].burn(from, amount);
* circuit breaker doesnot need to be updated because it covers an unrelated. If anything, the circuit breaker should be 
* debt register doesn't need to be updated because, by definition of the function of this function, . For example, someone with 0 staking/debt (AKA, just a "user" of the trading part of the protocol) should be able to transfer synths
* the debtCache should be updated and this will be added

2022-04-07 16:50 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        require(address(synths[currencyKey]) != address(0), "Issuer: synth doesn't exist");
no

2022-04-07 16:53 UTC, dbeal-eth commented on contracts/SynthetixBridgeToOptimism.sol
>          synthetixERC20().transferFrom(synthetixBridgeEscrow(), to, amount);
we can talk about this in the afternoon, but I would like to refrain from making changes to sensitive parts of the system like withdrawals unless we need to. Sure, its a slither warning, but we know what we have now works and even if there is a failure here it wouldn't change the overall result for the user (they still would'nt receive their funds and we could have a major problem)

2022-04-07 17:06 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        bytes memory messageData =
c621ce8b

2022-04-07 17:06 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +            //uint32(getCrossDomainMessageGasLimit(CrossDomainMessageGasLimits.Withdrawal))
c621ce8b

2022-04-07 17:07 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        synths[currencyKey].burn(from, amount);
c621ce8b

2022-04-07 17:07 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        );
c621ce8b

2022-04-11 00:10 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        issuer().burnFreeSynths(currencyKey, msg.sender, amount);
I thought only sUSD was in spec for this feature for V2X because of the added possible complications of moving volatile synths.

2022-04-11 00:11 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        issuer().issueFreeSynths(currencyKey, destination, amount);
> hould be doing that check

It's on another chain, this contract shouldn't trust that a message coming from some contract on another chain has done some checks. If it should only be minting sUSD, it should check that here as well.

2022-04-11 00:16 UTC, artdgn commented on contracts/Issuer.sol
> +        require(address(synths[currencyKey]) != address(0), "Issuer: synth doesn't exist");
If Issuer is intended to only be minting sUSD in this method, it should check that it's only sUSD, 

Even if the bridge checked it as well, these are two different contracts, and if somehow the bridge is wrong, the Issuer should do its own input validation if it can, and that check is trivial.

What is the benefit of skipping that check here?

2022-04-11 00:16 UTC, artdgn commented on contracts/Issuer.sol
> +        require(address(synths[currencyKey]) != address(0), "Issuer: synth doesn't exist");
why?

2022-04-11 00:20 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        );
I think that if the system is paused it should be paused, it shouldn't be minting due to unchecked messages from another chain. 

What if the bridge contract had a bug, and now you know it was exploited. So now when it lends on L1 - it's can't even be paused?

2022-04-11 00:46 UTC, artdgn requested changes

2022-04-11 00:46 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +    function initiateSynthTransfer(
I think the wait period for L2->L1 creates some accounting problems that make immediate burning problematic in this case.

What if e.g. half of debt is being sent to L1 (one tx, or multiple). The synths are burned, so the debt on that chain is decreased. Which now allows more minting. Which now can be sent to the bridge and burned again. And again. 

During that time, the debt is not an accurate represenation of the debt due to the burning of the synths, so allows minting more than needed for the c-ratio that was set. This possibly opens an inflation attack. Which in combination with the other chain not being able to pause the issuance (in current code), can be quite destructive.

**I think the bridge needs to hold the synths, and only burn them upon receiving an issuance confirming message from the other chain.** This way the accounting problem is for temporarily having more then debt in the system than needed, than vice versa, which is safer (due to allowing to mint less rather and more).

Maybe L1 -> L2 can be done with burning immediately (due to the speed), but even then - how do we know there isn't going to be an issue due to incorrectly accounting the debt during that short window?

Even if it's not an attack, a big enough burn will affect the accounting for the rest of the stakers: their debt will be reduced for a week, they might mint, and then the debt will jump back up when it's minted on the other side, no?

2022-04-11 00:47 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +    function initiateSynthTransfer(
Also, a lot of my comments from previous review weren't addressed yet, so these points remain unaddressed in my view.

2022-04-11 00:53 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +    function counterpart() internal view returns (address);
I don't think it's an abstract contract, we're in 0.5 still.

2022-04-11 00:55 UTC, artdgn commented on contracts/Issuer.sol
> +    function issueFreeSynths(
not a nit.

2022-04-11 22:51 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +    function initiateSynthTransfer(
> What if e.g. half of debt is being sent to L1 (one tx, or multiple). The synths are burned, so the debt on that chain is decreased (e.g. by a snapshot). Which now allows more minting. Which now can be sent to the bridge and burned again. And again.

Thats why the chainlink oracle is being updated to account for synths in transit. Read the PR description please!

> I think the bridge needs to hold the synths, and only burn them upon receiving an issuance confirming message from the other chain. This way the accounting problem is for temporarily having more then debt in the system than needed, than vice versa, which is safer (due to allowing to mint less rather and more).

Suppose we have the bridge hold the synths while they are in transit. What happens when the synth arrives on the other end and is minted? Do we have to ? Note that there remains a 15-20 minute delay for sending messages L1->L2, meaning that we haven't really accomplished anything regarding the issue you mentioned for going the other way

2022-04-11 22:58 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +    function counterpart() internal view returns (address);
> I don't think it's an abstract contract, we're in 0.5 still.

https://docs.soliditylang.org/en/v0.5.16/contracts.html?highlight=abstract#abstract-contracts

2022-04-11 23:01 UTC, justinjmoses commented on contracts/BaseSynthetixBridge.sol
> +    function counterpart() internal view returns (address);
Yeah it won't compile if we don't implement it.

2022-04-12 16:47 UTC, dbeal-eth commented
as discussed in meeting last week, the bridge has been updated to not accept parameter for  `currencyKey`. Instead, it will assume `sUSD`.

2022-04-12 17:43 UTC, justinjmoses commented on contracts/BaseSynthetixBridge.sol
> +        );
I think this function should use the modifier `requireInitiationActive` - this is what we use to disable deposits and withdrawals of SNX when we are upgrading the bridge or destination contracts, so I think it's reasonable to also have it here. That being said, whenever we suspend initiation on the bridge, it will mean that both SNX and sUSD will be disabled. I think that's just cost of doing business, so to say.

2022-04-12 17:44 UTC, justinjmoses commented on contracts/Issuer.sol
> +    function issueFreeSynths(
Agreed on a better name but not mandatory to add comments IMO - they are effectively protected internal

2022-04-12 17:46 UTC, justinjmoses commented on contracts/Issuer.sol
> +        require(address(synths[currencyKey]) != address(0), "Issuer: synth doesn't exist");
I feel this is a nitpick. The function here is protected internal - if the public function in the bridge is limited to sUSD and this function is limited to the bridge, I think it's reasonably protected. If we added requires everywhere to double and triple check inputs our code would be much bigger. I think using unit tests to check this is sufficient.

2022-04-13 01:29 UTC, artdgn commented on contracts/Issuer.sol
> +    function issueFreeSynths(
the comments are for developers looking into that code outside of the context of this PR and trying to figure out what accounting needs and doesn't need to happen here and **why** when compared to other issuing in the contract.

2022-04-13 01:32 UTC, artdgn commented on contracts/Issuer.sol
> +        require(address(synths[currencyKey]) != address(0), "Issuer: synth doesn't exist");
It is protected internal in this PR, but it's not future proof for subsequent changes. It is easy to imagine future changes that open a way for a currencyKey to be passed in not through the bridge, especially now the modifier is written in this PR (not limiting to only the bridge).

I disagree that it's a nitpick, if the Issuer from its point of view "knows" that it only mints sUSD in this method, but accepts `currencyKey` just future interface changes - it should check its inputs.

2022-04-13 20:48 UTC, justinjmoses commented on contracts/BaseSynthetixBridge.sol
> +        emit InitiateSynthTransfer(sUSD, destination, amount);
Could you also add the `uint` ID in here to help Chainlink to figure out which transfers have been finalized?

2022-04-14 06:30 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +    function initiateSynthTransfer(
Regarding the proposal for CL to track the burned / minted events. I have a variation on that, that's less dependant on harder to verify invents processing, and instead uses more easily verifiable (by external observer) contract views:

Each bridge will track and expose a view of total synths burned and minted, or even just the difference between those two sums. CL will use those views to count report the total debt in a way that will be trivial to check for someone who observes the rest of the debt values reported on both chains.

So e.g. when someone bridges L2->L1. They burn X. L2 side reports -X debt initially, L1 side reports 0. CL adds X to the rest of debt from both chains. After L1 finalises, it reports +X, L2 still reports -X - so there is no offset and CL adds 0 to the total debt.

We can even call that number something like `bridgeDebtOffset` and roll it into the number CL already uses, and this way no CL changes are required.

During migrations the offsets state should be migrated as well (just as external debt is migrated currently).

2022-04-15 00:03 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        synthTransferSent += amount;
should probably be done before calling an external contract to follow check-effects-interactions. will likely be flagged by slither and the audit

2022-04-15 00:05 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        synthTransferReceived += amount;
should probably be done before calling an external contract to follow check-effects-interactions

2022-04-15 05:28 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        emit InitiateSynthTransfer(sUSD, destination, amount);
no longer needed for chainlink, though lmk if you think we should still have it

2022-04-15 05:28 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        synthTransferSent += amount;
will be moved

2022-04-15 05:28 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        synthTransferReceived += amount;
will be moved

2022-04-15 05:29 UTC, dbeal-eth commented on contracts/Issuer.sol
> +    function _onlyBrokers() internal view {
will be changed

2022-04-15 05:34 UTC, dbeal-eth commented on contracts/Issuer.sol
> +    function issueFreeSynths(
the function need-not be associated only with the bridge (even if the bridge is currently the only caller), which is why it wasn't named as such. as for the adding of comments, I can add comments if you think its needed, but in this file only the most complicated functions or noteworthy lines have added comments. Considering the brevity and simplicity of the function, we can probably go without

2022-04-15 05:35 UTC, dbeal-eth commented on contracts/Issuer.sol
> +    function issueFreeSynths(
for naming, how does `issueSynthsWithoutDebt` sound? (and same for the corresponding `burn` function?)

2022-04-15 05:46 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        require(address(synths[currencyKey]) != address(0), "Issuer: synth doesn't exist");
> It is protected internal in this PR, but it's not future proof for subsequent changes. It is easy to imagine future changes that open a way for a currencyKey to be passed in not through the bridge, especially now the modifier is written in this PR (not limiting to only the bridge).

Can you give a specific hypothetical example of a subsequent change that could lead to unexpected complications because of the acceptance of this parameter?

> I disagree that it's a nitpick, if the Issuer from its point of view "knows" that it only mints sUSD in this method, but accepts currencyKey just for future proofing interface changes - it should check its inputs in current implementation.

I'm confused, all synths allow for `Issuer` to issue its tokens.

> Logically, the Issuer and the Bridge are different entities, and although internal (and have internal auth), they should still check their inputs without relying on implementation details knowledge of each other. Because when someone will go and change e.g. the bridge logic, they will also need to go and change the other contracts that implicitly rely on that logic, and they may forget to (and the reviewers of their PR might also forget to, and the auditors might forget to). That's why we should reduce this implicit reliance on internal knowledge of other contract's implementation if we can.

If we are creating a restritcion to only mint `sUSD` in order to match the impl of the bridge, then we are literally making an assumption within `Issuer` about how the bridge works and thereby increasing implementation complexity and hoops required if we have a case for this function to be used elsewhere

TBH, the synth contracts shouldn't be using `onlyInternalContracts` for auth. They should let the `Issuer` be the only caller for the `issue` function, and then everything calls the issuer which is much easier to upgrade and fits the implied purpose of this file by its name. But thats an issue from long ago.

2022-04-15 05:49 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        require(address(synths[currencyKey]) != address(0), "Issuer: synth doesn't exist");
henceforth, please assume all comments for the identically named `require sUSD?` comment earlier in this file now apply to this thread. apologies for my short response

2022-04-15 05:50 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +    function initiateSynthTransfer(
> Regarding the proposal for CL to track the burned / minted events. I have a variation on that, that's less dependant on harder to verify invents processing, and instead uses more easily verifiable (by external observer) contract views. It will even potentially require no changes from CL, so will be faster and easier to ship.
> 
> Each bridge will track and expose a view of total synths burned and minted, or even just the difference between those two sums. CL will use those views to report the total debt in a way that will be trivial to check for someone who observes the rest of the debt values reported on both chains.
> 
> So e.g. when someone bridges L2->L1. They burn X. L2 side reports -X debt offset initially, L1 side reports 0. CL adds X to the rest of debt from both chains. After L1 finalises, it reports +X, L2 still reports -X - so there is no offset and CL adds 0 to the total debt. When another bridging tx happens - it will update the offsets on each side at the right times when it lends on chain.
> 
> We can even call that number something like `bridgeDebtOffset` and roll it into the number CL already uses, and this way no CL changes are required.
> 
> During migrations the offsets state should be migrated as well (just as external debt is migrated currently).

this is being done now

2022-04-15 05:57 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        );
> I think that if the system is paused it should be paused, it shouldn't be minting due to unchecked messages from another chain.

after reviewing the implementation of the Synths file (https://github.com/Synthetixio/synthetix/blob/develop/contracts/Synth.sol#L167), it appears that it will allow minting or burning without checking to see if the system is paused, which is surprising. to prevent this, the `in

however, it doesn't solve the problem if one network is paused. If for example, L2 is paused, but L1 is not, how does L1 know that it can't send to L2? its not like a message could be sent to inform it. Therefore, I can think of only 2 things we can do:

1. always send the synths to the user in `finalizeSynthTransfer` even if the system is paused, which is probably the best thing to do tbh since the system being paused has little/nothing to do with the health of the bridge, and we have a separate lever to control that if need be
2. deposit any funds sent while the system was paused to a "lost funds" wallet of some sort, and manually distribute it after the system is unpaused, if necessary

however, we can't just have inaction, otherwise the synths would be lost in transit, unable to be recovered. we would probably have to refund.

2022-04-18 23:44 UTC, artdgn requested changes

2022-04-18 23:44 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +    bytes32 private constant SYNTH_TRANSFER_NAMESPACE = "SynthTransfer";
perhaps refactoring the SynthTransfer storage handling into a mixin will be nicer. It has a limited interface, and can be easier to read in a separate file

2022-04-18 23:44 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        _incrementSynthsTransferCounter(SYNTH_TRANSFER_RECV, currencyKey, amount);
this doesn't do any validation, and can mint any synth with any amount according to a message from another chain (or from another contract, that makes it think it's got it from another chain)

2022-04-18 23:44 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +            currentSynths + amount
nit? safemath

2022-04-18 23:44 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        bytes32[] memory currencyKeys = issuer().availableCurrencyKeys();
what if a synth was deprecated / not added, its values should still be summed in perpetuity for correct debt accounting of the two sides, no?

2022-04-18 23:44 UTC, artdgn commented on contracts/SystemSettingsLib.sol
> +    function setCrossSynthTransferEnabled(
nit: `setCross`**Synth**`TransferEnabled` did you mean to have `Chain` instead of `Synth`?

2022-04-18 23:44 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        require(!isInvalid, "Rates are not accurate");
nit: "invalid"

2022-04-18 23:44 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +            transferAmountKeys[i] = keccak256(abi.encodePacked(group, currencyKeys));
currencyKeys -> currencyKeys[i] ?

2022-04-18 23:44 UTC, artdgn commented on test/contracts/BaseSynthetixBridge.unit.js
> +						assert.bnEqual(flexibleStorage.smocked.setUIntValue.calls[0].value, toUnit('150'));
key should be validated as well

2022-04-18 23:44 UTC, artdgn commented on contracts/SystemSettings.sol
> +    function crossSynthTransferEnabled(bytes32 currencyKey) external view returns (uint) {
nit: crossSynth?

2022-04-18 23:58 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +    bytes32 private constant SYNTH_TRANSFER_NAMESPACE = "SynthTransfer";
the mixin is only expected to be implemented by `BaseSynthetixBridge`. Do you really think its worth the effort?

2022-04-18 23:59 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        _incrementSynthsTransferCounter(SYNTH_TRANSFER_RECV, currencyKey, amount);
what validation do you recomend? validation for message to only come from the other bridge contract is done with `onlyCounterpart`

2022-04-18 23:59 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +            currentSynths + amount
ty

2022-04-19 00:02 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        bytes32[] memory currencyKeys = issuer().availableCurrencyKeys();
if a synth is deprecated/removed from the issuer, then we could solve this problem easily by just disabling bridging and waiting for all messages to be forwarded.

2022-04-19 00:03 UTC, dbeal-eth commented on contracts/SystemSettingsLib.sol
> +    function setCrossSynthTransferEnabled(
I meant to have `Synth` as is in the code

2022-04-19 00:36 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        require(!isInvalid, "Rates are not accurate");
will fix

2022-04-19 00:36 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +            transferAmountKeys[i] = keccak256(abi.encodePacked(group, currencyKeys));
yes

2022-04-19 00:36 UTC, dbeal-eth commented on test/contracts/BaseSynthetixBridge.unit.js
> +						assert.bnEqual(flexibleStorage.smocked.setUIntValue.calls[0].value, toUnit('150'));
not quite there yet but yes needs to be done

2022-04-19 00:37 UTC, dbeal-eth commented on contracts/SystemSettings.sol
> +    function crossSynthTransferEnabled(bytes32 currencyKey) external view returns (uint) {
this is intended

2022-04-19 00:48 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +    bytes32 private constant SYNTH_TRANSFER_NAMESPACE = "SynthTransfer";
it should be pretty straightforward, just splitting it into another file. not insisting on it, but it seemed a nice way to declutter the file from the storage related activities

2022-04-19 00:51 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        _incrementSynthsTransferCounter(SYNTH_TRANSFER_RECV, currencyKey, amount);
It would be safer to control minting on the receiving side as well, at least in terms of supported currencyKeys, and later in amounts as well (rate limiting). 

So that the receiving side would have control over pausing / limiting damage in case of an issue. Right now it just does whatever the message tells it to. Feels too permissive, and no recourse for damage control / mitigation.

2022-04-19 00:56 UTC, artdgn commented on contracts/SystemSettings.sol
> +    function crossSynthTransferEnabled(bytes32 currencyKey) external view returns (uint) {
in that case the naming doesn't seem right to me.. what is a "cross synth transfer"? is it cross-chain-synth-transfer? previous `crossChainTransferEnabled(bytes32 key)` seems more clear to me

2022-04-19 00:59 UTC, artdgn commented on contracts/BaseSynthetixBridge.sol
> +        bytes32[] memory currencyKeys = issuer().availableCurrencyKeys();
should this be added into some checklist / doc that's relevant to migrations / deprecations?

2022-04-20 02:38 UTC, dbeal-eth commented on contracts/SystemSettings.sol
> +    function crossSynthTransferEnabled(bytes32 currencyKey) external view returns (uint) {
it doesn't clarify that this function only applies to synths being transferred cross chain (and ex. not SNX being transferred cross chain).

perhaps `crossChainSynthTransferEnabled`? seems like its crossing a bad threshold of wordyness

2022-04-20 02:41 UTC, dbeal-eth commented on test/contracts/BaseSynthetixBridge.unit.js
> +						assert.bnEqual(flexibleStorage.smocked.setUIntValue.calls[0].value, toUnit('150'));
FYI this test coverage has been added in the integration tests instead because its difficult to add the required tests to unit tests since the exact hash used to store the data could be built many different ways, and it is not the role of tests to verify that. only that the value has been stored and could conceivably be recovered later.

2022-04-20 02:44 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        bytes32[] memory currencyKeys = issuer().availableCurrencyKeys();
@justinjmoses how would you recommend considering this?

2022-04-20 02:46 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +            currentSynths + amount
e41306a2

2022-04-20 02:46 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        require(!isInvalid, "Rates are not accurate");
55953254

2022-04-20 02:46 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +            transferAmountKeys[i] = keccak256(abi.encodePacked(group, currencyKeys));
5b81e07c332649c2d715fb4f6bc0feb59b7de911

2022-04-20 02:46 UTC, dbeal-eth commented on test/contracts/BaseSynthetixBridge.unit.js
> +						assert.bnEqual(flexibleStorage.smocked.setUIntValue.calls[0].value, toUnit('150'));
5b81e07c332649c2d715fb4f6bc0feb59b7de911

2022-04-20 19:57 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        _incrementSynthsTransferCounter(SYNTH_TRANSFER_RECV, currencyKey, amount);
> So that the receiving side would have control over pausing / limiting damage in case of an issue. Right now it just does whatever the message tells it to. Feels too permissive, and no recourse for damage control / mitigation.

ok, what specific steps/measures can we take, besides implementing the rate limiting PR that has been under discussion? Should we keep rate limiting separate, or try and bundle it in this PR?

2022-04-28 07:27 UTC, kylriley commented on contracts/BaseSynthetixBridge.sol
> +        );
Worth mentioning that Optimism has [replay](https://github.com/ethereum-optimism/optimism/blob/2493e925ecff69ec352aa1a43471033ceb03a1a6/packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol#L231) / [relay](https://github.com/ethereum-optimism/optimism/blob/2493e925ecff69ec352aa1a43471033ceb03a1a6/packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol#L165) functions that can be used to resubmit failed cross-chain txs. 

If L1 => L2 fails on L2 `l1.replay()` can be used to resubmit the tx through to L2.
If L2 => L1 fails on L1 `l1.relay()` can be used to manually submit the L2 tx on L1.

Would need to have some condition on the front-end that determines when this is necessary, but it should be able to provide the user a mechanism for retrieving any lost synths.

2022-04-28 11:13 UTC, kylriley commented on contracts/BaseSynthetixBridge.sol
> +        );
@dbeal-eth my concern with (1.) would be more around automated triggers (i.e. debt / price circuit breaker), where you don't have time to trigger `initiationActive` beforehand. If funds are moving around it could make triaging / correcting the problem harder.

2022-05-05 01:50 UTC, barrasso reviewed
added comments to existing discussions and some small nits

2022-05-05 01:50 UTC, barrasso commented on contracts/BaseSynthetixBridge.sol
> +        _incrementSynthsTransferCounter(SYNTH_TRANSFER_RECV, currencyKey, amount);
some potential ideas for additional validation checks here:

- limit this functionality to only work with a single synth (i.e. `sUSD`) to reduce attack surface area
- add another modifier (e.g. `requireFinalizationActive`) that could be invoked on the receive side if some issue arises
  - this is kinda mentioned in your comment above (2.) where the in-flight funds that fail on the receiving side due to this pausing mechanism are recorded somehow and can be manually reconciled afterwards
- add a configurable variable that limits the amount of synths that can be sent/received
  - e.g. `maxSynthTransferAmount` (which can be tapered off and eventually set to `0` once the general purpose rate limiters are implemented)
  - or some `cooldown` variable (similar to burn lock) that allows for transfers only once per configurable time period ... this can also be tapered off and eventually set to `0` once the rate limiters are implemented
  - These setter variables can be internal to the bridge and set by owner (they don't have to live in SystemSettings so we can save some gas)

2022-05-05 01:50 UTC, barrasso commented on contracts/BaseSynthetixBridge.sol
> +        bytes32[] memory currencyKeys = issuer().availableCurrencyKeys();
Won't this get exponentially more costly as we continue to add more and more synths? And what if we end up only using this bridge for a couple synths? Do we really have demand for enabling ALL synths to be transferable?

imo, we can significantly cut down the complexity here and make it only work with `sUSD` 

otherwise, we should only enable synths that have a high probability of never getting removed/deprecated (e.g. `sETH`, `sBTC`)

2022-05-05 01:50 UTC, barrasso commented on contracts/SystemSettings.sol
> +    function crossSynthTransferEnabled(bytes32 currencyKey) external view returns (uint) {
nit: gonna have to agree with Arthur on naming convention here... 

Using `crossChainTransferEnabled(bytes32 key)` or `crossChainSynthTransferEnabled` seems more intuitive than the current `crossSynthTransferEnabled`

2022-05-05 01:50 UTC, barrasso commented on hardhat.config.js
> -		retries: 3,
np: unsure if this is supposed to be here

2022-05-05 01:50 UTC, barrasso commented on test/contracts/BaseSynthetixBridge.unit.js
> +				'initiateSynthTransfer',
np: related to naming convention for the setting

If the setting is indeed changed to something `crossChainSynthTransferEnabled`, maybe it makes sense to also rename these to be more explicit and match accordingly:
- `initiateCrossChainSynthTransfer`
- `finalizeCrossChainSynthTransfer`

Just looking at the function names as they are now-- there's no indication that these synth transfers are "cross chain"

2022-05-05 01:50 UTC, barrasso commented on test/contracts/BaseSynthetixBridge.unit.js
> +
could also add some tests here to verify that if a circuit breaker is tripped or the system is suspended in some way while synths are in-flight to L2, they are still finalized or handled as expected

2022-05-05 04:30 UTC, dbeal-eth commented on test/contracts/BaseSynthetixBridge.unit.js
> +
good idea

2022-05-05 04:31 UTC, dbeal-eth commented on test/contracts/BaseSynthetixBridge.unit.js
> +				'initiateSynthTransfer',
its on the bridge contract... shouldn't the name be corresponding with existing functions? other cross-transfer functions on the bridges aren't called "depositCrossChain" or "migrateEscrowCrossChain" so it seems reasonable for `initiateSynthTransfer` to be the name here as well

2022-05-05 04:36 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        bytes32[] memory currencyKeys = issuer().availableCurrencyKeys();
cost is not a concern here because the function is only expected to be called by the oracle (and there really is any value to call on chain because the data is useless in isolation)

"exponentially more costly" no, only linearly. This function could probably easily support 100 synths before hitting the gas limit and failing read-only call

in v3 similar calculations will be segmented by the investments of a fund, so we will not have to worry about similar functions becoming

2022-05-05 05:06 UTC, dbeal-eth commented on test/contracts/BaseSynthetixBridge.unit.js
> +
actually, we can't test that in this file because the unit test doesn't have the real Issuer or SystemStatus.

will do it in the integration

2022-05-05 05:09 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +    function synthTransferReceived() public view returns (uint) {
0e97a0b0

2022-05-05 05:10 UTC, dbeal-eth commented on hardhat.config.js
> -		retries: 3,
0e97a0b0

2022-05-05 05:10 UTC, dbeal-eth commented on contracts/SystemSettings.sol
> +    function crossSynthTransferEnabled(bytes32 currencyKey) external view returns (uint) {
0e97a0b0

2022-05-05 21:15 UTC, dbeal-eth commented on contracts/BaseSynthetixBridge.sol
> +        _incrementSynthsTransferCounter(SYNTH_TRANSFER_RECV, currencyKey, amount);
we have to be really careful adding checks to the finalization function that could cause the transfer to fail in legitimate cases because recovery of lost funds is be difficult.

alternatively, we could set up some sort of a "impound box" which stores synths which have been rejected but can be unlocked by owner, but that raises other questions about, ex. what to do about debt (does it get included or not, both of which could be an attack vector on their own?), 

> limit this functionality to only work with a single synth (i.e. sUSD) to reduce attack surface area

SIP officially says to support any synth that is enabled

> add another modifier (e.g. requireFinalizationActive) that could be invoked on the receive side if some issue arises 

we could do that, but its redundant when we could just suspend synth transfers using the existing system status facility. Also this could be majorly impacted by the rejected transfer issue listed above

> add a configurable variable that limits the amount of synths that can be sent/received 

we have another SIP for that (or at least its a planned SIP). also, an attacker could still likely exploit this by just minting SNX on L2 instead, or unlocking SNX on L1, which is currently unlimited

also
* `maxTransferAmount` alone wouldn't stop an attacker from sending multiple large transfers at the same time
* `cooldown` would be the ideal way to go, but then we are basically implementing the rate limiting SIP. also, the cooldown/rate limiting would have to be enforced on the `initiate` side, because enforcement on the receiving side could result in failed receive transfers if ex. the finalize calls are delayed and then submitted in a batch (same issue listed first) 
* also `cooldown` has a problem where a large synth holder could prevent other, synth holders from sending. the user could continuously send transfers from L1 -> L2 and L2 -> L1 and almost completely block the pipe for everyone else. we could make this limit on a per address basis... oh wait.

2022-05-06 01:44 UTC, barrasso approved these changes

2022-05-10 01:14 UTC, merged