Perps changes batch 1
Synthetixio/synthetix pull request #1780
Opened 2022-05-12 02:34 UTC by artdgn

Some small changes to the contracts:
- better view for liquidation price and liquidation fee
- better views for iterating over position ids (number of positions, mapping of position to address)
- positions id persistance through closing / liquidting a position
- contract name getters

2022-05-17 08:48 UTC, artdgn commented
btw, fork-tests are failing because AP & DYDX markets are paused although according to config they shouldn't be, and there's no automated choice for that situation in the deploy script (it asks for a decision).

2022-05-19 14:14 UTC, barrasso requested changes

2022-05-19 14:14 UTC, barrasso commented on contracts/FuturesMarketManager.sol
> +    function payFee(uint amount, bytes32 trackingCode) external onlyMarkets {
perhaps rename this to something else in order to differentiate it from the futures v1 `payFee` function below.

e.g. `payFeeWithTracking`?

2022-05-19 14:14 UTC, barrasso commented on contracts/PerpsV2MarketBase.sol
> +            // this will check system activbe, exchange active, futures active
[np] typo `activbe` => `active`

2022-05-20 00:21 UTC, artdgn commented on contracts/PerpsV2Settings.sol
> +    function maxSingleSideValueUSD(bytes32 _marketKey) public view returns (uint) {
yeah good point, not sure why these views are public

2022-05-20 00:22 UTC, artdgn commented on contracts/PerpsV2Settings.sol
> +        require(_baseFee <= 1e18, "taker fee greater than 1");
yep, missed when renaming stuff

2022-05-20 00:25 UTC, artdgn commented on contracts/FuturesMarketManager.sol
> +    function payFee(uint amount, bytes32 trackingCode) external onlyMarkets {
I think the v1 method will be removed with v1 stuff after the migration, so I think it makes more sense to have the default method called just `payFee` and always expect a tracking code as part of its interface (and it's up to the caller to pass a 0).

2022-05-20 19:42 UTC, barrasso approved these changes

2022-05-24 16:58 UTC, merged