fix kovan futures: add axs feed, remove luna mkt
Synthetixio/synthetix pull request #1786
Opened 2022-05-19 10:58 UTC by artdgn

Futures summary views were broken because feeds were not added for AXS and LUNA.

Changes in config:
- add feed for AXS into feeds json
- remove LUNA from markets json

Changes on chain:
- add feed for AXS to rates contract
- remove LUNA market from futures manager

2022-05-19 12:53 UTC, barrasso requested changes

2022-05-19 12:53 UTC, barrasso commented on publish/deployed/kovan-ovm/futures-markets.json
> -		"asset": "LUNA",
Why are we removing LUNA from the `futures-markets.json` instead of adding the missing feed to `kovan-ovm/feeds.json`?

2022-05-20 00:17 UTC, artdgn commented on publish/deployed/kovan-ovm/futures-markets.json
> -		"asset": "LUNA",
I assumed that it might have invalid / paused feed again in the future (since it was delisted and CL paused feeds for it already previously), and might get forked etc etc...  so I thought that we probably don't want / need to really deal with that.

I guess on testnet we might as well have it and see how things break..  

So I can add it back. What would you prefer?

2022-05-20 00:38 UTC, artdgn commented on publish/deployed/kovan-ovm/futures-markets.json
> -		"asset": "LUNA",
Also CL removed it from mainnet-opti feeds (pretty sure it was there previously) and only left it on kovan, which is possibly a sign of future deprecation there as well (https://docs.chain.link/docs/optimism-price-feeds/)

2022-05-20 19:39 UTC, barrasso commented on publish/deployed/kovan-ovm/futures-markets.json
> -		"asset": "LUNA",
Let's keep LUNA removed 👍

2022-05-20 19:40 UTC, barrasso approved these changes

2022-05-20 19:40 UTC, merged