SIP-240: Update Liquidate Amount
Synthetixio/synthetix pull request #1787
Opened 2022-05-20 19:43 UTC by barrasso

2022-05-20 19:53 UTC, dbeal-eth requested changes

2022-05-20 19:53 UTC, dbeal-eth commented on contracts/Issuer.sol
> +            amountToLiquidate = debtBalance.multiplyDecimal(SafeDecimalMath.unit().add(penalty));
This line should be 

`amountToLiquidate = amountToLiquidate.multiplyDecimal(transferableBalance).divideDecimal(collateralForAccount)`

There are a couple other ways the calc could be done.

2022-05-20 21:03 UTC, barrasso commented on contracts/Issuer.sol
> +            amountToLiquidate = debtBalance.multiplyDecimal(SafeDecimalMath.unit().add(penalty));
resolved

2022-06-01 05:00 UTC, artdgn approved these changes

2022-06-01 06:13 UTC, bachstatter commented
When we calculate `totalRedeemed` on line 710 in `Issuer.sol` we add the penalty.
But doesn't `amountToLiquidate` from `liquidator().calculateAmountToFixCollateral` already have the penalty added?

2022-06-07 23:06 UTC, dbeal-eth approved these changes

2022-06-08 18:31 UTC, merged