(alt) SIP-243: Upgrade Collateral Short
Synthetixio/synthetix pull request #1793
Opened 2022-05-28 20:32 UTC by ajsantander

2022-05-29 21:42 UTC, ajsantander commented on contracts/Collateral.sol
> -
Moved this function further down, so that it is right next to `_repayWithCollateral`.

2022-05-29 21:45 UTC, ajsantander commented on contracts/Collateral.sol
> +        }
This doesn't make any sense, so I commented it out and made it to revert if collapseFeeRate is ever not zero. This feature should not only be re-implemented but re-thought. If it doesn't make sense by design, this should be cleaned up, and the setting also removed entirely.

2022-05-29 21:46 UTC, ajsantander commented on contracts/Collateral.sol
> +        payment = _processPayment(loan, payment);
`_processPayment` now returns the payment that was actually used to reduce debt (`loan.amount`).

2022-05-29 21:47 UTC, ajsantander commented on contracts/Collateral.sol
> +        Loan storage loan = _getLoanAndAccrueInterest(id, borrower);
Notice the introduction of `_getLoanAndAccrueInterest` here.

2022-05-29 21:48 UTC, ajsantander commented on contracts/Issuer.sol
>          require(amount > 0, "Issuer: cannot burn 0 synths");
This function is no longer one time only, so that further stuck sUSD can be purged in the legacy contract.
Notice how we need to add `CollateralShortLegacy` to the AddressResolver.

2022-05-29 21:49 UTC, ajsantander commented on test/contracts/CollateralShort.js
> +				// TODO: what about fees paid when the loan accrues interest?
This is something I really don't like about these tests, none consider accrued interest.

2022-05-30 10:30 UTC, leomassazza commented on contracts/Collateral.sol
>          require(payment <= loan.amount.add(loan.accruedInterest), "Payment too high");
This require changed. I don't know the implicances (if it solved something you find out, or will introduce an issue). Before, the payment included the accruedInterest, so it could be reduced to 
require(payment <= loan.amount, "Payment too high");
to get the same result as before. (and even save some gas)

2022-05-30 10:51 UTC, ajsantander commented on contracts/Collateral.sol
>          require(payment <= loan.amount.add(loan.accruedInterest), "Payment too high");
Are you referring to this (currently in develop)?
https://github.com/Synthetixio/synthetix/blob/develop/contracts/Collateral.sol#L538

2022-06-01 04:33 UTC, artdgn commented on contracts/Issuer.sol
> +        require(short == resolver.getAddress("CollateralShortLegacy"), "Issuer: wrong short address");
nit: address(0) will pass this check if the `CollateralShortLegacy` address in resolver is not set

2022-06-01 10:40 UTC, leomassazza requested changes

2022-06-01 11:08 UTC, artdgn commented on contracts/Collateral.sol
> +        emit LoanRepaymentMade(borrower, borrower, id, principal, loan.amount);
> here the intention (per my understanding) was that the informed amount in the event is the actual re-payment made after paying the interests.

I see 3 issues with this interpretation:
- there seems to be no other way for a UI / subgraph / dune dashboard to know how much was repaid including interest since `LoanRepaymentMade` is the only event for repayment and only this value is emitted
- in `LoanClosedByRepayment` the same name of the field (`amountRepaid`) is used for the the whole `payment` returned from this method
- might not be the intuitive interpretation of `amountRepaid` externally

My guess is that originally that field was intended for the whole repayment including the interest

2022-06-01 11:24 UTC, artdgn commented on contracts/MixinSystemSettings.sol
> -    function getCollapseFeeRate(address collateral) internal view returns (uint) {
it should be fine to leave both the mixin and SystemSettings unchanged (with this unused getter and setter), it will actually save deploying the contract + lib (and state bloat for the chain :smile: ) and I don't think there's any harm in it.

Maybe add a `TODO` comment to remove these next time the contracts need to be redeployed.

2022-06-01 14:42 UTC, ajsantander commented on contracts/Issuer.sol
> +        require(short == resolver.getAddress("CollateralShortLegacy"), "Issuer: wrong short address");
@leomassazza should we add tests for this function?

2022-06-01 14:44 UTC, ajsantander commented on contracts/MixinSystemSettings.sol
> -    function getCollapseFeeRate(address collateral) internal view returns (uint) {
Ok, good point! Checking if we should revert this change.

2022-06-01 14:52 UTC, ajsantander commented on contracts/SystemSettingsLib.sol
> -    function setCollapseFeeRate(
We wouldn't need to include it if we keep the setting (even though unused) in SystemSettings right?

2022-06-01 15:01 UTC, ajsantander commented on contracts/MixinSystemSettings.sol
> -    function getCollapseFeeRate(address collateral) internal view returns (uint) {
Agreed, bringing the setting back even though it will remain unused.

2022-06-01 19:35 UTC, barrasso commented on contracts/Collateral.sol
> +        uint collateralToRemove = paymentSUSD.add(exchangeFee);
Done

2022-06-01 19:36 UTC, barrasso commented on contracts/SystemSettingsLib.sol
> -    function setCollapseFeeRate(
Reverted the setting removal

2022-06-01 19:36 UTC, barrasso commented on contracts/Issuer.sol
> +        require(short == resolver.getAddress("CollateralShortLegacy"), "Issuer: wrong short address");
added

2022-06-01 19:38 UTC, leomassazza commented on contracts/Issuer.sol
> +        require(short == resolver.getAddress("CollateralShortLegacy"), "Issuer: wrong short address");
Added

2022-06-01 19:39 UTC, leomassazza commented on contracts/Issuer.sol
> +        require(short == resolver.getAddress("CollateralShortLegacy"), "Issuer: wrong short address");
Added

2022-06-02 05:52 UTC, artdgn commented on contracts/Collateral.sol
>          loan.lastInteraction = block.timestamp;
So what I meant is that `loan.lastInteraction` update is not done in `_liquidate()` which means that subsequent interactions will not be blocked by the `interactionDelay` logic. 

In the code I couldn't see if it was intentional or not (no comment there about this), but it seems to make some sense since it looks like a penalty is applied (30%) which means that it probably can't be used for front-running (due to the heavy penalty).

So now I don't think it's a concern, but I wanted to raise this so that someone who's more on top of the code can confirm that it's intentional and is ok, and if so maybe add a comment there like:
```solidity
// lastInteraction is not updated during liquidation to allow partially liquidated users to fix their loans
// without being blocked due to interactionDelay. This should not be exploitable for frontrunning due
// to the heavy penalty applied in `_collateralUtil().liquidationAmount()`
```

2022-06-02 05:53 UTC, artdgn commented on contracts/Collateral.sol
>          loan.lastInteraction = block.timestamp;
this is now a **nit**

2022-06-02 05:57 UTC, artdgn approved these changes

2022-06-02 07:02 UTC, artdgn commented on publish/releases.json
> +			"sources": ["CollateralShort, Issuer"]
looks like shorts exist on L1 too, why is the SIP only for L2?

2022-06-02 15:44 UTC, merged

2022-06-02 15:51 UTC, barrasso commented on publish/releases.json
> +			"sources": ["CollateralShort, Issuer"]
this release only affects the L2 instance of `CollateralShort`

L1 has another older instance of `CollateralShort` that doesn't have the *WithCollateral functions