SIP-230 circuit breakers
Synthetixio/synthetix pull request #1813
Opened 2022-06-13 15:36 UTC by dbeal-eth

Implements [SIP-230](https://sips.synthetix.io/sips/sip-230/)

notes:
* circuit breaker will now operate separately from `SystemStatus`. This is documented in the SIP, but just wanted to make doubly sure its noted here
* Circuit breaker does not have a "backup" of checking previous oracle prices for when its in warmup period.
* some tests were removed because the functionality is no longer relevant or the cases were covered elsewhere
* integration tests may still be failing, I am working on figuring out what is going on

2022-06-14 01:43 UTC, artdgn requested changes
Haven't had the chance for a full review but please avoid updating the futures markets contracts in any way (only the settings / manager contract can be changed - but will need to be redeployed). And yes, I saw you mentioned this would be ok in your description, I disagree.

We should not make changes to the sources to make them different from deployed contracts if they're not going to be redeployed, because this means the tests test different contracts from what's deployed.

Please also avoid updating the `Perps` contracts (because they're being refactored and it will just cause merge conflicts), assume they function as the `Futures` ones. When this is merged I will ensure Perps will use the new contract and interface before deployment.

2022-06-14 17:36 UTC, dbeal-eth commented
> We should not make changes to the sources to make them different from deployed contracts if they're not going to be redeployed, because this means the tests test different contracts from what's deployed.

makes sense

> Please also avoid updating the Perps contracts (because they're being refactored and it will just cause merge conflicts), assume they function as the Futures ones. When this is merged I will ensure Perps will use the new contract and interface before deployment.

would you prefer if the changes be put into a separate branch for the time being? want to make sure its obvious what the intended changes would be based on the new circuit breaker

2022-07-01 06:56 UTC, artdgn commented
> would you prefer if the changes be put into a separate branch for the time being? want to make sure its obvious what the intended changes would be based on the new circuit breaker

I think it will be simplest to leave them alone for the time being (in the context of this PR). If the old interface is supported, by the time we reach the review stage of PerpsV2 before their actual deployed, SIP-230 should be merged already and even if we forget to update the new interface, it would just be pointed out in review and fixed (and if it would be still forgotted, most of Perps V2 would have upgradable logic, so would be easy to fix even if somehow everyone forgets about it still).

And we'll need to maintain the previous interface for as long FuturesV1 lives, which will probably be for some time at least even after V2 is live.

2022-07-01 06:56 UTC, artdgn commented
> would you prefer if the changes be put into a separate branch for the time being? want to make sure its obvious what the intended changes would be based on the new circuit breaker

I think it will be simplest to leave them alone for the time being (in the context of this PR). If the old interface is supported, by the time we reach the review stage of PerpsV2 before their actual deployed, SIP-230 should be merged already and even if we forget to update the new interface, it would just be pointed out in review and fixed (and if it would be still forgotted, most of Perps V2 would have upgradable logic, so would be easy to fix even if somehow everyone forgets about it still).

And we'll need to maintain the previous interface for as long FuturesV1 lives, which will probably be for some time at least even after V2 is live.

2022-07-04 02:24 UTC, artdgn requested changes
Mostly nits. Two main issues (other than the previous request for not touching futures/perps contracts for now):
- `ExchangeCircuitBreaker` wasn't touched, but I think it should be refactored to use the new `CircuitBreaker` so that there aren't two caching locations (one is used by `exchange` and the other one used by futures-v1). Having two caching location means that there are two separate breakers, and we probably should avoid that and have all flows use the same contract (for the logic itself).
- `resetLastValue` comment about not getting values from owner.

2022-07-04 02:24 UTC, artdgn commented on contracts/Issuer.sol
> +        newAddresses[13] = CONTRACT_SYSTEMSTATUS;
nit: slither says the `systemStatus` getter (and the contract in resolver setup) can be removed

2022-07-04 02:24 UTC, artdgn commented on contracts/OneNetAggregatorDebtRatio.sol
> +                ? 1000000000000000000000000000
why was it 0 before, and now is 1?

also please refactor as constant (and probably better to set the constant using 10**27 for clarity (and to prevent every reviewer from counting 27 zeros :)

2022-07-04 02:24 UTC, artdgn commented on contracts/CircuitBreaker.sol
> +    function probeCircuitBreaker(address oracleAddress, uint value) external onlyProbers returns (bool circuitBroken) {
nit: please require oracleAddress not zero. 

Previously the caching was done for aggregators (that couldn't be zero), now this contract only operates on addresses so should do its own minimal validation in the mutative method

2022-07-05 18:29 UTC, dbeal-eth commented on contracts/CircuitBreaker.sol
> +    function resetLastValue(address[] calldata oracleAddresses, uint[] calldata values) external onlyOwner {
the idea of adding this extra parameter is so that the owner has a chance to confirm what they think the last value should be when setting the price oracle, in case when the call is executed (ex. the pdao prepares the transaction and when it executes a couple hours later the oracle is misbehaving again) the oracle price shifts out of range again the circuit remains broken. If car insurance companies are to be believed, an oracle that misbehaves once has a statistically higher chance of misbehaving again, sort of mentality.

If the value is erroneously set incorrectly by the owner, then the circuit will remain paused and the owner will have to figure out what the problem is

2022-07-05 18:30 UTC, dbeal-eth commented on contracts/CircuitBreaker.sol
> +        return factor >= getPriceDeviationThresholdFactor();
good idea

2022-07-05 18:39 UTC, dbeal-eth commented
thanks @artdgn please assume any comments I have not replied to will be addressed with a corresponding suggested change

2022-07-05 18:41 UTC, dbeal-eth commented on contracts/OneNetAggregatorDebtRatio.sol
> +                ? 1000000000000000000000000000
its 1 now because, after some exploration of the reasoning behind having it 0 vs 1 before and editing the tests for this PR, it makes more sense to have it as 1 because `0` will inevitably cause unnecessary divide by 0 issues when the system has no debt, and if the system goes from having no debt to having debt, the first ratio will be `1e27`, so it preserves continuity in that regard

will fix the 0s. Didnt know the `**` syntax was supported in soldiity, that is nice.

good way to see why the change is made is to just change it back and see what breaks in the tests

its an edge case that doesn't really affect the existing system

2022-07-05 18:56 UTC, dbeal-eth commented on contracts/CircuitBreaker.sol
> +    function resetLastValue(address[] calldata oracleAddresses, uint[] calldata values) external onlyOwner {
also the owner can specify `value = 0` if they want to opt out of this functionality

2022-07-05 19:01 UTC, dbeal-eth commented on contracts/CircuitBreaker.sol
> +            msg.sender == requireAndGetAddress(CONTRACT_ISSUER) || msg.sender == requireAndGetAddress(CONTRACT_EXRATES),
which is more important, saving gas for stakers, or saving gas for exchangers? historically, people have often complained that minting/burning costs too much gas, but afaik people don't complain about gas when exchanging (probably because most of them are dolphins or bigger and aren't bothered by more expense gas). that is the reasoning behind this ordering, though if I'm wrong about that please lmk

2022-07-05 19:08 UTC, dbeal-eth commented on contracts/CircuitBreaker.sol
> +        return factor >= getPriceDeviationThresholdFactor();
actually, since `priceDeviationThresholdFactor` has already been in `SystemSettings` all this time, I don't really its worth it to move the function now. The amount of gas saved might be ~10k units per probe, which comes out about less than $2 on mainnet at current ETH/gas prices, and it increases the amount of code changes and testing for this PR

2022-07-05 23:09 UTC, dbeal-eth commented on contracts/ExchangeRates.sol
> +            _rateIsStaleWithTime(getRateStalePeriod(), rateAndTime.time) ||
e6f9905a

2022-07-05 23:09 UTC, dbeal-eth commented on contracts/ExchangeRates.sol
> +        bool broken = circuitBreaker().probeCircuitBreaker(address(aggregators[currencyKey]), rateAndTime.rate);
e6f9905a

2022-07-14 04:11 UTC, artdgn commented on contracts/CircuitBreaker.sol
> +            msg.sender == requireAndGetAddress(CONTRACT_ISSUER) || msg.sender == requireAndGetAddress(CONTRACT_EXRATES),
actually it's not a call, so doesn't really save much either way (just an SLOAD and not a CALL)

2022-07-14 04:13 UTC, artdgn commented on contracts/CircuitBreaker.sol
> +        return factor >= getPriceDeviationThresholdFactor();
I still think it's a simple change that will improve gas on literally every kind of transaction on L1. It doesn't looks like it requires complex testing, just a getter an setter with access control.

2022-07-14 04:23 UTC, artdgn requested changes
Thanks for addressing many of the things in the last review. One last important bit that I think you didn't address was the first point in https://github.com/Synthetixio/synthetix/pull/1813#pullrequestreview-1026928324 about refactoring current `ExchangeCircuitBreaker` (that will still be used by futures markets) to use the new circuit breaker, so that we don't have two separate breakers, but only one (and the old one will be proxying to the new one).

2022-07-15 02:15 UTC, dbeal-eth commented
> Thanks for addressing many of the things in the last review. One last important bit that I think you didn't address was the first point in [#1813 (review)](https://github.com/Synthetixio/synthetix/pull/1813#pullrequestreview-1026928324) about refactoring current `ExchangeCircuitBreaker` (that will still be used by futures markets) to use the new circuit breaker, so that we don't have two separate breakers, but only one (and the old one will be proxying to the new one).

@artdgn sorry I think I missed that comment or something. That sounds like a good idea, I will see about updating `ExchangeCircuitBreaker` as you suggest

2022-07-20 06:51 UTC, artdgn approved these changes

2022-07-20 06:51 UTC, artdgn commented on contracts/CircuitBreaker.sol
> +import "hardhat/console.sol";
whoops

2022-07-28 22:16 UTC, dbeal-eth commented on contracts/ExchangeRates.sol
> +    }
we cant do anything about this

2022-07-28 22:17 UTC, dbeal-eth commented on contracts/CircuitBreaker.sol
> +    uint internal _numCircuitsBroken = 0;
im confused

2022-08-10 14:53 UTC, merged