Escrow liquidation
Synthetixio/synthetix pull request #1825
Opened 2022-06-20 12:26 UTC by artdgn

2022-06-29 03:01 UTC, leomassazza commented on contracts/Issuer.sol
> +            uint escrowToLiquidate
Update function documentation to reflect changes in return values

2022-06-29 03:20 UTC, leomassazza commented on contracts/BaseSynthetix.sol
> +    bytes32 private constant CONTRACT_REWARDESCROWV2 = "RewardEscrowV2";
np: other contracts refers to this contract constant as CONTRACT_REWARDESCROW_V2

2022-06-29 03:34 UTC, leomassazza commented on contracts/BaseSynthetix.sol
> +        bool success = _transferByProxy(liquidatedAccount, address(liquidatorRewards()), totalRedeemed);
np: use same success variable name here and in line 384

2022-06-29 04:26 UTC, artdgn commented on contracts/BaseSynthetix.sol
> +        bool success = _transferByProxy(liquidatedAccount, address(liquidatorRewards()), totalRedeemed);
only one transfer in this scope, so naming it `liquidatorRewardTransferSucceeded` seems less readable to me

2022-06-29 15:13 UTC, leomassazza commented on contracts/BaseSynthetix.sol
> +        bool success = _transferByProxy(liquidatedAccount, address(liquidatorRewards()), totalRedeemed);
makes sense. Thanks

2022-06-29 23:08 UTC, dbeal-eth reviewed
looking good so far :+1: 

also, on the PR description could you post the latest example statistics/link for liquidation of one account with N number of escrow entries

this review is only half done. will provide other half of review tomorrow or something.

2022-06-29 23:08 UTC, dbeal-eth commented on contracts/RewardEscrowV2Storage.sol
> +
though this function would be unused, would be good to have a `setVestingEntry(address account, uint index, VestingEntries.VestingEntry calldata entry)` function as a escape hatch in case any future contract changes are conceived and the existing write functions that are provided are not sufficient for whatever reason.

I know technically its possible to do something like that with `addVestingEntry` and `setEntryZeroAmount`, but being able to update entries slots directly could be both more convenient and have gas benefits.

2022-06-29 23:08 UTC, dbeal-eth commented on publish/releases.json
> +      "sip": 251,
np interesting tab?

2022-06-30 03:03 UTC, artdgn commented on contracts/BaseRewardEscrowV2.sol
> +    function balanceOf(address account) public view returns (uint) {
not new, it was part of previous contract too (and is used in tests for convenience)

2022-06-30 03:04 UTC, artdgn commented on contracts/BaseRewardEscrowV2.sol
> +        VestingEntries.VestingEntry memory entry;
minute gas savings

2022-06-30 03:05 UTC, artdgn commented on contracts/BaseRewardEscrowV2.sol
> +        VestingEntries.VestingEntry memory entry;
same as above, no reason to redeclare variables every iteration

2022-06-30 03:16 UTC, artdgn commented on contracts/BaseRewardEscrowV2.sol
> +        (uint total, uint endIndex, uint lastEntryTime) = state().setZerosUntilTarget(account, startIndex, targetAmount);
I think the current name is narrow and specific, and something like `revokeEntries` implies that it also takes care of the aggregate accounting (total escrow amount) by handling all state related to revoking, which it doesn't. It only sets zeros until some target sum is reached, and everything else need to be handled outside of it.

[It can also be imagined to be used for more gas efficient vesting (if entry times are monotonic) or consolidating entries (e.g. before bridging / merging).]

2022-06-30 03:22 UTC, artdgn commented on contracts/BaseRewardEscrowV2.sol
> +        emit Revoked(account, recipient, targetAmount, startIndex, endIndex);
`Vested` doesn't seem to be per entry though, only for the total amount, and the total amount here is not really vested. 

Do you think we should consider the revoked amount vested? Not sure myself really.

2022-06-30 03:29 UTC, artdgn commented on contracts/BaseRewardEscrowV2.sol
> +    event Revoked(address indexed account, address indexed recipient, uint targetAmount, uint startIndex, uint endIndex);
Emitting one per entry would mean (other than extra gas) emitting the events in `setZerosUntilTarget`. That whole contract is not emitting any events (and if we start emitting there, we'd need to add events for all write methods for consistency).

The `targetAmount` and `account` make this event at least somewhat informative for accounting purposes.

Do you have any particular concerns or suggestions for this other then one event per entry?

2022-06-30 03:33 UTC, artdgn commented on contracts/BaseSynthetix.sol
> +    function migrateEscrowContractBalance() external onlyOwner {
It either needs to remain there, or if it is removed, the migration script needs to be removed as well (and escrow will be assumed to not be upgradable). Right now the migration script is written allowing additional upgrades of RewardEscrowV2 (and it is removed from non-upgradable).

2022-06-30 03:36 UTC, artdgn commented on contracts/BaseSynthetix.sol
> +        address to = resolver.requireAndGetAddress("RewardEscrowV2", "New escrow address unset");
yes, but it will read from cache so another thing to possibly get wrong.

actually probably a good idea to require them being different addresses here.

2022-06-30 05:53 UTC, artdgn commented on contracts/RewardEscrowV2Storage.sol
> +
> I know technically its possible to do something like that with addVestingEntry and setEntryZeroAmount, but being able to update entries slots directly could be both more convenient and have gas benefits.

The reason entries were updated in place instead of being appended as in every other place in migrateAccount code is why ~~we can't have nice things~~ the gas costs are so high for current implementation. I think it's actually better to not allow this in the future, and setting an entry to zero, and append new ones should be sufficient for any scenario IMO. Can' think of a scenario that wouldn't be possible with this.

> in case any future contract changes are conceived and the existing write functions that are provided are not sufficient for whatever reason

I think this is a valid concern in general though, and I think it's worth to think through any other state changes that might be required but the current write methods don't allow (I think editing a specific entry is covered by zero & append though).

2022-06-30 05:57 UTC, artdgn commented on publish/releases.json
> +      "sip": 251,
used github UI for merge conflict resolution :disappointed:

2022-06-30 05:58 UTC, artdgn commented on contracts/BaseSynthetix.sol
> +    function liquidateDelinquentAccountEscrowIndex(address account, uint escrowStartIndex)
nit, right?

2022-07-01 00:15 UTC, artdgn commented on contracts/Issuer.sol
> +    function synthetixERC20() internal view returns (IERC20) {
A lot of changes in `Issuer` are not related to the functionality, but were needed to reduce contract size (to allow space for the new changes)

2022-07-01 01:48 UTC, dbeal-eth commented on contracts/BaseRewardEscrowV2.sol
> +        (uint total, uint endIndex, uint lastEntryTime) = state().setZerosUntilTarget(account, startIndex, targetAmount);
`setZerosUntilTarget` makes the function sound more low level than it actually is. maybe instead call it `setEntryZeroAmountsUntilTarget` to make it clear this is sort of an range-capable wrapper around `setEntryZeroAmount` function. Alternately rename `setEntryZeroAmount` to be `setZeros`

2022-07-01 01:55 UTC, dbeal-eth commented on contracts/BaseRewardEscrowV2.sol
> +        VestingEntries.VestingEntry memory entry;
i suspected that was the reason but most modern compilers are smart enough to optimize for declarations inside loops. Not sure if that means solidity compiler would actually optimize this, but even if it doesn't, the gas savings here would be almost negligible and it adds additional changes to a already long/detailed PR. The little things add up.

Since the change is already made its probably not worth it to change it back, but as I was reading through the PR it didn't seem to have any purpose related to the problem we are trying to solve so I figured I would verify.

2022-07-01 01:56 UTC, dbeal-eth commented on contracts/BaseRewardEscrowV2.sol
> +        emit Revoked(account, recipient, targetAmount, startIndex, endIndex);
in discord discussion it was decided that an additional `Vested` event is not necessary.

2022-07-01 03:23 UTC, artdgn commented on contracts/BaseRewardEscrowV2.sol
> +        state().updateEscrowAccountBalance(account, int(quantity));
this will use SafeCast

2022-07-01 03:45 UTC, artdgn commented on contracts/BaseSynthetix.sol
> +        address liquidatorAccount = messageSender;
the usage of `messageSender` will be moved into the caller (which has the `optionalProxy` modifier)

2022-07-01 05:54 UTC, artdgn commented on publish/src/commands/deploy/deploy-core.js
> +	const tokenStateSynthetix = await deployer.deployContract({
this was moved but has no significance (was moved for a step that is no longer part of the PR)

2022-07-01 06:27 UTC, artdgn commented
To prevent confusion due to new commits I'm adding new commits in https://github.com/Synthetixio/synthetix/pull/1834 (so once you're done reviewing this PR, you can review the added changes there, and possible resolve some duplicate comments here if there are any)

2022-07-04 00:52 UTC, artdgn commented on contracts/BaseRewardEscrowV2.sol
> +    event Revoked(address indexed account, address indexed recipient, uint targetAmount, uint startIndex, uint endIndex);
resolved in discord discussion

2022-07-04 01:02 UTC, artdgn commented on contracts/BaseRewardEscrowV2.sol
> +        (uint total, uint endIndex, uint lastEntryTime) = state().setZerosUntilTarget(account, startIndex, targetAmount);
will rename to `setZeroAmount` and `setZeroAmountUntilTarget` so that they are named similarly

2022-07-05 18:04 UTC, dbeal-eth commented on test/contracts/Liquidator.js
> +							describe('last escrow entry remainder is added as new entry', () => {
since this functionality is in `RewardEscrow` maybe move this test case over to `RewardEscrow` tests?

2022-07-05 18:08 UTC, dbeal-eth commented on test/contracts/RewardEscrowV2Storage.js
> +	describe('public mutative methods on frozen contract', async () => {
unless this was changed later I believe we have these tests on integration as well, probably not necessary or useful to have the tests in unit because they don't get as accurate of a picture of the actual deployed chain state

2022-07-05 18:18 UTC, dbeal-eth commented on test/contracts/Liquidator.js
> +									assert.bnEqual(debtAfter, 0);
also cant remember as I was reading through, but do we have a test verifying that `liquidationAmounts` returns 0 after any of these liquidation operations is completed?

2022-07-05 18:21 UTC, dbeal-eth commented
also in `Liquidation.js` we should probably some specific tests for `liquidationAmounts` verifying it returns expected amounts in edge cases like no liquidatable amount (aka positive c-ratio)

2022-07-06 15:52 UTC, barrasso requested changes
overall contracts and tests look good - just had some minor feedback and nits

2022-07-06 15:52 UTC, barrasso commented on contracts/Issuer.sol
> +            if (collateralForAccount == totalRedeemed) {
Perhaps I'm being overly cautious here-- but is it worth considering the case where `totalRedeemed` is somehow not **exactly equal** to `collateralForAccount` and returns something slightly greater (i.e. by 1-2 wei)?  

e.g. due to a rounding error 

Or does this not matter since `collateralForAccount` will always be `>=` to `totalRedeemed` (when taking into account the unliquidatable collateral that's sitting in legacy `SynthetixEscrow` or `LiquidatorRewards`)?

2022-07-06 15:52 UTC, barrasso commented on contracts/Liquidator.sol
> +        uint balance = issuer().collateral(account);
Shouldn't this be checking only for *liquidateable* collateral, not *all* collateral?

e.g. `synthetix.balanceOf() + rewardEscrowV2().balanceOf()`

2022-07-06 15:52 UTC, barrasso commented on contracts/Liquidator.sol
>          return balance > (getLiquidateReward().add(getFlagReward()));
Side note:
I would consider removing this function `_hasEnoughSNX` altogether. 
This was added in SIP-148 mostly because it didn't make sense for liquidators to worry about insolvent accounts with such small amounts of SNX or escrow-only accounts. Now that escrow is liquidateable, it might not make sense to have this extra check.

Also, there's another problem with it:
  * you can flag an account via `flagAccountForLiquidation` even if `_hasEnoughSNX` returns `false`
  * after they are flagged, they cannot be liquidated since `isLiquidationOpen` will return `false`
  
 So flaggable, but unliquidateable accounts with small amounts of SNX will accumulate--  and this will become more of a problem if the reward values are raised in the future.

2022-07-06 15:52 UTC, barrasso commented on contracts/RewardEscrowV2.sol
> -    event MigratedAccountEscrow(address indexed account, uint escrowedAmount, uint vestedAmount, uint time);
The `systemActive` modifier is unused. 
If this is intended, it could be removed-- along with `systemStatus()`.

2022-07-06 15:52 UTC, barrasso commented on test/integration/behaviors/liquidations.behavior.js
> +				assert.bnEqual(amountLiquidated.toString(), beforeDebtBalance.toString()); // the variance is due to a rounding error as a result of multiplication of the SNX rate
can remove this comment

2022-07-06 17:21 UTC, ajsantander commented on contracts/BaseRewardEscrowV2.sol
> +    }
As slither is suggesting here, should we make these external? I see no internal reference to nextEntryId() from within this contract.

2022-07-08 01:52 UTC, artdgn commented on publish/src/commands/deploy/configure-reward-escrow.js
> +	await runStep({
I'll add the check, and this should address the gas consideration.

2022-07-08 04:08 UTC, artdgn commented on test/contracts/Liquidator.js
> +				});
The test checks that `"escrow balance is not used for self-liquidation"` by adding entries, triggering `liquidateSelf` and checking that escrow is untauched.

The revert is a precaution and can only be triggered if a bug is deployed in Liquidator somehow (in which case liquidator will ask Synthetix to liquidate from escrow, but Synthetix will revert, preventing it).

It's possible to trigger this by mocking a bad response from Liquidator, but I think it's not needed, as this precaution revert implementation is simple enough to verify, and cannot be triggered by any user input (I can think of).

2022-07-08 04:15 UTC, artdgn commented on test/contracts/Liquidator.js
> +									assert.bnEqual(debtAfter, 0);
will add a post-action check as well

2022-07-08 04:21 UTC, artdgn commented on test/contracts/Liquidator.js
> +							describe('last escrow entry remainder is added as new entry', () => {
the remainder functionality for `revokeFrom` is tested there as well (in `'should revoke and transfer SNX to recipient for partial amount'`)

so it might be a bit redundant, but it might be considered also a liquidation side effect, so might as well leave it here too.

2022-07-08 04:23 UTC, artdgn commented on test/contracts/RewardEscrowV2Storage.js
> +	describe('public mutative methods on frozen contract', async () => {
This depends on functionality that should work in the unit tests as well (the inability to transfer using synthetix impl) because is part of the contract code (and not the contract state). It's one more place that might check a regression if this is changed in a way that breaks this assumtion.

2022-07-08 05:06 UTC, artdgn commented on contracts/Issuer.sol
> +            if (collateralForAccount == totalRedeemed) {
it shouldn't be possible to be in this condition, and I'm hesitant to change `==` to `<=` just because no rounding is taking place.

I think it would make sense to add a require to check for this if this was a value being passed from another contract. However, `totalRedeemed` is a result of the internal method `_redeemableCollateralForTarget` and it seems overkill to check the result of `<= collateralForAccount` in the same contract.

2022-07-08 05:26 UTC, artdgn commented on contracts/Liquidator.sol
> +        uint balance = issuer().collateral(account);
will add another view to Issuer for `liquidatableCollateral` (don't think `Liquidator` should have internal knowledge of that calculation)

2022-07-08 05:33 UTC, artdgn commented on contracts/Liquidator.sol
>          return balance > (getLiquidateReward().add(getFlagReward()));
I think the check does make some sense (if the reward is a constant amount), otherwise the liquidation tx cannot succeed. 

Wouldn't adding this check during `flagAccountForLiquidation` make this behavior consistent?

2022-07-08 05:48 UTC, artdgn commented on test/integration/behaviors/liquidations.behavior.js
> +				assert.bnEqual(amountLiquidated.toString(), beforeDebtBalance.toString()); // the variance is due to a rounding error as a result of multiplication of the SNX rate
what do you mean? this is still a "close" comparison and not an exact comparison because of the `.toString()` (which truncates). There some issue with bnClose in integration tests (that's why it's used).

2022-07-08 17:53 UTC, barrasso commented on contracts/Liquidator.sol
>          return balance > (getLiquidateReward().add(getFlagReward()));
> otherwise the liquidation tx cannot succeed.

Where exactly would the tx fail? 
I was thinking that this case should be handled in the `else` block at L393 in `BaseSynthetix`:

```
  /* If the total amount of redeemed SNX is greater than zero 
  but is less than the sum of the flag & liquidate rewards,
  then just send all of the SNX to the LiquidatorRewards contract. */
  stakerRewards = totalRedeemed;
  ```
  
The liquidator doesn't get any flat reward for doing this, but it at least goes to stakers in the form of LiquidatorRewards.
It also cleans up small dust SNX that is stuck in inactive accounts. Let's say there are 10,000 accounts each with balanceOf 1-2 SNX... (which actually looks like is the case on Optimism already). That's already a decent amount of SNX that can't be liquidated and is just sitting until the reward threshold drops. And those rewards will likely never be <1 (*unless SNX moons to $2,192 and is altered by SCCP*).

2022-07-11 02:58 UTC, artdgn commented on contracts/Liquidator.sol
>          return balance > (getLiquidateReward().add(getFlagReward()));
Discussion continued in https://github.com/Synthetixio/synthetix/pull/1834#discussion_r917489876

2022-07-11 16:35 UTC, ajsantander commented on contracts/BaseRewardEscrowV2.sol
> +            endIndex = numVestingEntries(account);
nit: avoid a call in the case the if statement body block is accessed by saving numVestingEntries to the stack

2022-07-11 17:28 UTC, ajsantander requested changes
I see quite a bit of semantic overloading around the determination of wether a vesting entry is held in the old escrow contract or in the new one. Sometimes `entry.endTime == 0` is used, sometimes `entryId < fallbackCount`, and sometimes `amount = 0` (with the use of the `ZERO_PLACEHOLDER = -1`.

I call "semantic overloading" whenever you use a variable for more things that it's supposed to. E.g. `_totalEscrowedAccountBalance` should hold a balance, and only a balance, not an additional indicator (-1) pointing to where the value is stored.

As a developer, specially as a smart contract developer, one may be tempted to use semantic overloading for runtime optimization. My view regarding this is to always prioritize security over performance. Semantic overloading introduces points of fragility in the code, where one may forget assumptions in different parts of the code.

Even if the developer that introduces the overloads is smart enough to not make mistakes with them, code reviewers will find it harder to understand the code, and thus get lost in technicalities instead of detecting issues. Additionally, developers working in the code in the future are quite likely to make mistakes.

My suggestion for this PR then is to remove semantic overloading, and use explicit variables for understanding when values should be read from the old contract, and when from the new contract.

2022-07-12 14:46 UTC, ajsantander approved these changes

2022-08-09 10:38 UTC, leomassazza commented on contracts/RewardEscrowV2Storage.sol
> +    int internal constant ZERO_PLACEHOLDER = -1;
This is confusing and prone to errors. And the fact that there are two helper functions to read/write using the ZERO_PLACEHOLDER, those functions can be used to inspect an actual flag. 
Also, while looking at the helper function, the result is still an int (that can be negative), so -1 can be a valid value (from typing reading).

using a flag the complexity of the `_readWithZeroPlaceholder(int v)` is reduced to a transparent reading since the uninitialized flag is not artificially introduced in the value (the reading function it's replacing a -1 for a 0 and again, being the return type an int, -1 can be a valid number)

2022-08-09 10:55 UTC, leomassazza commented on contracts/BaseSynthetix.sol
> +            entryID = rewardEscrowV2().accountVestingEntryIDs(account, i);
I see those two functions are called together (same pattern) a couple of times. Here it implies two calls. 

You can add a single function that internally calls both to minimize the number of interactions.

2022-08-09 11:14 UTC, leomassazza commented on contracts/Issuer.sol
> +        return
This now will revert if synthetixEscrow, rewardEscrowV2 or liquidatorRewards are not set, but I assume that will be seen easily at deployment time tests.

2022-08-09 11:29 UTC, leomassazza commented on contracts/MintableSynthetix.sol
> +pragma experimental ABIEncoderV2;
why do we have the pragma here?

2022-08-10 01:46 UTC, artdgn commented on contracts/MintableSynthetix.sol
> +pragma experimental ABIEncoderV2;
because of the use of `VestingEntries.VestingEntry` struct used in `BaseSynthetix` for `getFirstNonZeroEscrowIndex`

2022-08-10 01:49 UTC, artdgn commented on contracts/Issuer.sol
> +        return
This was previously the case as well because the checks in previous code would always be true. E.g. `address(synthetixEscrow()) != address(0) is always true because `synthetixEscrow()` uses `requireAndGetAddress` which requires it to not be 0.

This change is removing redundant code to reduce contract size (to be able to fit the other code).

2022-08-10 01:55 UTC, artdgn commented on contracts/BaseSynthetix.sol
> +            entryID = rewardEscrowV2().accountVestingEntryIDs(account, i);
They are used in external calls only once, in this view method, which is expected to be called offline mostly.

Adding a convenience method doesn't really make sense since it adds contract code, and testing surface area, and won't really save much gas.

2022-08-10 03:08 UTC, artdgn commented on contracts/RewardEscrowV2Storage.sol
> +    int internal constant ZERO_PLACEHOLDER = -1;
>  uninitialized flag

Yes this issue was also raised by @ajsantander, I've explored a version with explicit flags (for all other cases of placeholders as well, which is almost all state variables) in https://github.com/Synthetixio/synthetix/pull/1838 and raised the issue to the auditors as well for their considerations.

In the end, that alternative code becomes prone to errors as well (because now you have to read and write two state variables for each state, and each value in an array), you have to both read and write them in sync, and handle and test possible mis-matches or misreads of the values. It adds gas costs, so leads to additional gas optimisations which lead to more complexity. It's also hard to read and reason about (but in a different way).

These value placeholders aren't super comfy in my view either, but even after implementing an alternative it didn't seem better. Also, no one was strongly in favour of that alternative version either (auditors or otherwise), so the more reviewed and simpler version remained.

> or change the helpers to return a uint and cast the result so

I'll move the casting around :+1:

2022-08-10 11:10 UTC, leomassazza commented on test/integration/behaviors/liquidations.behavior.js
> +					let cratioBefore;
rename to beforeCRatio as the other before*

2022-08-10 11:12 UTC, leomassazza commented on test/integration/behaviors/liquidations.behavior.js
> +					let collateralBefore;
dito: beforeCRatio

2022-08-10 11:20 UTC, leomassazza commented on test/contracts/RewardEscrowV2Storage.js
> +	// const WEEK = 7 * 86400;
np: delete commented out line

2022-08-10 11:25 UTC, leomassazza commented on test/contracts/RewardEscrowV2.js
>  		it('then numVestingEntries should return 0', async () => {
Comment says 0 and should be 2

2022-08-10 11:25 UTC, leomassazza commented on test/contracts/RewardEscrowV2.js
>  	describe('There are no escrow entries initially', async () => {
Fix comment. Expected 2 entries and not zero (no escrow entries)

2022-08-10 11:32 UTC, leomassazza approved these changes
Approved with some minor np in the tests. I marked as resolved the previous conversations you addressed.

2022-08-10 23:04 UTC, artdgn commented on test/integration/behaviors/liquidations.behavior.js
> +					let collateralBefore;
this one is actually used as name implies it seems

2022-08-17 14:11 UTC, barrasso approved these changes

2022-08-18 22:15 UTC, merged