SIP-258 fix rate direction in ExchangeRatesWithDexPricing
Synthetixio/synthetix pull request #1835
Opened 2022-07-08 05:30 UTC by dbeal-eth

`ExchangeRatesWithDexPricing` was processing all dex exchange rate
queries in the same direction, creating unfavorable fills in unlikely circumstances on atomic swaps.

This change will ensure trade direction is taken into account while
computing rates.

Implements [SIP-258](https://sips.synthetix.io/sips/sip-258/)

2022-07-08 07:49 UTC, artdgn requested changes
- I think there are tests only for sUSD trades (sUSD->sETH, and reverse). Should probably include a (sBTC -> sETH).
- using sourceAmount for destination rate calculation

2022-07-08 07:49 UTC, artdgn commented on contracts/ExchangeRatesWithDexPricing.sol
> +                _getPriceFromDexAggregator(sUSD, destinationCurrencyKey, sourceAmount)
Passing `sourceAmount` here makes not sense since this is a destination rate calculation, right?

I think this means that passing the amount into this method (and then `_dexPriceDestinationValue`) makes no sense in general, since it doesn't matter which amount is used, because it's just factored out anyway and the **rate** is returned. OR if external oracle somehow is using amount for liquidity based calculation (which I don't think it does) we need to pass a different amount here (because sourceAmount is incorrect if source currency is not sUSD).

Would probably be less confusing to remove the amount passing, and use an arbitrary amount for the oracle call.

2022-07-08 07:49 UTC, artdgn commented on contracts/ExchangeRatesWithDexPricing.sol
> +    /// @dev One of `sourceCurrencyKey` or `destCurrencyKey` should be sUSD. There are two parameters to indicate directionality. Because this function returns "price", if the source is sUSD, the res
this seems confusing, I think it would be less confusing to pass the non-sUSD currencyKey, and a flag of whether it is source or destination.

2022-07-08 07:49 UTC, artdgn commented on contracts/ExchangeRatesWithDexPricing.sol
> +        return destCurrencyKey == "sUSD" ? result : SafeDecimalMath.unit().divideDecimalRound(result);
nit: I think you already have `sUSD` constant in scope

2022-07-08 18:23 UTC, dbeal-eth commented on contracts/ExchangeRatesWithDexPricing.sol
> +                _getPriceFromDexAggregator(sUSD, destinationCurrencyKey, sourceAmount)
just trying to make the minimum changes to fix this issue which is why the `sourceAmount` argument was not removed

2022-07-08 18:27 UTC, dbeal-eth commented on contracts/ExchangeRatesWithDexPricing.sol
> +    /// @dev One of `sourceCurrencyKey` or `destCurrencyKey` should be sUSD. There are two parameters to indicate directionality. Because this function returns "price", if the source is sUSD, the res
booleans are opaque at the location of the function call as to what they indicate and don't follow the pattern used on other parts of the repo (almost every other function in Exchanger/ExchangeRates uses `sourceCurrencyKey, destCurrencyKey` for args). it is confusing that the function returns `price` instead of a `rate`, so I can understand ify ou wanted that changed, but would like more opinions on this because I would consider this exactly the opposite (ie, that using a boolean is more confusing/harder to track than argument ordering)

2022-07-08 18:30 UTC, dbeal-eth commented
> Looks like the SIP link is dead? Also, do we have a test that passes here and fails on `develop`?

yes I recall there are about 10 tests failing if the solidity code was checked into `develop`. The reason for the failure is because the mock dex aggregator has the wrong assumption about the behavior of aggregator when flipping input tokens (this can be verified by just using the on-chain aggregator and observing the result).

we should probably add another test to verify trade going the other direction as arthur mentioned, but the ticket is still in draft so give me a little more time :smile:

2022-07-08 18:33 UTC, dbeal-eth commented on contracts/ExchangeRatesWithDexPricing.sol
> +        return destCurrencyKey == "sUSD" ? result : SafeDecimalMath.unit().divideDecimalRound(result);
whoops

2022-07-10 17:15 UTC, kaleb-keny commented on contracts/ExchangeRatesWithDexPricing.sol
> +                _getPriceFromDexAggregator(sUSD, destinationCurrencyKey, sourceAmount)
the fixes look fine to me, as long as `_getPriceFromDexAggregator` gets the min return amount, which i assume it does

2022-07-10 17:17 UTC, kaleb-keny commented
> Looks like the SIP link is dead? Also, do we have a test that passes here and fails on `develop`?

hey SIP-258 has now been merged, waiting for afif review, but seems to be in line with db's proposed here. Just one thing, need to redeploy `DexPriceAggregatorUniswapV3` with default fee of 5 bp and see if that works... In order to be able to hop over the 5 bp btc/eth & eth/usdc pools

2022-07-26 21:43 UTC, merged