SIP-257: update ExchangeRates to handle up to 27 decimals
Synthetixio/synthetix pull request #1844
Opened 2022-07-21 02:35 UTC by artdgn

https://sips.synthetix.io/sips/sip-257/

https://github.com/synthetixio/project-management/issues/362

2022-07-25 15:09 UTC, barrasso requested changes
LGTM, just one comment on deployment layer

2022-07-25 15:09 UTC, barrasso commented on publish/releases.json
> +			"layer": "both",
Should consider releasing to `"layer": "ovm"` instead since:
* the SIP explicitly states that `Network: Optimism` 
* the intended purpose is to enable a futures market only available on L2

2022-08-01 00:55 UTC, artdgn commented on publish/releases.json
> +			"layer": "both",
Functionally it is only needed for optimism, but releasing it only there will create a divergence between source and deployed for mainnet which is probably a bad idea.

Also, when the next change will happen in this contract (e.g. 230) it will be released to mainnet anyway, since we won't create two versions of it.

You're right about the SIP, although it is mainly about the new added market (which is only on optimism), but the Rates contracts change is technically (due to above reasons) only possible for both layers.

2022-08-01 05:26 UTC, artdgn commented on publish/releases.json
> +			"layer": "both",
Updating the SIP: https://github.com/Synthetixio/SIPs/pull/1143

2022-08-01 15:20 UTC, barrasso approved these changes

2022-08-08 14:23 UTC, merged