impersonate the deployer using cannon
Synthetixio/synthetix pull request #1854
Opened 2022-07-30 03:35 UTC by dbeal-eth

this will allow for prototype testing on real forked network without
needing any keys or anything.

here is a command to fork mainnet. Any SIPs configured for an unreleased
release in `publish/releases.json` will be deployed

```
npx hardhat cannon:build --file cannonfile.release.toml --network mainnet --dry-run network=mainnet --impersonate --fund-signers --port 8545
```

once we feel more comfortable with the process we might want to add some
convenience `npm` commands to make bringin up these environments easier
so the command doesn't have to be as long

2022-07-30 20:03 UTC, kaleb-keny approved these changes

2022-07-31 08:47 UTC, kaleb-keny approved these changes

2022-08-01 15:10 UTC, barrasso requested changes
need to revert deployment.json changes

2022-08-01 15:10 UTC, barrasso commented on publish/deployed/local-ovm/deployment.json
>  			"source": "SafeDecimalMath",
why are there `local-ovm/deployment.json` changes? shouldn't this be empty?

2022-08-01 15:10 UTC, barrasso commented on publish/deployed/mainnet/deployment.json
> -			"address": "0xb4dc5ced63C2918c89E491D19BF1C0e92845de7C",
I think these mainnet deployment files were accidentally committed

2022-08-01 15:16 UTC, barrasso commented on publish/releases.json
> -			"sips": []
also should revert this change as it is in `staging` and not yet in develop

2022-08-01 22:23 UTC, barrasso approved these changes

2022-08-01 22:23 UTC, merged