Liquidators QoL
Synthetixio/synthetix pull request #1881
Opened 2022-08-23 13:52 UTC by leomassazza

Ref: https://www.notion.so/Liquidations-QoL-077c9cedfb934ee8b167279ed45ffa02

2022-08-27 05:20 UTC, bachstatter commented on contracts/PerpsEngineV2ViewsMixin.sol
> +    function canLiquidate(bytes32 marketKey, address[] calldata accounts)
😍

2022-08-29 01:58 UTC, artdgn requested changes
Some small notes. Also if you can add some context into the PR description in addition to the notion link, since notion is not openly accessible, and it would be nice to provide some minimal context for PRs for anyone without that access.

2022-08-29 01:58 UTC, artdgn commented on contracts/PerpsEngineV2Base.sol
> +    /// Reverts if any account should not be liquidated.
this comment line is incorrect I think (it won't revert)

2022-08-29 01:58 UTC, artdgn commented on contracts/PerpsEngineV2Base.sol
> +    function liquidatePosition(bytes32 marketKey, address account) external {
I think this method should be part of orders router, since 1. that's the contract that handles msg.sender auth for other orders, and 2. is technically just a convenience method, so shouldn't clutter the engine interface and contract.

I think the tests you've added for this can be just moved to the order tests as well.

2022-08-29 01:58 UTC, artdgn commented on contracts/PerpsEngineV2Base.sol
> +    ) internal returns (bool) {
maybe this now needs a rename to `_tryLiquidatePosition` or something to be clear that it only may do the action, and the result should be checked

2022-08-29 01:58 UTC, artdgn commented on contracts/PerpsEngineV2ViewsMixin.sol
> +            liquidatables[i] = !isInvalid && _canLiquidate(position, price);
can probably skip the loop entirely if `isInvalid` is true

2022-08-29 01:58 UTC, artdgn commented on contracts/PerpsEngineV2ViewsMixin.sol
> +    /// view that returns an array of bools indication for each account if can be liquidated
should mention that invalidity is rolled in to the resulting bools

2022-08-29 01:58 UTC, artdgn commented on contracts/PerpsOrdersV2Base.sol
> +    function canLiquidate(bytes32 marketKey, address[] calldata accounts) external view returns (bool[] memory) {
coverage complains about this view. 

I think it's not needed really, because the single account `canLiquidate` is returned in `positionSummary` and for the batch view, they would use the engine anyway, because that's where the batch liquidation method is.

2022-08-29 01:58 UTC, artdgn commented on test/contracts/PerpsEngineV2.js
> +				await instance.liquidatePositions(marketKey, [trader], liquidator);
any idea what happened to the diff here, these test cases seem to already exist, but are shown as new here :thinking:

2022-08-29 11:56 UTC, davidvuong commented on contracts/PerpsEngineV2Base.sol
> +    /// backwards compatible liquidatePositon where a single position is liquidated by msg.sender
Minor: Typo in `liquidatePositon`.

2022-08-29 11:56 UTC, davidvuong commented on contracts/PerpsEngineV2ViewsMixin.sol
> +            liquidatables[i] = !isInvalid && _canLiquidate(position, price);
Q & Nit: There's generally an inconsistent use of the `is` prefix to denote booleans throughout the project (see: `tooVolatile` but `isInvalid` and `invalid` mixed). What is the convention? `isXXX` is how I've always named my variables, web3 or otherwise.

2022-08-29 11:56 UTC, davidvuong commented on contracts/PerpsEngineV2Base.sol
> +        liquidated = new bool[](accounts.length);
Q: Is it generally accepted to simply noop on mutative calls when user input results in a pointless invocation (as opposed to reverting)? In our case, return an empty array when input `accounts.length == 0`?

2022-08-31 01:59 UTC, artdgn commented on contracts/PerpsEngineV2Base.sol
> +        liquidated = new bool[](accounts.length);
I think it makes sense to revert in this particular case (length 0). Although a no-op can still happen in this method if no account is actually liquidatable, but it seems reasonable.

2022-11-16 16:09 UTC, leomassazza commented
To be moved to PerpsV2 / V3

2022-11-16 16:09 UTC, closed without merging