Feature/shortcut methods
Synthetixio/synthetix pull request #1882
Opened 2022-08-24 05:47 UTC by davidvuong

2022-08-25 02:44 UTC, artdgn requested changes

2022-08-25 02:44 UTC, artdgn commented on contracts/PerpsOrdersV2Base.sol
> +        _engineInternal().transferMargin(marketKey, msg.sender, marginDelta);
nit: another option was to make `transferMargin` public and call it instead.

2022-08-25 02:44 UTC, artdgn commented on contracts/PerpsOrdersV2Base.sol
> +    function tradeAndTransfer(
I think that `closeAndWithdraw` might be a good convenience method to add here as well, since `tradeAndTransfer` requires caller to know how much to withdraw, but `closeAndWithdraw` can just `closePosition` and then `withdrawMaxMargin` cleanly and simply closing everything.

2022-08-25 02:44 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +				const fee = (await perpsOrders.orderFee(marketKey, size, [baseFee, 0, toBytes32('')])).fee;
that's weird, what's that third argument struct to `orderFee`?

2022-08-25 02:44 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +				assert.bnEqual(position.margin, margin.sub(fee), 'Margin does not match expected');
good idea to check those views before the tx as well

2022-08-25 02:44 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +				const [fee] = await executeTransferAndTradeWithFee(margin, size);
would be good to check the events are as expected (at least order of events) in at least one of those tests

2022-08-25 02:44 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +				assert.equal(position.id, '1');
nit: any particular reason this might be important?

2022-08-25 02:44 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +				await assert.revert(
revert checks should always specify the expected message (or a distinct part of it)

2022-08-25 02:44 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +			it('should revert when size exceed max leverage on transferred margin', async () => {
instead of this one I'd check with an existing position that withdrawing (negative marginDelta) and than trading reverts

2022-08-25 02:44 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +				const withdrawableMargin = await perpsEngine.withdrawableMargin(marketKey, trader);
this test can be stronger since withdrawable margin **after** the trade should be larger, I don't think what you're doing here withdraws all margin (because you call `withdrawableMargin` with an open position)

2022-08-25 02:44 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +				assert.equal(updatedPosition.size, '0');
can check margin is close to 0 (or if you calculate it right with fees, exactly 0).

2022-08-25 05:29 UTC, davidvuong commented on test/contracts/PerpsOrdersV2.js
> +				assert.equal(position.id, '1');
It just confirms the position was initialised correctly and since it's the first position, the id is 1. However, can be omitted if not necessary.

2022-08-26 05:57 UTC, artdgn requested changes

2022-08-26 05:57 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +				assert.bnEqual(position1.margin, '0', '(before) Margin does not match expected');
nit: the context messages are nice, but aren't really used much elsewhere (seem kinda cluttery as opposed to an inline comment about the assertions block)

2022-08-26 05:57 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +					decodedLogs.map(log => log?.name).filter(name => !!name),
this filter is hiding events that also should be checked as they are part of the expected system flow (events from `perpsStorage` about position init, funding, etc)

2022-08-26 05:57 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +				// There will be more margin to withdraw after the position is closed.
you can use `simulateTrade` view on `perpsEngine` to get the exact expected trade results (sorry for realizing this now and not in the previous review when I was commenting on this)

2022-08-26 06:26 UTC, davidvuong commented on test/contracts/PerpsOrdersV2.js
> +				assert.bnEqual(position1.margin, '0', '(before) Margin does not match expected');
I was going off the pseudo types provided in jsdoc comments. `context`, the 3rd argument of `assertBNEqual` is required but I can change that and remove the message here. I also agree this is cluttery.

2022-08-26 08:21 UTC, artdgn commented on test/contracts/PerpsOrdersV2.js
> +				assert.bnEqual(position.margin, '0', 'Margin does not match expected');
nit: some remaining context strings

2022-08-26 14:06 UTC, merged

2022-08-26 14:06 UTC, davidvuong commented
![image](https://user-images.githubusercontent.com/1312550/186921969-442c9c1b-d3cb-46b1-8fb1-557abc8a087c.png)

Merged.