[DRAFT] Changes for V3 migration
Synthetixio/synthetix pull request #1897
Opened 2022-09-09 22:03 UTC by noahlitvin

2022-11-14 15:16 UTC, barrasso requested changes

2022-11-14 15:16 UTC, barrasso commented on cannonfile.toml
> +version = "2.99.0"
do we need `version` defined here? I thought we removed this before because it was leading to some weird deployment issues

2022-11-14 15:16 UTC, barrasso commented on contracts/Issuer.sol
> +        // Consider triggering a migration of liquidateble accounts to V3
is this supposed to be commented out?

2022-11-14 22:01 UTC, dbeal-eth approved these changes

2022-11-14 22:01 UTC, dbeal-eth commented on cannonfile.toml
> +version = "2.99.0"
yea I deliberately put it here now because we need a version lock on 2.99 for certain downstream v3 things to work.

we will continue using 2.99.0 for the rest of time on the cannon side, was my thought.

2022-11-14 22:01 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        // Consider triggering a migration of liquidateble accounts to V3
yes, the migration does not happen during liquidate

2022-11-14 22:01 UTC, dbeal-eth commented on contracts/Issuer.sol
> +        // Consider triggering a migration of liquidateble accounts to V3
should probably be removed altogether tbh

2022-11-15 01:47 UTC, barrasso approved these changes

2022-11-19 02:48 UTC, merged