Feature/time based next price
Synthetixio/synthetix pull request #1899
Opened 2022-09-13 06:13 UTC by davidvuong

2022-09-16 19:44 UTC, leomassazza commented on contracts/MixinFuturesV2DelayedOrders.sol
> +    uint public constant MIN_ORDER_DELAY = 60 seconds;
this constant should be a configuration parameter. See MixinFuturesV2MarketSettings.sol / FuturesV2MarketSettings.sol

2022-09-16 19:50 UTC, leomassazza commented on contracts/MixinFuturesV2DelayedOrders.sol
> +        uint maxTimeDelta,
I'd remove the delay from the function spec and fix it to the min delay configured. (Already asked Afif for the product definition on this)

2022-09-16 20:12 UTC, leomassazza requested changes
love it! nice job. There's a fix needed in the cancellations (to prevent others to cancel the order before time) and maybe add a max delay config param to the order (see Afif comments on discord)

2022-09-20 10:39 UTC, davidvuong commented on contracts/MixinFuturesV2DelayedOrders.sol
> +        uint maxTimeDelta,
We discussed this a little further on Discord and after a few rounds, Afif wanted to allow traders to specify a delay between a min and max (inclusive). As such, I have renamed everything to be more canonical; desired, min, and max.

2022-09-20 10:40 UTC, davidvuong commented on contracts/MixinFuturesV2DelayedOrders.sol
> +    function cancelDelayedOrder(address account) external {
oops! Good catch!

2022-09-27 15:11 UTC, leomassazza approved these changes

2022-09-27 15:12 UTC, leomassazza commented
Approved, but please, don't merge until futuresV2 is audited to ease the reviews

2022-10-04 14:20 UTC, leomassazza commented on contracts/FuturesV2MarketDelayedOrders.sol
> +        require(
According to the SIP,` desiredTimeDelta == 0` is a valid value and defaults to `_minDelayTimeDelta`

2022-10-12 01:33 UTC, davidvuong commented
Builds are failing due to an `npm audit` error. Awaiting fix from `futuresV2`. This is the same problem in #1906. While `futuresV2` is still in development, I'll be merging (not rebasing) commits and resolving tests to avoid drifting too far. Same applies to #1906.

```
npx hardhat test test/contracts/PerpsV2Market.js

  165 passing (4m)
  31 pending
```

```
npx hardhat test test/contracts/PerpsV2Market.delayedOrder.js

  41 passing (1m)
```

2022-10-14 01:51 UTC, leomassazza commented on contracts/PerpsV2MarketDelayedOrders.sol
> +        if (currentRoundId > order.targetRoundId) {
shouldn't be (currentRoundId >= order.targetRoundId) ? (I didn't go to border cases but at first sight it looks >= is more accurate than strictly greater.

2022-11-04 16:16 UTC, merged