Add ARB perpsV2
Synthetixio/synthetix pull request #2056
Opened 2023-03-26 00:16 UTC by leomassazza

2023-03-26 13:27 UTC, kaleb-keny requested changes

2023-03-26 13:27 UTC, kaleb-keny commented on publish/assets.json
> +		"description": "ARB"
For the sake of consistency, would it be ok to update the  description here to "Arbitrum"

2023-03-26 13:27 UTC, kaleb-keny commented on publish/deployed/mainnet-ovm/perpsv2-markets.json
> +		"asset": "ARB",
I believe this what the line that troy was asking about, if we can drop the `s` for, maybe there was a misunderstanding when we spoke about it, as `marketKey` has the `s`, but `asset` doesn't need one.

2023-03-26 13:27 UTC, kaleb-keny commented on publish/deployed/mainnet-ovm/perpsv2-markets.json
> +		"makerFeeOffchainDelayedOrder": "0.0012",
I update these two troy pointed it out yesterday, makerFee is almost always <= takerFee, in order to encourage arbitrage and a balanced skew. If you can please flip these, I posted the necessary PR on the SIP site, that is yet to be merged (i.e. makerFee = 4 bp / takerFee = 12 bp)

2023-03-26 15:00 UTC, leomassazza commented on publish/assets.json
> +		"description": "ARB"
Fixed

2023-03-26 15:00 UTC, leomassazza commented on publish/deployed/mainnet-ovm/perpsv2-markets.json
> +		"makerFeeOffchainDelayedOrder": "0.0012",
Fixed

2023-03-26 15:13 UTC, kaleb-keny approved these changes

2023-03-27 00:21 UTC, barrasso approved these changes

2023-03-27 16:40 UTC, kaleb-keny approved these changes

2023-03-27 17:05 UTC, merged