implements 2078, 2079 and 2080
Synthetixio/synthetix pull request #2205
Opened 2024-02-20 12:49 UTC by kaleb-keny

2024-02-20 13:44 UTC, leomassazza requested changes

2024-02-20 13:44 UTC, leomassazza commented on publish/deployed/mainnet-ovm/perpsv2-markets.json
> +		"maxMarketValue": "1000",
XMR is not mentioned on any of the two SIPs

2024-02-20 13:44 UTC, leomassazza commented on publish/deployed/sepolia-ovm/perpsv2-markets.json
> +		"maxMarketValue": "1000",
same here

2024-02-20 13:55 UTC, kaleb-keny commented on publish/deployed/sepolia-ovm/perpsv2-markets.json
> +		"maxMarketValue": "1000",
ohh yeah you are right leo, it has been already implemented but we never updated the repo https://sips.synthetix.io/sccp/sccp-2078/

2024-02-23 12:39 UTC, leomassazza approved these changes

2024-02-23 12:40 UTC, merged