Identify diff  between deployed and compiled bytecode and report new gas consumption
Synthetixio/synthetix pull request #709
Opened 2020-09-08 19:53 UTC by i-stam

2020-09-11 13:32 UTC, ajsantander requested changes
Looking good! Just a few minor suggestions.

With these fixes, I think that we can wrap this up and merge. I've produced 3 new issues with what we would need to do to continue this topic:
https://github.com/Synthetixio/synthetix-pm/issues/22
https://github.com/Synthetixio/synthetix-pm/issues/23
https://github.com/Synthetixio/synthetix-pm/issues/24

2020-09-11 13:32 UTC, ajsantander commented on buidler.config.js
> +
We might want to override `config.gasReporter.outputFile` tho. Normal gas tests write to `test-gas-used.log`, and we don't want to overwrite those. I suggest `test-gas-used-prod.log`.

2020-09-11 17:31 UTC, i-stam commented on buidler.config.js
> +
You are right about this, I thought i had removed the duplicate logs, most probably I never pushed

2020-09-11 17:33 UTC, i-stam commented on publish/src/commands/prepare-deploy-detect-diff.js
> +	fs.writeFileSync(configFile, stringify(config));
I was wanted to report the total number of contracts: number or names (the list can be pretty long)

2020-09-11 18:21 UTC, i-stam commented on buidler.config.js
> +
I couldn't find a way to do it. the output file is specified in `buidler.config.js` by setting `gasReporter:outputFile` and this could be a problem for Ci when we want to have multiple multiple `codechecks` and reports.

2020-09-11 20:06 UTC, ajsantander commented on buidler.config.js
> +
I tried it out and I was able to do it by setting in in the test:prod task.

2020-09-11 20:07 UTC, ajsantander commented on publish/src/commands/prepare-deploy-detect-diff.js
> +	fs.writeFileSync(configFile, stringify(config));
Well, I didn't mean to list the contracts, just report the number.

2020-09-14 12:32 UTC, ajsantander approved these changes

2020-09-14 12:33 UTC, merged