EchangeRates modifications + tests
Synthetixio/synthetix pull request #715
Opened 2020-09-14 12:51 UTC by clementbalestrat

2020-09-14 12:52 UTC, clementbalestrat commented on contracts/ExchangeRates.sol
> +import "./interfaces/AggregatorV2V3Interface.sol";
@justinjmoses just waiting for chainlink to add it to their repo

2020-09-14 16:41 UTC, justinjmoses commented on contracts/ExchangeRates.sol
> +import "./interfaces/AggregatorV2V3Interface.sol";
It's done. Please upgrade to `0.0.10`

2020-09-14 16:41 UTC, justinjmoses commented on contracts/ExchangeRates.sol
> +        aggregator.latestRoundData();
you don't want to put a require in here to be more explicit?

2020-09-14 16:43 UTC, justinjmoses commented on contracts/ExchangeRates.sol
> +        aggregator.latestRoundData();
Also, should we not `require` that `decimals` is <= 18?

2020-09-14 16:45 UTC, justinjmoses commented on test/contracts/ExchangeRates.js
> +const MockAggregator = artifacts.require('MockAggregatorV2V3');
Is there any point keeping the old `MockAggregator` around?

2020-09-14 16:46 UTC, justinjmoses commented on test/contracts/ExchangeRates.js
> +const MockAggregator = artifacts.require('MockAggregatorV2V3');
It's used by the publish tests, which are currently breaking: https://app.circleci.com/pipelines/github/Synthetixio/synthetix/3441/workflows/31d93e6b-bdf5-41a9-a2e6-c5cfcd110a65/jobs/19683

2020-09-14 16:46 UTC, justinjmoses requested changes
Comments inline

2020-09-14 16:59 UTC, justinjmoses commented
Also @clementbalestrat can you make sure you add all updated contracts to `publish/releases.json` so they are marked for release?

2020-09-16 14:01 UTC, justinjmoses commented on contracts/test-helpers/MockAggregatorV2V3.sol
> +interface AggregatorV2V3Interface {
So you can simply use `import "@chainlink/contracts-0.0.10/src/v0.5/interfaces/AggregatorV2V3Interface.sol";
` instead, however if you do, then you'll need to stub out everything in the mock. Which would you prefer?

2020-09-16 14:01 UTC, justinjmoses commented on contracts/test-helpers/MockAggregatorV2V3.sol
> +    struct Entry {
I'll ask Chainlink to add this to future versions of their interface

2020-09-16 14:03 UTC, justinjmoses submitted a review, later dismissed
Just a comment about the interface def in the mock.

Additionally, please hold on merging this as #699 can be PRed into here first.

2020-09-17 20:09 UTC, justinjmoses requested changes
Blocked pending merge of #699

2020-09-18 00:31 UTC, justinjmoses approved these changes
One remaining comment: https://github.com/Synthetixio/synthetix/pull/715/files#r489461873

2020-09-18 02:17 UTC, merged