Assimilate l2-comms into a scripts folder
Synthetixio/synthetix pull request #762
Opened 2020-09-28 18:58 UTC by ajsantander

WIP

2020-09-28 19:02 UTC, justinjmoses commented on scripts/status.js
> +	/* ~~~~ FixedSupplySchedule ~~~~ */
Note: a lot of this is shared with SupplySchedule - perhaps we just use the SupplySchedule ABI and report on whatever both have in common?

2020-09-28 19:06 UTC, justinjmoses commented on scripts/status.js
> +		logItem('FixedSupplySchedule.mintableSupply', supply);
Also we should split these out into a file per contract I reckon. I'd also love one for ExchangeRates that shows the rates (like the testnet script)

2020-09-29 21:10 UTC, ajsantander commented on scripts/status.js
> +	/* ~~~~ FixedSupplySchedule ~~~~ */
Nice. Done.

2020-09-29 21:11 UTC, ajsantander commented on scripts/status.js
> +		logItem('FixedSupplySchedule.mintableSupply', supply);
Improvements for the future? My goal in this PR is to reproduce what we had in l2-comms in this repo, in a way that is extensible and easy to use.

2020-09-29 21:54 UTC, justinjmoses requested changes
A couple of minor changes

2020-09-29 21:54 UTC, justinjmoses commented on buidler.config.js
> +usePlugin('@nomiclabs/buidler-ethers');
Is this still needed?

2020-09-29 21:54 UTC, justinjmoses commented on package.json
> +		"@nomiclabs/buidler-ethers": "^2.0.0",
and this?

2020-09-29 21:54 UTC, justinjmoses commented on scripts/airdrop.js
> +		const l2Balance = await Synthetix.balanceOf(address);
we should also check make sure there have been no transfer events in some recent window of time.

2020-09-29 21:54 UTC, justinjmoses commented on scripts/status.js
> +	await logRate('SNX');
could we also log all synths?

2020-09-30 14:14 UTC, ajsantander commented on buidler.config.js
> +usePlugin('@nomiclabs/buidler-ethers');
Good catch, thanks.

2020-09-30 14:15 UTC, ajsantander commented on scripts/airdrop.js
> +		const l2Balance = await Synthetix.balanceOf(address);
Do you think this is still required, given that the script now demands that the system be suspended?

2020-09-30 17:17 UTC, justinjmoses commented on scripts/airdrop.js
> +		const l2Balance = await Synthetix.balanceOf(address);
Ah well you can't transfer SNX at all if the system is suspended. 🤔

2020-10-01 20:55 UTC, justinjmoses commented on scripts/status.js
> +	const synths = JSON.parse(fs.readFileSync(synthsPath));
Why not use `getSynths()` ?

2020-10-01 21:11 UTC, ajsantander commented on scripts/status.js
> +	const synths = JSON.parse(fs.readFileSync(synthsPath));
Nize

2020-10-01 22:40 UTC, justinjmoses approved these changes
:shipit:

2020-10-02 11:47 UTC, merged