update deploy.js to use versions for old extrates
Synthetixio/synthetix pull request #780
Opened 2020-10-08 00:34 UTC by jacko125

2020-10-08 01:36 UTC, hav-noms submitted a review, later dismissed

2020-10-08 01:46 UTC, justinjmoses approved these changes

2020-10-08 01:46 UTC, justinjmoses requested changes

2020-10-08 01:46 UTC, justinjmoses commented on publish/src/commands/deploy.js
> +	const exchangeRatesVersions = getVersions({ network, byContract: true }).ExchangeRates;
this won't work in local mode though where there are no historic versions

2020-10-08 01:49 UTC, justinjmoses commented on publish/src/commands/deploy.js
> +	const exchangeRatesVersions = getVersions({ network, byContract: true }).ExchangeRates;
you should also include `path, fs` as well

2020-10-08 02:54 UTC, jacko125 commented on publish/src/commands/deploy.js
> +	const exchangeRatesVersions = getVersions({ network, byContract: true }).ExchangeRates;
will update this to be more comprehensive and handle getExistingContracts()

2020-10-08 15:24 UTC, justinjmoses commented on publish/src/commands/deploy.js
> +	const exchangeRatesVersions = getVersions({ network, byContract: true }).ExchangeRates;
Instead of this approach, why not have `getExistingContract` use `getVersions` instead, it's what we should do now that we have access to historical versions.

2020-10-16 19:29 UTC, justinjmoses commented
Ping on this @jacko125

2020-10-24 06:32 UTC, jacko125 commented
> Ping on this @jacko125

Ready for review. Merged latest changes in deploy.js in. Tested against `local:test` run

2020-10-28 23:28 UTC, justinjmoses approved these changes
LGTM Jacko - if you remove the lock file change the tests should all pass.

2020-10-29 13:00 UTC, justinjmoses approved these changes

2020-10-29 13:02 UTC, merged