Deploy.js: Skip AddressResolver-dependent steps until addresses have been properly imported.
Synthetixio/synthetix pull request #802
Opened 2020-10-14 03:10 UTC by zyzek

2020-10-16 19:36 UTC, justinjmoses approved these changes
LGTM

2020-10-21 20:29 UTC, ajsantander approved these changes
Just left one suggestion.

As a general comment, something to consider when refactoring this file, is that it is so big that a minor change diffed a lot of lines and made this diff hard to review, when it is not such a big change logically.

2020-10-21 20:29 UTC, ajsantander commented on publish/src/commands/deploy.js
>  	}
@zyzek maybe it would be a good idea to either (1) exit the script here, or (2) prompt the user for continuing after owner actions are set.

2020-10-21 20:35 UTC, ajsantander requested changes
Sorry, changing my previous approval to "request changes" to make sure that my comment is addressed. Perhaps we should stop the script or hold it instead of just letting it continue with a console log.

2020-10-22 07:35 UTC, zyzek commented on publish/src/commands/deploy.js
>  	}
I think I prefer just exiting the script; prompting the user to continue also I think necessitates checking that everything has been imported properly before continuing successfully. I did start implementing this but I realised that we get the same result anyway by just re-running deploy.js.

It's already very close to the end of the script, so maybe it's a bit much to actually exit early, but at least I can change the printed message and exit with status code 1.

2020-10-22 16:08 UTC, ajsantander approved these changes

2020-10-22 16:08 UTC, ajsantander commented on publish/src/commands/deploy.js
>  	}
That's awesome. Thanks @zyzek

2020-10-23 01:10 UTC, ajsantander approved these changes

2020-10-23 03:52 UTC, merged