Debt snapshots L2 refactor
Synthetixio/synthetix pull request #811
Opened 2020-10-19 21:11 UTC by zyzek

- [ ] Realtime/L2 `DebtCache` version
- [ ] Fix deploy.js (in particular `IssuerWithoutUpdatableCache` on `useOvm`)
- [ ] Add multi-synth add/remove functions to issuer and update deploy.js
- [ ] Remove flexible storage from debt cache
- [ ] Fix other test suites (prod, coverage, &c.)
- [ ] Update the keeper with the new interfaces.

2020-10-22 19:35 UTC, justinjmoses submitted a review, later dismissed
Just a few nps, otherwise LGTM

2020-10-22 19:35 UTC, justinjmoses commented on contracts/RealtimeDebtCache.sol
> +// https://docs.synthetix.io/contracts/RealtimeDebtCache
actually these urls are wrong - it should be /contracts/source/contracts/RealtimeDebtCache

2020-10-22 19:35 UTC, justinjmoses commented on publish/src/commands/deploy.js
> +		deps: ['AddressResolver', 'DebtCache'],
You don't need to do this - this is just for deps that would break contract instantiation. For those required by the address resolver, we don't include them in deps (otherwise we'd have to change the deploy script a whole lot)

2020-10-22 19:35 UTC, justinjmoses commented on publish/src/commands/deploy.js
> +		deps: ['AddressResolver', 'DebtCache'],
(ibid)

2020-10-22 19:35 UTC, justinjmoses commented on test/contracts/setup.js
> +		const chunkSize = 15;
This is probably overkill - can just keep using the singular `addSynth` for the test setup script

2020-10-23 02:26 UTC, zyzek commented on contracts/RealtimeDebtCache.sol
> +// https://docs.synthetix.io/contracts/RealtimeDebtCache
Ah, right you are. I've fixed this for all the existing files.

2020-10-23 02:40 UTC, zyzek commented on publish/src/commands/deploy.js
> +		deps: ['AddressResolver', 'DebtCache'],
Noted, and fixed.

2020-10-23 02:40 UTC, zyzek commented on publish/src/commands/deploy.js
> +		deps: ['AddressResolver', 'DebtCache'],
Also fixed.

2020-10-23 02:55 UTC, zyzek commented on test/contracts/setup.js
> +		const chunkSize = 15;
I've reverted this. The idea was to see if it sped up any test suites, but given there aren't any that add a lot of synths, it seems not to make a difference.

2020-10-23 04:14 UTC, jacko125 commented on contracts/ContractStorage.sol
> +// https://docs.synthetix.io/contracts/source/contracts/contractstorage
Is this supposed to be Upper case for `ContractStorage` ?

2020-10-29 19:51 UTC, ajsantander requested changes
Looking good @zyzek !

A couple minor requests (apart from those made via inline comments):
1) Add Issuer and DebtCache to releases.json
2) Remove Issuer and IssuerWithoutUpdatableCache from ovm-ignore.json

2020-10-29 19:51 UTC, ajsantander commented on contracts/RealtimeDebtCache.sol
> +    // Report the current debt values from all all cached debt functions
nit: "all all" typo

2020-10-29 22:42 UTC, zyzek commented on contracts/DebtCache.sol
> +    function takeDebtSnapshot() external requireSystemActiveIfNotOwner {
There is already a `_currentDebt`, but I am not using it, since `takeDebtSnapshot` on each loop iteration needs to cache the debt of the synth it's currently up to, so it seemed more graceful to recapitulate and extend the logic from `_currentDebt`.

2020-10-29 22:42 UTC, zyzek commented on contracts/RealtimeDebtCache.sol
> +    // Report the current debt values from all all cached debt functions
Nice catch; corrected.

2020-11-01 23:38 UTC, zyzek commented
Ok good call, I'm getting some mysterious reverts with the fork prod test when the tests try to issue or exchange synths through the `Synthetix` contract. No error messages and this doesn't affect issuance for some reason. I'll investigate...

2020-11-04 07:07 UTC, zyzek commented
Fixed the prod tests, ready for another look @ajsantander .

2020-11-04 13:54 UTC, ajsantander commented on publish/releases.json
> +			"SynthetixBridgeToOptimism",
Do we need to deploy SynthetixBridgeToOptimism in L1 mainnet right now?

2020-11-04 14:03 UTC, ajsantander commented
@zyzek I ran the prod tests after your latest changes and they all pass, awesome 🙌

2020-11-04 14:11 UTC, ajsantander approved these changes

2020-11-04 21:41 UTC, zyzek commented on publish/releases.json
> +			"SynthetixBridgeToOptimism",
Removed this and SystemSettings.

2020-11-04 23:06 UTC, merged