Gas tank
Synthetixio/synthetix pull request #812
Opened 2020-10-20 00:45 UTC by clementbalestrat

2020-10-20 19:35 UTC, justinjmoses commented on contracts/test-helpers/StubFlexibleStorage.sol
> +contract StubFlexibleStorage is IFlexibleStorage {
This seems like a huge stub. Why not just use the real `FlexibleStorage` instead of rewriting all this?

2020-10-20 19:39 UTC, justinjmoses commented on contracts/GasTank.sol
> +contract GasTank is Owned, MixinResolver, ReentrancyGuard, MixinSystemSettings {
Please implement the `IGasTank` interface

2020-10-21 19:36 UTC, justinjmoses commented on contracts/GasTank.sol
> +        return (_gas + PAYGAS_COST) * currentGasPrice() + getKeeperFee().divideDecimal(currentEtherPrice());
Can you use SafeMath operators

2020-10-21 19:37 UTC, justinjmoses commented on contracts/GasTank.sol
> +        address contractAddress = resolver.requireAndGetAddress(_contractName, "Missing contract address");
Note this won't handle upgrades of contracts, as you are persisting the address of the contract that has access, not the label. Perhaps the label is better to persist?

2020-10-21 19:39 UTC, justinjmoses commented on test/contracts/GasTank.spec.js
> +	beforeEach(async () => {
we still need the `ensureOnlyExpectedMutativeFunctions` checks

2020-10-21 19:40 UTC, justinjmoses commented on test/contracts/GasTank.spec.js
> +	describe('approveContract', () => {
You need to use `onlyGivenAddressCanInvoke` to ensure it is protected

2020-10-21 19:41 UTC, justinjmoses commented on test/contracts/GasTank.spec.js
> +			await assert.revert(
please use `onlyGivenAddressCanInvoke` with no `address` so it checks the range of `accounts`

2020-10-21 19:41 UTC, justinjmoses commented on contracts/GasTank.sol
> +    ) internal nonReentrant {
We should check re-entrancy protection in a test.

2020-10-21 19:43 UTC, justinjmoses commented on test/contracts/setup.js
> +				'SynthetixState',
You can't mock `SynthetixState` as well?

2020-10-21 19:44 UTC, justinjmoses requested changes
Comments inline

2020-10-23 03:49 UTC, zyzek requested changes

2020-10-23 03:49 UTC, zyzek commented on contracts/GasTank.sol
> +        if (maxGasPriceOf(_spender) > 0) {
You can save `maxGasPriceOf(_spender)` to a local variable to save the overhead of a second function call inside the conditional.

While we're on it: does the extra constant in the `executionCost` call correspond to `maxGasPriceOf(_spender) == 0` or `maxGasPriceOf(_spender) > 0`? I guess it should be the latter.

2020-10-23 03:49 UTC, zyzek commented on contracts/GasTank.sol
> +        require(tx.gasprice >= currentGasPrice(), "Gas price is too low");
We're doing two calls to `currentGasPrice`; one here and one inside `executionCost`. I'd probably compute this once an then pass it into an internal version of `executionCost` which takes in the gas price as an argument, and is also called by the public function.

I'd also check `tx.gasprice >= currentGasPrice()` before computing `etherSpent`, which will save a bit of gas in case the tx fails... Though given that this `payGas` operation is happening at the very end of the execution maybe that's pretty negligible.

I forget if we made any decisions about contracts being able to "lock" a value of the user's ether; e.g. you submit a limit order and you have to keep at least enough ether in there to cover the execution cost of that order.

2020-10-23 03:49 UTC, zyzek commented on contracts/SystemSettings.sol
> +    uint public constant MAX_KEEPER_FEE = 1e18 * 10;
Could just be `10e18` I think?

2020-10-23 03:49 UTC, zyzek commented on contracts/GasTank.sol
> +contract GasTank is Owned, MixinResolver, ReentrancyGuard, MixinSystemSettings, IGasTank {
Add a link to the documentation page that will be generated for this contract: https://docs.synthetix.io/contracts/source/contracts/gastank. You should also do the same for the `IGasTank` interface.

2020-10-23 03:49 UTC, zyzek commented on contracts/SystemSettings.sol
> +    uint public constant MAX_KEEPER_FEE = 1e18 * 10;
We probably should add this parameter as a value in the `defaults` object defined in `index.js`. Not sure what we agreed the initial default value should be. Was it zero?

With the default, we'll also need to add a test that it's been set up properly in `test/publish/index.js`, along with all the other default value tests. (line 260 or so)

2020-10-23 03:49 UTC, zyzek commented on test/contracts/GasTank.spec.js
> +			assert.bnGt(toBN(keeperAccountBalance), toBN(keeperAccountInitialEthBalance));
We should be able to check that this is sending back the right amount by checking something like:

```
const gasSpent = tx.receipt.gasUsed;
const gasRefund = gasSpent.mul(fastGasPriceDefault);
const keeperFee = divideDecimalRound(keeperFeeDefault, ethPriceDefault); // imported from test/utils/index.js

assert.bnClose(keeperAccountBalance, keeperAccountInitialEthBalance.add(gasRefund).add(keeperFee));
```

Some of the particular names and logic might be off but that's the general idea.

2020-10-23 03:49 UTC, zyzek commented on test/contracts/GasTank.spec.js
> +			assert.bnGt(toBN(keeperAccountBalance), toBN(keeperAccountInitialEthBalance));
Might have to pass bnClose a slightly larger threshold value as the third argument, but I think it's important to make sure the gas being refunded is not too far off its intended value.

2020-10-23 03:49 UTC, zyzek commented on contracts/test-helpers/Keeper.sol
> +        uint gasConsummed = gasleft();
nitpick: Consummed -> Consumed

2020-10-23 03:49 UTC, zyzek commented on contracts/GasTank.sol
> +        _recipient.transfer(etherSpent);
So consensys recommends that we don't use `.transfer` anymore. https://diligence.consensys.net/blog/2019/09/stop-using-soliditys-transfer-now/

Should we remove it here, and in `_withdrawEther`?

Thoughts on this @justinjmoses @ajsantander ?

2020-10-23 04:36 UTC, clementbalestrat commented on test/contracts/setup.js
> +				'SynthetixState',
Actually @justinjmoses I realised I can't mock `Synthetix`. Some of the tests fail with `Transaction reverted: function returned an unexpected amount of data`

2020-11-02 01:06 UTC, clementbalestrat commented on contracts/GasTank.sol
> +        address contractAddress = resolver.requireAndGetAddress(_contractName, "Missing contract address");
hmmm I'm not sure. 

How do you handle `require(approved[msg.sender], "Contract is not approved");` in `PayGas` then?

2020-11-02 04:46 UTC, clementbalestrat commented on contracts/GasTank.sol
> +    ) internal nonReentrant {
Then it probably makes sense to test every contract using this protection?

2020-11-02 06:22 UTC, clementbalestrat commented on contracts/GasTank.sol
> +        require(tx.gasprice >= currentGasPrice(), "Gas price is too low");
regarding your last point, I can't remember either. Let's decide when we actually implement a keeper.

2020-11-02 06:37 UTC, clementbalestrat commented on contracts/SystemSettings.sol
> +    uint public constant MAX_KEEPER_FEE = 1e18 * 10;
Probably not `MAX_KEEPER_FEE` as it is just a limit. I guess you meant the default `KEEPER_FEE`.

2020-11-02 07:23 UTC, clementbalestrat commented on test/contracts/GasTank.spec.js
> +			assert.bnGt(toBN(keeperAccountBalance), toBN(keeperAccountInitialEthBalance));
yeah good call

2022-04-30 03:47 UTC, closed without merging