SIP 89 Virtual Synths
Synthetixio/synthetix pull request #821
Opened 2020-10-28 14:33 UTC by justinjmoses

2020-10-29 15:48 UTC, justinjmoses commented
Example of running `Synthetix.prod.js`

![image](https://user-images.githubusercontent.com/799038/97597783-9a783200-19dc-11eb-9241-1dba85ff1ba4.png)

at the same time, here was the rate on 1inch

![image](https://user-images.githubusercontent.com/799038/97597818-a49a3080-19dc-11eb-8a61-a742a03a3927.png)

2020-11-06 11:55 UTC, jacko125 commented on contracts/Exchanger.sol
> +    function _createVirtualSynth(
Is the concept with `ExchangerWithVirtualSynth` that overrides the internal function `_createVirtualSynth` in the Exchanger class supposed to be that the former will be whats deployed on L1 and the normal "Exchanger" contract will be only be on OVM ?

2020-11-06 12:05 UTC, jacko125 commented on contracts/Exchanger.sol
> +    function exchangeWithVirtual(
I'd split the VirtualSynth creation outside of the internal `_exchange` function for separation of concerns so that `exchangeWithVirtual()` would create a VirtualSynth instead of relying on a bool flag to determine if an VirtualSynth is created within `_exchange`.

This could be.a limitation with the stack too deep issue instead of returning the required variables to setup a virtual synth not inside `_exchange` ?

2020-11-06 13:35 UTC, justinjmoses commented
This needs to be moved to a PR with a new branch name to trigger the `workflow-develop` CI flow

2020-11-06 13:44 UTC, zyzek requested changes
Leaving several comments now, but will continue reviewing.

2020-11-06 13:44 UTC, zyzek commented on contracts/Exchanger.sol
> +            dest.issue(address(vSynth), amountReceived);
It's a bit of a nitpick, but a minor amount of space can be saved by reassigning the recipient address and using only one `issue` call, as follows:

```solidity
if (virtualSynth) {
    recipient = address(_createVirtualSynth(dest, recipient, amountReceived);
}

dest.issue(recipient, amountReceived);
```

2020-11-06 13:44 UTC, zyzek commented on contracts/Exchanger.sol
> +    function exchangeWithVirtual(
I was thinking this too; however the destination account needs to be known before the exchange (which is either the vSynth or the original recipient), and the vSynth needs to know the amount received after the exchange.
It's possible to do this by breaking the `_exchange` function up into the bits before the call to `_convert`, and the bits after, but I'm not sure this is any cleaner than what's here. Perhaps we can just do the exchange quantity calculation by itself and construction of the vSynth before rather than after the exchange itself, and pass these in as parameters?

2020-11-06 13:44 UTC, zyzek commented on contracts/Exchanger.sol
> +            dest.issue(address(vSynth), amountReceived);
Alternately, `_createVirtualSynth` on this layer could just return the recipient or zero address, and then the if statement can be removed, and the `virtualSynth` bool argument removed entirely in the enclosing call to _exchange by relying on the function overriding. E.g.:

```solidity
vSynth = _createVirtualSynth(dest, recipient, amountReceived); // on layer 2 returns address(0);
address recipientOrSynth = vSynth == address(0) ? recipient : vSynth;
dest.issue(recipient, amountReceived);
```

2020-11-06 13:44 UTC, zyzek commented on contracts/ExchangerWithVirtualSynth.sol
> +    event VirtualSynthCreated(address vSynth, address synth, bytes32 currencyKey, uint amount);
Does this strictly need the currency key? One assumes it could always be recovered from the synth itself at the block this was emitted.

2020-11-06 14:31 UTC, zyzek requested changes

2020-11-06 14:31 UTC, zyzek commented on contracts/VirtualSynth.sol
> +    function decimals() external pure returns (uint8) {
Do we need both a public `DECIMALS` constant and this external `decimals` function? Isn't renaming `DECIMALS` to `decimals` sufficient to satisfy the ERC20 extended interface? Or am I missing some integration that expects the `DECIMALS` form?

2020-11-06 14:31 UTC, zyzek commented on contracts/interfaces/IVirtualSynth.sol
> +interface IVirtualSynth {
`secsLeftInWaitingPeriod` seems to be missing from the interface; `resolver`, as well, if we think that's needed at all.

2020-11-06 19:39 UTC, justinjmoses commented on contracts/Exchanger.sol
> +    function exchangeWithVirtual(
Yeah Anton's point answers your Jacko. But doing the creation first could definitely work and might be a lot nicer. Let me look into this.

2020-11-06 19:41 UTC, justinjmoses commented on contracts/ExchangerWithVirtualSynth.sol
> +    event VirtualSynthCreated(address vSynth, address synth, bytes32 currencyKey, uint amount);
No not strictly - it just seemed like it might be better for reporting - but def not critical.

2020-11-06 19:41 UTC, justinjmoses commented on contracts/VirtualSynth.sol
> +        // Note: we can do this as Exchanger will issue this amount to us
yep

2020-11-06 19:42 UTC, justinjmoses commented on contracts/VirtualSynth.sol
> +    function decimals() external pure returns (uint8) {
I was just following the convention in `Synth.sol` but yeah, different scenario. I'll fix it up.

2020-11-06 19:46 UTC, justinjmoses commented on contracts/interfaces/IVirtualSynth.sol
> +interface IVirtualSynth {
Agreed on `secs` but not necessary on the `resolver`.

2020-11-07 18:56 UTC, justinjmoses commented
Closed for #857

2020-11-07 18:56 UTC, closed without merging