Fixing underlying issue with settler on vSynth
Synthetixio/synthetix pull request #881
Opened 2020-11-12 19:55 UTC by justinjmoses

2020-11-12 22:06 UTC, jacko125 submitted a review, later dismissed
Approved.

2020-11-13 00:52 UTC, zyzek requested changes
One small query. Also just to point out that we're going to need to be careful about settling all vSynths if we ever purge any Synths with outstanding settlements in future.

2020-11-13 00:52 UTC, zyzek commented on contracts/Exchanger.sol
> -            destinationAddress,
Do we not also need to do this when emitting the exchange event just above as well?

2020-11-13 00:55 UTC, jacko125 commented
> One small query. Also just to point out that we're going to need to be careful about settling all vSynths if we ever purge any Synths with outstanding settlements in future.

I think we should have a keeper settle and execute the vSynths to their final destinations as soon as possible. That was something discussed before so for the trader / user they wouldn't have to do anything manually to get the wBTC for example.

2020-11-13 02:01 UTC, zyzek approved these changes

2020-11-13 02:03 UTC, jacko125 approved these changes
Lgtm the changes

2020-11-13 02:48 UTC, merged