Build circleci config with Mustache
Synthetixio/synthetix pull request #883
Opened 2020-11-12 22:01 UTC by ajsantander

The CircleCI CLI has a command for packing a config file called "pack", but we found it to be very limited in terms of what it can do. Using Mustache would seem to be a much more powerful approach.

2020-11-13 17:18 UTC, justinjmoses commented on package.json
> +			"pre-commit": "npm run lint && pretty-quick --staged"
Qu: don't you want to validate at least on pre-commit?

2020-11-13 17:19 UTC, justinjmoses commented on package.json
> +		"mustache": "^4.0.1",
Isn't this more of a dev dependency? It's really just to build CI config when we change it.

2020-11-13 17:20 UTC, justinjmoses requested changes
Overall a good direction for sure, but a few things to consider

2020-11-13 20:47 UTC, ajsantander commented on package.json
> +		"mustache": "^4.0.1",
Moved to devDependencies

2020-11-13 20:48 UTC, ajsantander commented on package.json
> +			"pre-commit": "npm run lint && pretty-quick --staged"
Actually, went a little bit further. This is now handled in the pack.js script, and will only run circleci if available in the OS.

2020-11-20 14:11 UTC, justinjmoses commented on package.json
> +			"pre-commit": "npm run lint && pretty-quick --staged"
How is that happening?

2020-11-20 14:13 UTC, ajsantander commented on package.json
> +			"pre-commit": "npm run lint && pretty-quick --staged"
It uses execa to run the circleci command, and catches failures: https://github.com/Synthetixio/synthetix/pull/883/files#diff-7906ff03d65275e67cb294aedd9c5f682a4301f8ba0d0ebeeb44aac8cc9a07c1R49-R54

Of course, it can also fail because the circleci command was run and exited with 1. In that case, the developer will have to pay attention to the output.

2020-11-20 15:12 UTC, justinjmoses approved these changes

2020-11-20 15:12 UTC, merged