Check if resolver needs imports and if bridge needs sync separately
Synthetixio/synthetix pull request #944
Opened 2020-12-02 18:04 UTC by ajsantander

The connect-bridge was not syncing cache on the bridge if its resolver didnt need to import any addresses. However, if for example the bridge has a new dependency, its cache might be out of sync. So the script now separately checks if the bridge's cache is out of sync.

2020-12-02 18:45 UTC, i-stam approved these changes
lgtm, perhaps we could somehow test it to be sure that it works as expected

2020-12-08 12:25 UTC, justinjmoses commented on publish/src/commands/connect-bridge.js
> +			.isResolverCached(AddressResolver.options.address)
This has changed now due to SIP-100

2020-12-08 12:25 UTC, justinjmoses requested changes

2020-12-08 12:25 UTC, justinjmoses commented on publish/src/commands/connect-bridge.js
> +				.setResolverAndSyncCache(AddressResolver.options.address)
(ibid - from SIP-100)

2020-12-08 15:28 UTC, ajsantander commented on publish/src/commands/connect-bridge.js
> +			.isResolverCached(AddressResolver.options.address)
Updated

2020-12-08 15:28 UTC, ajsantander commented on publish/src/commands/connect-bridge.js
> +				.setResolverAndSyncCache(AddressResolver.options.address)
Updated

2020-12-11 16:45 UTC, justinjmoses approved these changes

2020-12-11 16:46 UTC, merged