Safety check for ensuring gas deployment limit
Synthetixio/synthetix pull request #955
Opened 2020-12-09 11:22 UTC by i-stam

- This adds a new parameter, namely `ensureOvmDeploymentGasLimit`,  to the `deploy` and `deployer` scripts to ensure that each contract deployment does not exceed the 9mil gas cap when deploying to the OVM.

2020-12-09 13:11 UTC, ajsantander commented on publish/src/commands/deploy.js
> +				'-e, --ensure-ovm-deployment-gas-limit <value>',
I'd rename this to something sligthly more convenient, like `--max-ovm-deployment-gas` and give it a default value of `9000000`, which is something you can do with commander. See the other params.

2020-12-09 13:12 UTC, ajsantander commented on publish/src/Deployer.js
> +					if (gasUsed > 9000000) {
The variable incoming from deploy.js is not a boolean. I believe its a number, so you should use `gas > this.ensureOvmDeploymentGasLImit`.

2020-12-09 13:14 UTC, ajsantander requested changes
This is the right way to do it @i-stam , just some minor necessary tweaks.

Also, this makes me think... should we make this restriction applicable to any tx, that is not just deployment transactions? I can imagine how an `AddressResolver.rebuildCaches()` call could easily exceed the limit.

2020-12-09 13:16 UTC, justinjmoses commented on publish/src/commands/deploy.js
> +				'-e, --ensure-ovm-deployment-gas-limit <value>',
should we not make the param just a flag and hardcode in the `9m` amount?

2020-12-09 15:13 UTC, ajsantander commented
Also @i-stam we already have a `contractDeploymentGasLimit` parameter on the deploy script. Couldn't this somehow be used for what we need, without having to add a new parameter?

2020-12-14 21:16 UTC, ajsantander commented
We should be able to control this using the deploy command's `contractDeploymentGasLimit` parameter. There's no need to add a new parameter.

2020-12-14 21:16 UTC, closed without merging