Always return named parameter for resolverAddressesRequired()
Synthetixio/synthetix pull request #981
Opened 2020-12-15 21:08 UTC by ajsantander

2020-12-15 21:23 UTC, justinjmoses requested changes
The signature isn't accurate in a couple of contracts - I suspect it compiles because it's using the signature from `MixinResolver` but still it's good to be accurate. Can you please double check and fix those?

2020-12-15 21:23 UTC, justinjmoses commented on contracts/SynthetixBridgeToBase.sol
> +        addresses = combineArrays(existingAddresses, addresses);
it's not named above :(

2020-12-15 21:23 UTC, justinjmoses commented on contracts/SynthetixBridgeToOptimism.sol
> +        addresses = combineArrays(existingAddresses, addresses);
as above.

2020-12-16 02:50 UTC, jacko125 approved these changes

2020-12-16 09:09 UTC, jacko125 approved these changes

2020-12-16 13:55 UTC, ajsantander commented on contracts/SynthetixBridgeToBase.sol
> +        addresses = combineArrays(existingAddresses, addresses);
Oops! Fixed.

2020-12-16 13:55 UTC, ajsantander commented on contracts/SynthetixBridgeToOptimism.sol
> +        addresses = combineArrays(existingAddresses, addresses);
Also fixed.

2020-12-16 15:20 UTC, justinjmoses approved these changes

2020-12-16 15:21 UTC, merged